[#vol2_clause_appendix_mdpws_discovery_proxy]
=== Discovery Proxy implementation requirements

This chapter describes requirements to the <<vol1_spec_sdpi_p_actor_discovery_proxy>> <<acronym_mdpws>> binding that go beyond message outlines and semantics specified in <<vol2_clause_dev_46>> and <<vol2_clause_dev_47>>.

.R7007
[sdpi_requirement#r7007,sdpi_req_level=shall,sdpi_req_type=tech_feature]
****
[NORMATIVE]
====
A <<vol1_spec_sdpi_p_actor_discovery_proxy>> shall provide the Discovery Proxy service by implementing the port type
with the <<term_q_name>> dp:DiscoveryProxy.
====

[NOTE]
====
* The <<vol1_spec_sdpi_p_actor_discovery_proxy>> port type is defined in <<vol2_clause_appendix_a_mdpws_wsdl>>.

* The OID used for the target namespace of the <<vol1_spec_sdpi_p_actor_discovery_proxy>> WSDL file is listed in <<vol2_table_appendix_mdpws_discovery_proxy_oids>>.
====
****

.R7008
[sdpi_requirement#r7008,sdpi_req_level=shall,sdpi_req_type=tech_feature]
****

[NORMATIVE]
====
A <<vol1_spec_sdpi_p_actor_discovery_proxy>> shall accept the WS-Eventing wse:Filter@Dialect
urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.2.1.
====

[NOTE]
====
The OID used for the filter dialect is listed in <<vol2_table_appendix_mdpws_discovery_proxy_oids>>.
====
****

.R7009
[sdpi_requirement#r7009,sdpi_req_level=shall,sdpi_req_type=tech_feature]
****
[NORMATIVE]
====
A <<vol1_spec_sdpi_p_actor_somds_consumer>> shall add the filter dialect urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.2.1 to
every Subscribe request to a <<vol1_spec_sdpi_p_actor_discovery_proxy>>.
====

[NOTE]
====
The OID used for the filter dialect is listed in <<vol2_table_appendix_mdpws_discovery_proxy_oids>>.
====
****

==== Utilized OIDs

All object identifiers used by the <<vol1_spec_sdpi_p_actor_discovery_proxy>> are specified in <<vol2_table_appendix_mdpws_discovery_proxy_oids>>.

[#vol2_table_appendix_mdpws_discovery_proxy_oids]
.WS-Eventing subscription filter dialect and WSDL target namespace OID assignments
[cols="2,3,1",options="autowidth, header"]
|===
| Primary identifier
| Concept description
| Secondary identifier

| 1.3.6.1.4.1.19376.1.6.2.10
| Profile specific OID for SDPi
| sdpi

| 1.3.6.1.4.1.19376.1.6.2.10.1
| Describes namespaces for different purposes as specified by its sub-nodes
| namespaces

| 1.3.6.1.4.1.19376.1.6.2.10.1.2
| Identifies <<vol1_spec_sdpi_p_actor_discovery_proxy>> objects.
| discovery-proxy

| 1.3.6.1.4.1.19376.1.6.2.10.1.2.1
| Subscription filter dialect used to identify Hello/Bye subscriptions provided by a <<vol1_spec_sdpi_p_actor_discovery_proxy>>.
| subscription-filter

| 1.3.6.1.4.1.19376.1.6.2.10.1.2.2
| WSDL target namespace identifier for the <<vol1_spec_sdpi_p_actor_discovery_proxy>> actor.
| wsdl
|===

==== Discovery Proxy WSDL

<<vol2_clause_appendix_a_mdpws_wsdl>> shows the WSDL file that specifies the <<vol1_spec_sdpi_p_actor_discovery_proxy>> Web Service interface.

.Discovery Proxy WSDL outline
[source#vol2_clause_appendix_a_mdpws_wsdl,xml]
----
include::../../../sources/discovery-proxy/DiscoveryProxy.wsdl[]
----
