//reset|+1|off
[#vol2_clause_dev_25,sdpi_offset=25]
[role=transaction,transaction-id=DEV-25]
=== Discover BICEPS Services [DEV-25]

==== Scope
[sdpi_transaction#transaction-dev-25,actors='actor-somds-provider actor-somds-consumer',figure=vol2-figure-dev-25-sequence,messages='message-discover-biceps-services']

include::tf2-dev-25-summary.adoc[]

==== Actor Roles

[sdpi_transaction_actors]
--

[actor-id="somds_consumer",contribution=Initiator]
Asks for the resource representation of the <<vol1_spec_sdpi_p_actor_somds_provider>> via the <<vol2_clause_dev_25_message_get_metadata, GetMetadata>> message.

[actor-id="somds_provider",contribution=Responder]
Sends its resource representation to the <<vol1_spec_sdpi_p_actor_somds_consumer>> via the <<vol2_clause_dev_25_message_get_metadata_response, GetMetadataResponse>> message.

--


==== Referenced Standards

* <<ref_ieee_11073_10207_2017>> Section 9 Discovery Model
* <<ref_ieee_11073_10207_2017>> Section 7.3 Service Model

==== Messages
.Message Interaction Diagram [DEV-25]
[plantuml#vol2_figure_dev_25_sequence, target=puml-dev-25-sequence, format=svg]

....
include::../../plantuml/vol2-figure-dev-25-sequence.puml[]
....

[#vol2_clause_dev_25_message_get_metadata]
===== GetMetadata Message
The GetMetadata message is used by a <<vol1_spec_sdpi_p_actor_somds_consumer>> to request the resource representation data of a <<vol1_spec_sdpi_p_actor_somds_provider>>.

====== Trigger Events
This message is sent when a <<vol1_spec_sdpi_p_actor_somds_consumer>> has discovered a <<term_transport_address>> for a <<vol1_spec_sdpi_p_actor_somds_provider>>.

====== Expected Actions
When a <<vol1_spec_sdpi_p_actor_somds_consumer>> sends this message, the <<vol2_clause_dev_25_message_get_metadata_response, GetMetadataResponse>> message is expected as a response.

[#vol2_clause_dev_25_message_get_metadata_response]
===== GetMetadataResponse Message
The GetMetadataResponse message is sent in response to an incoming <<vol2_clause_dev_25_message_get_metadata, GetMetadata>> message.

====== Trigger Events
The GetMetadataResponse message is sent whenever a <<vol1_spec_sdpi_p_actor_somds_provider>> receives a <<vol2_clause_dev_25_message_get_metadata, GetMetadata>> message.

====== Message Semantics
[[payload_dev_25_get_metadata_biceps_services]]BICEPS Services:: Collection of BICEPS services the <<vol1_spec_sdpi_p_actor_somds_provider>> offers, including but not limited to one or multiple of the following BICEPS services (<<ref_ieee_11073_10207_2017>> Section 7.3 Service Model):
* GET SERVICE (mandatory)
* SET SERVICE
* DESCRIPTION EVENT SERVICE
* STATE EVENT SERVICE
* CONTEXT SERVICE
* WAVEFORM SERVICE

NOTE: There is currently no mandatory support for provision of the LOCALIZATION SERVICE, CONTAINMENT TREE SERVICE and ARCHIVE SERVICE.

[#message_semantics_discover_biceps_services_device]
Device Metadata:: Expresses <<vol1_spec_sdpi_p_actor_somds_provider>> characteristics that typically vary from one <<vol1_spec_sdpi_p_actor_somds_provider>> to another of the same kind, for example:
* Friendly name
* Firmware version
* Serial number
[#message_semantics_discover_biceps_services_model]
Model Metadata:: Expresses <<vol1_spec_sdpi_p_actor_somds_provider>> characteristics that are typically fixed across all <<vol1_spec_sdpi_p_actor_somds_provider>>s of the same model by their <<term_manufacturer>>, for example:
* <<term_manufacturer>>
* Model name
* Model number

====== Expected Actions
When a <<vol1_spec_sdpi_p_actor_somds_provider>> sends this message, there is no expected or required response.

// todo: this ID is a duplicate of the one defined in tf2-dev-23.adoc; it needs its own ID. 
// [#vol2_clause_dev_23_message_announce_network_presence_ses]
include::../dev-x-default-ses-secured-mode.adoc[]

