:var_transaction_id: DEV-32

:var_label_dev_32_message_notification: Change Sequence Report


//reset|+1|off
[#vol2_clause_dev_32,sdpi_offset=32]
[role=transaction,transaction-id=DEV-32]
=== Retrieve Archive Data [{var_transaction_id}]

==== Scope

include::tf2-dev-32-summary.adoc[]

==== Actor Roles

[sdpi_transaction_actors]
--

[actor-id="somds_consumer",contribution=Initiator]
Once subscribed, listens for messages to retrieve historic <<acronym_mdib>> data.

[actor-id="somds_provider",contribution=Responder]
While a subscription is running, the <<vol1_spec_sdpi_p_actor_somds_provider>> delivers messages that reflect historic <<acronym_mdib>> data.

--

==== Referenced Standards

* <<ref_ieee_11073_10207_2017>> Section 7.4 Message Model

==== Messages

.Message Interaction Diagram [{var_transaction_id}]
[plantuml#vol2_figure_dev_32_sequence, target=puml-dev-32-sequence, format=svg]
....
include::../../plantuml/vol2-figure-dev-32-sequence.puml[]
....

[#vol2_clause_dev_32_message_subscribe]
===== Subscribe Message

The Subscribe message used to establish a historic <<acronym_mdib>> data stream.

[#vol2_clause_dev_32_message_subscribe_trigger_events]
====== Trigger Events

The Subscribe message is sent whenever a <<vol1_spec_sdpi_p_actor_somds_consumer>> wants to access historic <<acronym_mdib>> data.

[#vol2_clause_dev_32_message_subscribe_semantics]
====== Message Semantics

[[payload_dev_32_filter]]Filter:: A generic filter expression defined by other means.

[#vol2_clause_dev_32_message_subscribe_expected_actions]
====== Expected Actions

This message is part of a subscription establishment process as described in <<vol2_clause_dev_27>>. Once the subscription is running, the <<vol1_spec_sdpi_p_actor_somds_provider>> sends <<vol2_clause_dev_32_message_notification, Change Sequence Report>> messages.

// ---------- Notification ---------

[#vol2_clause_dev_32_message_notification]
===== {var_label_dev_32_message_notification} Message

The {var_label_dev_32_message_notification} messages contain historic <<acronym_mdib>> data and are delivered in a 1:1 relationship by a <<vol1_spec_sdpi_p_actor_somds_provider>> to a <<vol1_spec_sdpi_p_actor_somds_consumer>>.

[#vol2_clause_dev_32_message_notification_trigger_events]
====== Trigger Events

{var_label_dev_32_message_notification} messages are sent for as long as there is requested historic <<acronym_mdib>> data left to be transmitted to the subscribed <<vol1_spec_sdpi_p_actor_somds_consumer>> based on filter criteria specified by <<payload_dev_32_filter>>.

[#vol2_clause_dev_32_message_notification_semantics]
====== Message Semantics

[[payload_dev_32_notification_changesequencereport]]ChangeSequenceReport:: A report that contains historic <<acronym_mdib>> data.

[#vol2_clause_dev_32_message_notification_expected_actions]
====== Expected Actions

When a <<vol1_spec_sdpi_p_actor_somds_provider>> sends this message, there is no expected action or required responses.

[#vol2_clause_dev_32_publish_biceps_update_reports_ses]
include::../dev-x-default-ses-secured-mode.adoc[]

==== Additional Requirements

.R0529
[sdpi_requirement#r0529,sdpi_req_level=shall,sdpi_req_type=tech_feature]
****
[NORMATIVE]
====
If a <<vol1_spec_sdpi_p_actor_somds_provider>> provides the <<term_history_service>>, the <<vol1_spec_sdpi_p_actor_somds_provider>> shall provide message counting of <<term_history_service>> change sequence reports to <<vol1_spec_sdpi_p_actor_somds_consumer>>s.
====

NOTE: This is a binding requirement that needs to be satisfied by a particular implementation requirement.

****