
[#standard_clause_foreword,sdpi_offset=clear]
= Foreword

== HL7-IHE Gemini Device Interoperability Program

Recognizing the decades-long close collaboration between between Health Level Seven International (HL7) and Integrating the Healthcare Enterprise (IHE), and in order to better facilitate coordinated development, the Gemini Program was created as a home for joint projects.
This Gemini standard is one such joint development project between the HL7 and IHE Devices working groups focused on acute care, plug-and-trust medical device interoperability.
Its development and publication adheres to the consensus standards processes of both HL7, an ANSI accredited standards development organization, and IHE.
The title of this document, *_Technical Framework Profile Standard_*, reflects its unique status as a Gemini specification, utilizing the IHE Technical Framework organization and elements (e.g., integration profiles, actors, transactions, content modules), but processed as an HL7 specification that will be published as a "standalone" standard and will persist even when its status transitions to normative standard (HL7) or Final Text (IHE).

To facilitate integration with the companion IHE Devices Technical Framework (final text) specification, a companion to this standard is created for each edition:  "IHE Devices Technical Framework _Supplement_ -- Service-oriented Device Point-of-care Interoperability (SDPi)", which will be organized and adhere to IHE style guidelines for supplement documents, but it will be in major section outline only, with each section including a note indicating where the content is located in the published *Gemini Technical Framework Profile _Standard_* (this document).
Given its alignment with the companion IHE specification, some section numbers are skipped in this document to facilitate its intended integration into the above-mentioned "standard".
Skipped section numbers are already present in the Devices Technical Framework and will not require changes due to the incorporation of the supplement once it transitions to normative standard / final text status.

Additionally, some content that may otherwise be only referenced by a "supplement" document and defined elsewhere in the existing technical framework, will be incorporated in this specification to ensure that it is internally cohesive and does not force the reader to unnecessarily consult other documents.

Publication as a *Standard for Trial Use* (HL7 STU) or *Trial Implementation* (IHE TI) reflects the continuous cycle of development, balloting and publication of the specification, to address addition of new capabilities as well as identified safety, effectiveness and security issues and enhancements.
Product developers are encouraged to use the standard, recognizing the potential impact of this continuous development cycle and its status as a _"trial use"_ standard.


This supplement is published on {gemini_standard_sdpi_publication_month} for Trial Implementation and may be available for testing at subsequent IHE or HL7 testing events, such as an IHE Connectathon.
The standard may be amended based on the results of testing.
Following successful testing and implementation maturity, it will transition to a normative standard, and the companion IHE supplement will be incorporated into the Devices Technical Framework.
Comments are invited and can be submitted at https://www.ihe.net/DEV_Public_Comments/[Devices Public Comments] or by submitting a https://github.com/IHE/DEV.SDPi/issues/new/choose[GitHub Issue].

General information about IHE can be found at http://www.ihe.net/[IHE.net], and about HL7 can be found at https://www.hl7.org/index.cfm[HL7.org].

General information about the HL7 Devices Working Group can be found at https://www.hl7.org/Special/committees/healthcaredevices/index.cfm[HL7.org/healthcaredevices], and the IHE Devices domain can be found at https://www.ihe.net/ihe_domains/[IHE Domains].

Information about the organization of IHE Technical Frameworks and Supplements and the process used to create them can be found at https://www.ihe.net/resources/profiles/[Profiles] and https://www.ihe.net/about_ihe/ihe_process/[IHE Processes].

The current version of the IHE Devices Technical Framework can be found at https://profiles.ihe.net/DEV/[DEV Technical Framework].

== Gemini Technical Framework Profile Standard
[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{standard_note}*:  This section will define this new type of standard:
. Gemini - Joint effort between HL7 and IHE
. Technical Framework - Specifying content per the IHE TF constructs (actors, transactions, content modules, volumes, etc.)
. Profile - Includes both functionality-focused "integration profile" specifications, as well as normative referenced standard profiling (content selection and constraint)
. Standard - a consensus standard that is developed in accordance with an accredited standards development process (e.g., ANSI accredited) and is on a track to become an international standard (e.g., via liaison from HL7 to ISO/TC 215 Health informatics).
|===

== General Technical Framework Organization
[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{standard_note}*:  This section will explain the general organization and clauses used in this standard, and the scope / rationale behind each.
|===

== Use of AsciiDoc
[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{standard_note}*:  Explaination and rationale behind the use of AsciiDoc for capturing the content of this standard.
This will include other options that were considered, as well as the unique emergence in this document (e.g., during the pandemic) and the position it plays sitting between work from many other standards organizations that has been evolving over decades.
|===

include::standard-issues.adoc[]

