


[#clause_overview,sdpi_offset=clear]
= Standard Overview

[#clause_sdpi_standard_scope]
== Scope

NOTE: #content from current TF-1:2.3.1.1 SDPi Profiles – Scope of Application#

[#clause_sdpi_standard_purpose]
== Purpose

NOTE: #content from current TF-1:2.3.1.1 and similar#


[#clause_sdpi_standard_copyright_licenses_trademarks]
== Copyright Licenses & Trademarks


include::copyrights.adoc[]

// SDPi Trademark

=== Trademark

NOTE: #Should this also include HL7 here?  Other TM's that are in the IHE TF-0 but not in this standalone document#

IHE^®^ and the IHE logo are trademarks of the Healthcare Information Management Systems Society in the United States and trademarks of IHE Europe in the European Community.
Please refer to the IHE Technical Frameworks General Introduction, https://profiles.ihe.net/GeneralIntro/ch-10.html[Section 10 - Trademark] for information on their use.

[#clause_sdpi_xml_namespaces]
== XML Namespaces

The XML namespace URI that is used by this specification is: `urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.1.1`.

<<table_xml_namespaces>> lists XML namespaces and prefixes that are used in this specification.
The choice of any namespace prefix is arbitrary and not semantically significant.

.Prefixes and XML namespaces used in this specification.
[#table_xml_namespaces,cols="1,5,2",width=100%,]
|===
|Prefix |XML Namespace |Specification

|sdpi
|urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.1.1
|This specification, used by <<acronym_biceps>> extensions.

|dp
|urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.2.2
|This specification, used by the <<vol1_spec_sdpi_p_actor_discovery_proxy>> actor.

|dpws
|http://docs.oasis-open.org/ws-dd/ns/dpws/2009/01
|<<ref_oasis_dpws_2009>>

|hs
|urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.3.1
|This specification, used by service specification of the <<term_history_service>>.

|hm
|urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.3.2
|This specification, used by model specification of the <<term_history_service>>.

|wsa
|http://www.w3.org/2005/08/addressing
|<<ref_oasis_ws_addressing_2006>>

|wsd
|http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01
|<<ref_oasis_ws_discovery_2009>>

|wse
|http://schemas.xmlsoap.org/ws/2004/08/eventing
|<<ref_w3c_ws_eventing_2006>>

|wsm
|http://schemas.xmlsoap.org/ws/2004/09/mex
|<<ref_w3c_ws_metadata_exchange_2008>>

|===


// Forward declarations of common labels & acronyms & variables
include::document-declarations.adoc[]

// Define oids for referenced standards
include::oid-definitions.adoc[]

[#clause_sdpi_standard_overview,sdpi_offset=clear]
= SDPi Profiles Overview

NOTE: #This secton integrates content previously in multiple locations in the standard, and as a result, there are duplications and inconsistencies in the "flow" of content.  This will be addressed as the "standalone" work is completed.#

[#standard_clause_sdpi_organization,sdpi_offset=clear]
== SDPi Organization

This IHE Devices Technical Framework standard introduces a new _family of interoperability profiles_, Service-oriented Device Point-of-care Interoperability (SDPi), that comprise four separate profiles:

* SDPi-Plug-and-trust (*SDPi-P*) Profile
* SDPi-Reporting (*SDPi-R*) Profile
* SDPi-Alerting (*SDPi-A*) Profile
* SDPi-external Control (*SDPi-xC*) Profile

To that end, the standard includes updates to all three IHE DEV TF volumes, including:

*TF-1  Profiles*

* General overview of the SDPi architectural approach and integrated set of profiles
* Profile-specific sections
* Related appendices, for example the integration of this family of SDPi Profiles with other sources of requirements - use cases or reference standards

*TF-2  Transactions*

* Extensive new set of transactions based on IEEE 11073 Service-oriented Device Connectivity (SDC) medical device interoperability standards.
* Related appendices, for example the specialized use of web services messaging for device communication and gateways to other protocols or profiles

*TF-3  Content Modules*

* New content covering the application of IEEE 11073 SDC semantic standards to device content modules, with a primary focus on specifications related to the IEEE 11073-10207 BICEPS standard.

NOTE: As explained in the https://profiles.ihe.net/GeneralIntro/ch-7.html#7.5[IHE Technical Framework Document Conventions], the acronym TF stands for Technical Framework, whereas the number immediately behind the hyphen in the "TF-X" notation stands for the volume number within a Technical Framework.

[#standard_clause_mapping_clinical_scenarios_to_profile_requirements]
=== Use Cases:  Mapping Clinical Scenarios to Profile Requirements
IHE technical framework integration profile specifications include use case sections to ensure that the technical solutions are rooted in real-world application requirements.
These sections typically include a basic description of use case scenarios, identify the key systems that exchange information, application-level detail of the information exchanged, and perhaps even some sequence diagrams.
This information may also be used to drive the test cases that are used for conformity assessment, ensuring that the resulting specification implementation meets the intended needs.

This standard includes this same organization; however, it also defines a set of general, non-profile-specific clinical use cases that provide requirements, which may be mapped to multiple SDPi integration profiles.
Section <<vol1_appendix_c_dpi_use_cases>> provides a collection of these high-level clinical use cases.

FOR READERS OF THIS STANDARD, a good strategy might be to first review the use cases in the Volume 1 appendix (e.g., <<vol1_clause_appendix_c_use_case_sicdmp>> ), and then review the specific profiles to which the clinical scenario requirements have been mapped.
Reviewing the use case specifications in this order will provide the needed context to understand what is presented in each profile.

[#standard_clause_joint_ihe_hl7_gemini_ses_mdi_project_development]
=== Joint IHE-HL7 Gemini SES+MDI Project Development
This standard is the result of a joint https://confluence.hl7.org/x/Xzf9Aw[IHE-HL7 Gemini Device Interoperability program] which began early 2020.
Extensive notes and discussion materials are provided on the project's HL7 Confluence site, including a https://confluence.hl7.org/pages/viewpage.action?pageId=113674346#LibrarywithEVERYTHINGyoueverwantedtoknow...-GeneralUpdate&BriefingPresentations[Library with extensive presentations and other materials].
This Library also includes *_briefings (slides and recordings) to provide background for those reviewing the specification_*.

The joint IHE-HL7 devices team leveraged tools from both organizations, as well as participated jointly throughout the project's multi-year efforts.

The methods currently employed are provided in the wiki article:  https://github.com/IHE/DEV.SDPi/wiki/Program-Coordination-Co-Working-Spaces#program-coordination--co-working-spaces[Program Coordination & Co-Working Spaces].

[#standard_clause_support_for_ri_mc_rr_using_asciidoc]
=== Support for RI+MC+RR using AsciiDoc
In addition to the standard's technical specification content, a development approach has been advanced that represents added value to adopters and implementers over the traditional document oriented approach.
These are referred to as:

[none]
. *_Requirements Interoperability + Model Centric + Regulatory Ready_*

Or *RI+MC+RR* for short.

These three objectives may be summarized as follows:

[none]
* *Requirements Interoperability (RI)*
[none]
** Ability to integrate and automate requirements and capabilities from component specifications and standards to enable traceability and coverage at <<term_conformity_assessment>> (<<acronym_ca>>) of the component product interface
* *Model Centric (MC)*
[none]
** Transition from a document-centric to a _computable model-based "single source of truth"_ specification from which the Technical Framework becomes a view of the model
* *Regulatory Ready (RR)*
[none]
** Enable CA test reports that are genuinely _"regulatory submission ready"_ (e.g., inclusion in a U.S. FDA 510(k) submission package)

The SDPi {gemini_standard_sdpi_revision} version of the standard continues to make small but significant steps toward support of these objectives, especially Requirements Interoperability, as well as the use of AsciiDoc metadata to annotate the document sources for post-processing.
Clearly, moving toward <<term_model_centric>> specifications and full integration of <<term_model_based_systems_engineering>> will take considerable effort and time; however, this standard represents a humble start in that direction.
Subsequent standard versions will build upon these objectives and support a new level of rigor for connectathon and product conformity assessment testing and ultimately test reports that directly impact the challenges around medical product regulatory submissions.

Additional discussion is provided in <<vol1_appendix_a_requirements_management_for_p_n_t_interperability>>, and on the https://confluence.hl7.org/pages/viewpage.action?pageId=82906664#ConformityAssessment&Tooling-RI+MC+RRforMedTechSpecificationsInitiative[Gemini project's Confluence pages].
See also related discussions on the Gemini Project's https://confluence.hl7.org/x/XhPUB[Pathway to an Ecosystem of Plug-and-Trust Products].


include::profiles-detailed-overview.adoc[]


[#clause_sdpi_actors_summary]
== SDPi Actors Summary

include::summary-actors.adoc[]

[#clause_sdpi_transactions_summary]
== SDPi Transactions Summary

include::summary-transactions.adoc[]

