:uri_sdc_port_type: http://standards.ieee.org/downloads/11073/11073-20701-2018
:uri_sdc_wsdl: https://standards.ieee.org/wp-content/uploads/import/download/11073-20701-2018_downloads.zip

MDPWS is based on DPWS which in turn leverages a profiled SOAP-based Web Services protocol stack to establish a service-oriented system of devices (<<acronym_somds>>).

.R0500
[sdpi_requirement#r0500,sdpi_req_level=shall]
****
A <<actor_somds_provider>> shall at least provide the port types as specified in <<vol2_table_appendix_mdpws_service_mapping_port_types>>.

.Notes
[%collapsible]
====
NOTE: According to <<acronym_biceps>>, the GET SERVICE is the only mandatory service to be implemented. This specification extends the list of mandatory services to increase interoperability between <<actor_somds_participant>>s.
NOTE: All port types of SDC are {uri_sdc_wsdl}[available for download].

NOTE: Other port types are currently out of scope of this specification and may be added in a future revision.
====
****

.Minimum required port types
[#vol2_table_appendix_mdpws_service_mapping_port_types,cols="3,1"]
|===
|Port Type (as <<term_q_name>>) |BICEPS service <<ref_ieee_11073_10207_2017>>

|{{uri_sdc_port_type}}GetService
|GET SERVICE

|{{uri_sdc_port_type}}DescriptionEventService
|DESCRIPTION EVENT SERVICE

|{{uri_sdc_port_type}}StateEventService
|STATE EVENT SERVICE

|{{uri_sdc_port_type}}ContextService
|CONTEXT SERVICE

|{{uri_sdc_port_type}}WaveformService
|WAVEFORM SERVICE

|===

.R0501
[sdpi_requirement#r0501,sdpi_req_level=should]
****
A <<actor_somds_consumer>> should not request context states by using the `GetContextStatesByIdentification` and `GetContextStatesByFilter` operations of the {{uri_sdc_port_type}}ContextService port type.

.Notes
[%collapsible]
====
NOTE: `GetContextStatesByIdentification` and `GetContextStatesByFilter` are insufficiently defined in <<ref_ieee_11073_10207_2017>> and are likely to be obsoleted in a future revision of the specification.

NOTE: A <<actor_somds_consumer>> may retrieve context states by using `GetContextStates` and perform filtering by itself.
====
****
