// = Service-oriented Device Point-of-care Interoperability – external Control (SDPi-xC) Profile

[#vol1_clause_sdpi_xc_profile,sdpi_offset=13,role=profile,profile-id=sdpi-xc,reftext="External Control Profile",oid-arcs=.14]
== Service-oriented Device Point-of-care Interoperability – external Control (SDPi-xC) Profile

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*: This SDPi-xC (External Control) Profile Section is generally out-of-scope for this version of the profile (see https://github.com/orgs/IHE/projects/6/views/1["Gemini SDPi Releases" Github project]); however, it is provided here to indicate the intended direction of the SDPi Profiles, with details being added in subsequent versions. Depending on capabilities, some very basic controls may need to be provided as part of the 2.X or 3.X versions, especially around external adjustment of settings (e.g., alert limits or to trigger a blood-pressure reading).

|===

[#vol1_clause_sdpi_xc_profile_reftext,reftext="SDPi-xC Profile"]
The SDPi-External Control ([[acronym_sdpi_xc,SDPi-xC]] SDPi-xC) Profile enables external or "remote" control of one device by another, both being in the same secure environment (<<term_medical_device_lan>>).
This may be as simple as adjust an alarm limit or triggering a blood pressure cuff reading, to adjusting a respiration rate on a ventilator or titrating a drug dose rate on an infusion pump.
Specializes services and semantics are provided to enable safe and secure control invocation.

[#vol1_clause_sdpi_xc_actors_transactions_content_modules]
=== SDPi-xC Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this specification.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

<<vol1_figure_sdpi_xc_actor_diagram>> shows the actors directly involved in the SDPi-xC profile.
The relevant transactions between them are detailed in the subsequent <<vol1_table_sdpi_xc_actors_transactions>>.
actor groupings, including abstract with concrete, are detailed in <<vol1_clause_sdpi_xc_required_actor_groupings>>.

[#vol1_figure_sdpi_xc_actor_diagram]
.SDPi-xC Actor Diagram

image::../images/vol1-diagram-sdpi-xc-actor.svg[]

// Deferred transactions. 
sdpi_include_transaction::DEV-44[actor-id="somds_medical_control_provider",responder="required",placeholder-name="Manage medical external control"]
sdpi_include_transaction::DEV-45[actor-id="somds_medical_control_provider",responder="required",placeholder-name="Invoke medical control services"]

sdpi_include_transaction::DEV-44[actor-id="somds_medical_control_consumer",initiator="required",placeholder-name="Manage medical external control"]
sdpi_include_transaction::DEV-45[actor-id="somds_medical_control_consumer",initiator="required",placeholder-name="Invoke medical control services"]

.SDPi-xC Profile - Actors and Transactions
[#vol1_table_sdpi_xc_actors_transactions]
sdpi_transaction_table::[profile-id="sdpi-xc"]

NOTE: see <<vol1_clause_sdpi_xc_required_actor_groupings>> for actor inheritance and grouping.

// Old (manual) version:
// include:actor-tables/sdpi-xc-transactions.adoc[]

[#vol1_clause_sdpi_xd_actor_descriptions_actor_profile_requirements]
==== Actor Descriptions and Actor Profile Requirements

SDPi-xC actor roles and responsibilities are described in the subsections below.

Unless otherwise specified below, individual transaction requirements are specified in TF-2   <<vol2_clause_transactions>>, and requirements related to content modules are detailed in TF-3 <<vol3_clause_content_modules>>.
This section documents any additional requirements on the profile’s content actors.

////
TODO:
    - Consider adding more descriptive content to this sequence diagram, especially the intersection of this profile and SDPi-P (adding transactions from the start of the conversation + SDPi-P actors;
    - Add a gateway sequence diagram here or below in the gateway actor
////

<<vol1_figure_sdpi_xc_example_sequence_diagram>> illustrates a typical (not comprehensive) exchange scenario between SDPi-xC actors:

[#vol1_figure_sdpi_xc_example_sequence_diagram]
.SDPi-xC Example Sequence Diagram

[plantuml, target=puml-sdpi-xc-example-sequence-diagram, format=svg]
....
include::../plantuml/vol1-figure-sdpi-xc-example-sequence-diagram.puml[]
....

[#vol1_clause_sdpi_xc_somds_medical_control_provider,role="actor actor-alias",actor-id="somds_medical_control_provider",oid-arcs=.37]
===== SOMDS Medical Control Provider
[#vol1_spec_sdpi_xc_actor_somds_medical_control_provider, reftext='SOMDS Medical Control Provider',role="actor-alias",actor-id="somds_medical_control_provider"]
Actor Summary Definition:
[none]
. A <<vol1_spec_sdpi_p_actor_somds_provider>> grouped actor that provides operational control services to a <<vol1_spec_sdpi_xc_actor_somds_medical_control_consumer>>.

This actor is designed to publish medical device operational control services to a <<vol1_spec_sdpi_xc_actor_somds_medical_control_consumer>>, which in turn can invoke the services and remotely manage the device, safely and securely.
Transactions enabled for this actor are identified in <<vol1_table_sdpi_xc_actors_transactions>> above.

Given this _intended medical purpose_, the actor will fully address applicable requirements from the core <<acronym_sdc>> standards (<<ref_ieee_11073_10207_2017>> and <<ref_ieee_11073_20701_2018>>), as well as the <<acronym_pkp>> standards <<ref_ieee_11073_10700_2022>> and <<ref_ieee_11073_10703_202x>> (Control <<acronym_pkp>>).

Every <<vol1_spec_sdpi_xc_actor_somds_medical_control_provider>> is grouped with an <<vol1_spec_sdpi_p_actor_somds_provider>> to enable <<acronym_somds>>-based connectivity.
This actor inherits all the capabilities of the paired <<vol1_spec_sdpi_p_actor_somds_consumer>>.
Note that optional capabilities for this specification, as specified in <<vol1_clause_sdpi_a_actor_options>>, may also result in additional requirements for the underlying <<vol1_spec_sdpi_p_actor_somds_consumer>> and <<vol1_clause_sdpi_p_profile_reftext>>.

[#vol1_clause_sdpi_xc_somds_medical_control_consumer,role="actor actor-alias",actor-id="somds_medical_control_consumer",oid-arcs=.38]
===== SOMDS Medical Control Consumer
[#vol1_spec_sdpi_xc_actor_somds_medical_control_consumer, reftext='SOMDS Medical Control Consumer',role="actor-alias",actor-id="somds_medical_control_consumer"]
Actor Summary Definition:
[none]
. A <<vol1_spec_sdpi_p_actor_somds_consumer>> grouped actor that invokes operational control services on a <<vol1_spec_sdpi_xc_actor_somds_medical_control_provider>>.

This actor is designed to invoke and manage medical device control operations, safely, effectively and securely.
Transactions enabled for this actor are identified in <<vol1_table_sdpi_xc_actors_transactions>> above.

Given this _intended medical purpose_, the actor will fully address applicable requirements from the core <<acronym_sdc>> standards (<<ref_ieee_11073_10207_2017>> and <<ref_ieee_11073_20701_2018>>), as well as the <<acronym_pkp>> standards <<ref_ieee_11073_10700_2022>> and <<ref_ieee_11073_10703_202x>> (Control <<acronym_pkp>>).

Every <<vol1_spec_sdpi_xc_actor_somds_medical_control_consumer>> is grouped with an <<vol1_spec_sdpi_p_actor_somds_consumer>> to enable <<acronym_somds>>-based connectivity.
This actor inherits all the capabilities of the paired <<vol1_spec_sdpi_p_actor_somds_consumer>>.
Note that optional capabilities for this specification, as specified in <<vol1_clause_sdpi_a_actor_options>>, may also result in additional requirements for the underlying <<vol1_spec_sdpi_p_actor_somds_consumer>> and <<vol1_clause_sdpi_p_profile_reftext>>.

[#vol1_clause_sdpi_xc_actor_options]
=== SDPi-xC Actor Options
No options are specified for this specification.

[#vol1_clause_sdpi_xc_required_actor_groupings]
=== SDPi-xC Required Actor Groupings
[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*:  As indicated in <<vol1_figure_sdpi_xc_actor_diagram>> above, there are two grouped actors:

[none]
. <<vol1_spec_sdpi_xc_actor_somds_medical_control_consumer>> with <<vol1_spec_sdpi_p_actor_somds_consumer>>
. <<vol1_spec_sdpi_xc_actor_somds_medical_control_provider>> with <<vol1_spec_sdpi_p_actor_somds_provider>>

This section will be more completely detailed in a future version of the supplement.

|===

=== SDPi-xC Overview

==== Concepts

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*:  An overview of the concepts for this <<vol1_clause_sdpi_a_profile_reftext>> will be provided in a future supplement version.
Note that this specification extends the concepts established in the base <<vol1_clause_sdpi_p_profile_reftext>>.
|===

[#vol1_clause_sdpi_xc_use_cases_reftext, reftext='SDPi-xC Use Cases']
==== Use Cases

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*:  No use cases have been included that provide functional requirements for device external control.  These will be added to a future version of the SDPi supplement.
Therefore, with this release of the SDPi specification, this section remains incomplete.
|===

////
#TODO:  Migrate additional content from the old Word version to this section
////

[#vol1_clause_sdpi_xc_ses_considerations]
=== SDPi-xC Safety, Effectiveness and Security - Requirements and Considerations

==== SES General Considerations
Requirements from the <<ref_iso_81001_1_2021>>, <<ref_iec_80001_1_2021>>, and related standards should be fully applied to this technical framework element.

For additional guidance, see Section <<vol1_clause_appendix_a_ses_considerations_and_requirements>>.

==== Safety Requirements & Considerations
No additional safety requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ Section above.

==== Effectiveness Requirements & Considerations
No additional effectiveness requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ Section above.

==== Security Requirements & Considerations
No additional security requirements and considerations are identified for this technical framework element beyond those provided by the  SDPi-P Profile (see <<vol1_clause_appendix_a_ses_considerations_section_template>>), and those specified in the _<<acronym_ses>> General Considerations_ Section above.

Note that capability '_external or "remote" control of one device by another_' enabled by this SDPi-xC Profile refers to "external" to the device that is controlled, while both devices are in the same secure environment (<<term_medical_device_lan>>).

=== SDPi-xC Cross Profile Considerations
No additional cross profile considerations have been identified.

////
#TODO:  See the template instructions + PCD 2019 and other TF's to see if any content should go in this section for SDPi-xC.#
////

