// = Service-oriented Device Point-of-care Interoperability - Alerting (SDPi-A) Profile

[#vol1_clause_sdpi_a_profile,sdpi_offset=12,role=profile,profile-id=sdpi-a,reftext="Alerting Profile",oid-arcs=.13]
== Service-oriented Device Point-of-care Interoperability – Alerting (SDPi-A) Profile

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*:  This initial version of the <<acronym_sdpi_a>> Profile is built upon the foundational <<acronym_sdpi_p>> Profile but adds services specialized for the communication and management of medical device alerting.
Additionally, since the primary purpose of this specification is the communication of medical alert information to accomplish intended medical purposes, it will require the completion and integration of the emerging ISO/IEEE 11073 Alert <<acronym_pkp>> standard  <<ref_ieee_11073_10702_202x>>.
When this new standard is published, its requirements will be integrated into this supplement, with its <<term_implementation_conformance_statement>> added to <<vol1_appendix_b_referenced_standards_conformance>>.
Many of those requirements will be mapped to the actors, transactions and other specifications in this specification.

Two of the transactions identified below, [DEV-41] and [DEV-42] are related to Medical Alert Delegation; however, at this stage there is considerable standards development activity to update the current <<acronym_sdc>> standards, particularly in association with completing the Alert <<acronym_pkp>> standard  <<ref_ieee_11073_10702_202x>>.
As a result, the completion of these two transactions has been deferred to a subsequent version of the supplement.

Similarly, a related transaction, [DEV-43], namely providing clinician alert acknowledgement status information back to the alerting device, is also being discussed further and will be deferred to a subsequent version of the supplement.

Finally, it should be noted that  <<actor_somds_acm_gateway>> is defined below and fully specified in <<vol2_clause_appendix_sdpi_acm_gateway>>.
Also in development is <<acronym_hl7>> <<acronym_fhir>> support for medical alerting (e.g., refinement of the <<acronym_fhir>> DeviceAlert resource and future development of a <<acronym_fhir>> Device Alerting IG).
As a result, a "SOMDS Medical Alert FHIR Gateway" is not included as an actor at this stage; however, it is expected to be added in the coming year or two.

|===

[#vol1_clause_sdpi_a_profile_reftext,reftext="SDPi-A Profile"]
The SDPi-Alerting ([[acronym_sdpi_a,SDPi-A]] SDPi-A) Profile supports the communication of alert information from one <<term_service_oriented_medical_device_system>> to other <<acronym_somds>> systems or to other external non-<<acronym_somds>> systems utilizing a <<label_system_type_name_agw>>.
The actors and transactions in this specification are specialized versions of their counterparts in the <<vol1_clause_sdpi_p_profile_reftext>>; however, are differentiated in that they are specifically designed to communicate alert information to fulfill an _intended medical purpose_, primarily to notify a clinician of a patient or device-related condition that requires their attention.
Additional services have been provided to specifically support the exchange and management of this medical device alert information, providing a high-level of reliability and performance, commensurate with the potential risk to the patient if they are not promptly addressed.

The profile builds upon the foundational <<term_plug_and_trust>> capabilities provided by the <<vol1_clause_sdpi_p_profile_reftext>>.
These extended capabilities for medical data exchange are achieved by various means, including:

. Grouping <<acronym_sdpi_a>> actors with their <<acronym_sdpi_p>> counterparts
. Addressing requirements from the emerging <<acronym_pkp>> ISO/IEEE standards:  <<ref_ieee_11073_10700_2022>> and <<ref_ieee_11073_10701_2022>>
. Requiring capabilities that in the <<vol1_clause_sdpi_p_profile_reftext>> may be optional
. Requiring additional <<acronym_biceps>> data elements or content modules

Additional requirements to addressed safety and effectiveness requirements are provided in <<vol1_clause_sdpi_a_ses_considerations>>.

[#vol1_clause_sdpi_a_actors_transactions_content_modules]
=== SDPi-A Actors, Transactions, and Content Modules

This section defines the actors, transactions, and/or content modules in this specification.
General definitions of actors are given in the https://profiles.ihe.net/GeneralIntro/ch-A.html[_Technical Frameworks General Introduction Appendix A_].
IHE Transactions can be found in the https://profiles.ihe.net/GeneralIntro/ch-B.html[_Technical Frameworks General Introduction Appendix B_].
Both appendices are located at https://profiles.ihe.net/GeneralIntro/[_profiles.ihe.net/GeneralIntro_].

<<vol1_figure_sdpi_a_actor_diagram>> shows the actors directly involved in the SDPi-A Profile.
The relevant transactions between them are detailed in the subsequent <<vol1_table_sdpi_a_actors_transactions>>.
Actor groupings, including abstract with concrete, are detailed in <<vol1_clause_sdpi_a_required_actor_groupings>>.

[#vol1_figure_sdpi_a_actor_diagram]
.SDPi-A Actor Diagram

image::../images/vol1-diagram-sdpi-a-actor.svg[]

////

#TODO:  In the table below, are any of these Receiver vs. Responder?  If so, then we may need to add a note like in SDPi-P

#TODO: Do we need to add an option note for Alert Delegation?#

////

sdpi_include_transaction::DEV-38[actor-id="somds_medical_alert_provider",responder="required"]
sdpi_include_transaction::DEV-39[actor-id="somds_medical_alert_provider",initiator="required"]
sdpi_include_transaction::DEV-40[actor-id="somds_medical_alert_provider",responder="required"]

sdpi_include_transaction::DEV-38[actor-id="somds_medical_alert_consumer",initiator="required"]
sdpi_include_transaction::DEV-39[actor-id="somds_medical_alert_consumer",responder="required"]
sdpi_include_transaction::DEV-40[actor-id="somds_medical_alert_consumer",initiator="optional"]

sdpi_include_transaction::DEV-38[actor-id="somds_acm_gateway",responder="required"]
sdpi_include_transaction::DEV-39[actor-id="somds_acm_gateway",initiator="required"]
sdpi_include_transaction::DEV-40[actor-id="somds_acm_gateway",responder="required"]

// Deferred transactions. 
sdpi_include_transaction::DEV-41[actor-id="somds_medical_alert_provider",responder="optional",placeholder-name="Manage medical alert delegation"]
sdpi_include_transaction::DEV-42[actor-id="somds_medical_alert_provider",initiator="optional",placeholder-name="Delegate medical alert"]
sdpi_include_transaction::DEV-43[actor-id="somds_medical_alert_provider",responder="required",placeholder-name="Update alert acknowledgement status"]

sdpi_include_transaction::DEV-41[actor-id="somds_medical_alert_consumer",initiator="optional",placeholder-name="Manage medical alert delegation"]
sdpi_include_transaction::DEV-42[actor-id="somds_medical_alert_consumer",responder="optional",placeholder-name="Delegate medical alert"]
sdpi_include_transaction::DEV-43[actor-id="somds_medical_alert_consumer",initiator="required",placeholder-name="Update alert acknowledgement status"]

sdpi_include_transaction::DEV-43[actor-id="somds_acm_gateway",initiator="required",placeholder-name="Update alert acknowledgement status"]

ifdef::markup-actor-transactions-table[]

[#vol1_table_sdpi_a_actors_transactions]
.SDPi-A Profile - Actors and Transactions
sdpi_transaction_table::[profile-id="sdpi-a"]

[NOTE]
====
* Transaction is required if <<vol1_clause_sdpi_a_actor_option_alert_delegation_reftext>> is supported.

* By default, the <<vol1_spec_sdpi_a_actor_somds_acm_gateway>> acts as a <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>>, initiating [DEV-04] transactions when they are received from <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>>s.
This default configuration requires the grouped <<vol1_spec_sdpi_p_actor_somds_v2_gateway>> Actor to have the <<vol1_spec_sdpi_p_option_gateway_export>> option selected.

If the gateway supports  <<vol1_clause_sdpi_a_actor_option_remote_alert_signaling_reftext>>, then it also acts as a <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> and accepts inbound [DEV-04] transactions from ACM Alert Reporters.
In this case, the gateway will support both "Initiator & Responder" for these transactions.
In this case, the <<vol1_spec_sdpi_p_actor_somds_v2_gateway>> Actor has both the <<vol1_spec_sdpi_p_option_gateway_import>> and <<vol1_spec_sdpi_p_option_gateway_export>> options selected.
====

endif::[]

ifndef::markup-actor-transactions-table[]

// Manual actors and transactions table:
include::actor-tables/sdpi-a-transactions.adoc[]

endif::[]
 
[#vol1_clause_sdpi_a_actor_descriptions_actor_profile_requirements]
==== Actor Descriptions and Actor Profile Requirements

SDPi-A actor roles and responsibilities are described in the subsections below.

Unless otherwise specified below, individual transaction requirements are specified in TF-2   <<vol2_clause_transactions>>, and requirements related to content modules are detailed in TF-3 <<vol3_clause_content_modules>>.
This section documents any additional requirements on the profile’s content actors.

////
TODO:
    - Consider adding more descriptive content to this sequence diagram, especially the intersection of this profile and SDPi-P (adding transactions from the start of the conversation + SDPi-P actors;
    - Add a gateway sequence diagram here or below in the gateway actor
////

<<vol1_figure_sdpi_a_example_sequence_diagram>> illustrates a typical (not comprehensive) exchange scenario between SDPi-A actors:

[#vol1_figure_sdpi_a_example_sequence_diagram]
.SDPi-A Example Sequence Diagram

[plantuml, target=puml-sdpi-a-example-sequence-diagram, format=svg]
....
include::../plantuml/vol1-figure-sdpi-a-reporting-example-sequence-diagram.puml[]
....

[#vol1_clause_sdpi_a_somds_medical_alert_provider,role="actor actor-alias",actor-id="somds_medical_alert_provider",oid-arcs=.35]
[actor-grouping="somds_provider"]
===== SOMDS Medical Alert Provider
[#vol1_spec_sdpi_a_actor_somds_medical_alert_provider, reftext='SOMDS Medical Alert Provider',role="actor-alias",actor-id="somds_medical_alert_provider"]
Actor Summary Definition:
[none]
. A <<vol1_spec_sdpi_p_actor_somds_provider>> grouped actor that sends medical alert information to a <<actor_somds_medical_alert_consumer>>.

This actor is designed to publish medical device alert information to a <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>>, which in turn can communicate it safely and reliably to a clinician.
Transactions enabled for this actor are identified in <<vol1_table_sdpi_a_actors_transactions>> above.

Given this _intended medical purpose_, the actor will fully address applicable requirements from the core <<acronym_sdc>> standards (<<ref_ieee_11073_10207_2017>> and <<ref_ieee_11073_20701_2018>>), as well as the <<acronym_pkp>> standards <<ref_ieee_11073_10700_2022>> and <<ref_ieee_11073_10702_202x>> (Alert <<acronym_pkp>>).

Every <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> is grouped with an <<vol1_spec_sdpi_p_actor_somds_provider>> to enable <<acronym_somds>>-based connectivity.
This actor inherits all the capabilities of the paired <<vol1_spec_sdpi_p_actor_somds_provider>>.
Note that optional capabilities for this specification, as specified in <<vol1_clause_sdpi_a_actor_options>>, may also result in additional requirements for the underlying <<vol1_spec_sdpi_p_actor_somds_provider>> and <<vol1_clause_sdpi_p_profile_reftext>>.

Note that if a <<label_system_type_name_sas>> is being created, it may incorporate both <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> and <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> Actors, both receiving and publishing alerts.

[#vol1_clause_sdpi_a_somds_medical_alert_consumer,role="actor actor-alias",actor-id="somds_medical_alert_consumer",oid-arcs=.34]
[actor-grouping="somds_consumer"]
===== SOMDS Medical Alert Consumer
[#vol1_spec_sdpi_a_actor_somds_medical_alert_consumer, reftext='SOMDS Medical Alert Consumer',role="actor-alias",actor-id="somds_medical_alert_consumer"]
Actor Summary Definition:
[none]
. A <<vol1_spec_sdpi_p_actor_somds_consumer>> grouped actor that receives medical alert information from a <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>>.

This actor is designed to receive and manage medical device alert information to communicate it safely and reliably to a clinician.
Transactions enabled for this actor are identified in <<vol1_table_sdpi_a_actors_transactions>> above.

Given this _intended medical purpose_, the actor will fully address applicable requirements from the core <<acronym_sdc>> standards (<<ref_ieee_11073_10207_2017>> and <<ref_ieee_11073_20701_2018>>), as well as the <<acronym_pkp>> standards <<ref_ieee_11073_10700_2022>> and <<ref_ieee_11073_10702_202x>> (Alert <<acronym_pkp>>).

Every <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> is grouped with an <<vol1_spec_sdpi_p_actor_somds_consumer>> to enable <<acronym_somds>>-based connectivity.
This actor inherits all the capabilities of the paired <<vol1_spec_sdpi_p_actor_somds_consumer>>.
Note that optional capabilities for this specification, as specified in <<vol1_clause_sdpi_a_actor_options>>, may also result in additional requirements for the underlying <<vol1_spec_sdpi_p_actor_somds_consumer>> and <<vol1_clause_sdpi_p_profile_reftext>>.

Note that if a <<label_system_type_name_sas>> is being created, it may incorporate both <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> and <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> Actors, both receiving and publishing alerts.

[#vol1_clause_sdpi_a_somds_acm_gateway,role="actor actor-alias",actor-id="somds_acm_gateway",oid-arcs=.28]
[actor-grouping="somds_v2_gateway"]
===== SOMDS ACM Gateway
[#vol1_spec_sdpi_a_actor_somds_acm_gateway, reftext='SOMDS ACM Gateway',role="actor-alias",actor-id="somds_acm_gateway"]
Actor Summary Definition:
[none]
. A <<vol1_spec_sdpi_p_actor_somds_v2_gateway>> grouped actor that supports the bi-directional exchange of medical alert information with non-SOMDS systems and applications using IHE Alert Communication Management (ACM) transactions.

This is designed to exchange medical device alert information to external non-<<acronym_somds>> systems using the <<acronym_hl7>> V2-based Alert Communication Management (ACM) Profile transactions.

Every <<vol1_spec_sdpi_a_actor_somds_acm_gateway>> is grouped with an <<vol1_spec_sdpi_p_actor_somds_v2_gateway>> to enable <<acronym_somds>>-based connectivity.
This actor inherits all the capabilities of the paired <<vol1_spec_sdpi_p_actor_somds_v2_gateway>>.
Note that optional capabilities for this specification, as specified in <<vol1_clause_sdpi_a_actor_options>>, may also result in additional requirements for the underlying <<vol1_spec_sdpi_p_actor_somds_v2_gateway>> and <<vol1_clause_sdpi_p_profile_reftext>>.

Transactions enabled for this actor are identified in <<vol1_table_sdpi_a_actors_transactions>> above.

Given this _intended medical purpose_, the actor will fully address applicable requirements from the core <<acronym_sdc>> standards (<<ref_ieee_11073_10207_2017>> and <<ref_ieee_11073_20701_2018>>), as well as the <<acronym_pkp>> standards <<ref_ieee_11073_10700_2022>> and <<ref_ieee_11073_10702_202x>> (Alert <<acronym_pkp>>).

This actor shall implement the <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> capabilities, receiving alert information provided by <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> systems and publishing them as [DEV-04] / [PCD-04] Transactions to external ACM Alert Manager (AM) systems.
If <<vol1_clause_sdpi_a_actor_option_remote_alert_signaling_reftext>> is implemented, then this actor will also support the <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> capabilities, receiving [DEV-04] / [PCD-04] Transactions from external ACM Device Observation Reporter (DOR) systems and making them available to other <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> systems.
Note:  Not supported are <<vol1_spec_sdpi_a_actor_somds_acm_gateway>> systems that only implement the <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> and not <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> capabilities.

Detailed specifications for mapping from <<acronym_somds>>/<<acronym_biceps>>  to <<acronym_hl7>> V2 / ACM [DEV-04]/[PCD-04] transactions are provided in <<vol2_clause_appendix_sdpi_acm_gateway>>.

NOTE: This actor is not intended to play the role of an ACM Alert Manager.
If [DEV-04] transactions are received by the gateway, they will be simply mapped to <<acronym_somds>>/<<acronym_biceps>> semantics and provided to <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> systems.

If a <<label_system_type_name_sas>> is being created, it may incorporate both <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> and <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> Actors, both receiving and publishing alerts to external ACM-based systems.

[#vol1_clause_sdpi_a_actor_options]
=== SDPi-A Actor Options

[#vol1_clause_sdpi_a_actor_option_alert_delegation,role=profile-option,profile-option-id=alert_delegation,oid-arcs=".4"]
==== Alert Delegation Option

// Deferred transactions. 
sdpi_include_transaction::DEV-41[actor-id="somds_medical_alert_provider",responder="required",placeholder-name="Manage medical alert delegation"]
sdpi_include_transaction::DEV-42[actor-id="somds_medical_alert_provider",initiator="required",placeholder-name="Delegate medical alert"]

sdpi_include_transaction::DEV-41[actor-id="somds_medical_alert_consumer",initiator="required",placeholder-name="Manage medical alert delegation"]
sdpi_include_transaction::DEV-42[actor-id="somds_medical_alert_consumer",responder="required",placeholder-name="Delegate medical alert"]

[#vol1_clause_sdpi_a_actor_option_alert_delegation_reftext, reftext='SDPi-A Option:  Alert Delegation']
[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*:  This section is intentionally left incomplete to indicate capabilities that will be added in a future version of the SDPi Supplement.
As stated elsewhere, the completion of the <<ref_ieee_11073_10702_202x>> standard is required before this profile can be completed (beyond alert reporting for DIS capabilities), and that is especially the case for alert delegation.

*_The sequence diagram below for delegation is provided for informative purposes only and will be finalized when the IEEE standard and this profile option are completed._*

This option will enable <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> systems to safely and reliably transfer or "delegate" audible annunciation of alert conditions to another system.
This option will enable both the <<transaction_name_manage_medical_alert_delegation>> [DEV-41] and <<transaction_name_delegate_medical_alert>> [DEV-42] transactions.

|===

////
TODO:
    - Consider adding more descriptive content to this sequence diagram, especially the intersection of this profile and SDPi-P (adding transactions from the start of the conversation + SDPi-P actors;
    - Add a gateway sequence diagram here or below in the gateway actor
////

<<vol1_figure_sdpi_a_option_delegate_medical_alert_example_sequence_diagram>> illustrates a typical (not comprehensive) alert delegation scenario between SDPi-A actors:

[#vol1_figure_sdpi_a_option_delegate_medical_alert_example_sequence_diagram]
.SDPi-A Delegate Medical Alert Example Sequence Diagram

[plantuml, target=puml-sdpi-a-delegation_example-sequence-diagram, format=svg]
....
include::../plantuml/vol1-figure-sdpi-a-delegation-example-sequence-diagram.puml[]
....


[#vol1_clause_sdpi_a_actor_option_alert_user_acknowledgement,role=profile-option,profile-option-id=alert_user_acknowledgement,oid-arcs=".5"]
==== Alert User Acknowledgement Option

[#vol1_clause_sdpi_a_actor_option_alert_user_acknowledgement_reftext, reftext='SDPi-A Option:  Alert User Acknowledgement']
[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*:  This section is left intentionally blank to indicate capabilities that will be added in a future version of the SDPi Supplement.

This option will enable <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> systems to safely and reliably receive from <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> systems user (clinician) acknowledgement of previously reported alert conditions.
This option will enable the <<transaction_name_update_alert_acknowledgement_status>> [DEV-43] transaction.

|===

[#vol1_clause_sdpi_a_actor_option_remote_alert_signaling,role=profile-option,profile-option-id=remote_alert_signaling,oid-arcs=".6"]
==== Remote Alert Signaling

sdpi_include_transaction::DEV-38[actor-id="somds_acm_gateway",initiator="required"]
sdpi_include_transaction::DEV-39[actor-id="somds_acm_gateway",responder="required"]
sdpi_include_transaction::DEV-40[actor-id="somds_acm_gateway",initiator="optional"]

[#vol1_clause_sdpi_a_actor_option_remote_alert_signaling_reftext, reftext='SDPi-A Option:  Remote Alert Signaling']
[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*:  This section is left intentionally blank to indicate capabilities that will be added in a future version of the SDPi Supplement.

This option will enable <<vol1_spec_sdpi_a_actor_somds_acm_gateway>> systems to receive [DEV-04]/[PCD-04] transactions from an ACM Alert Reporter and then act as a <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> to communicate the signals to <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> systems.
This option will enable the <<vol1_spec_sdpi_a_actor_somds_acm_gateway>> to respond to <<transaction_name_establish_medical_alert_exchange>> [DEV-38] and <<transaction_name_retrieve_medical_alert_status>> [DEV-40] transactions, and to initiate <<transaction_name_publish_medical_alert_update>> [DEV-39] transactions.

|===

[#vol1_clause_sdpi_a_required_actor_groupings]
=== SDPi-A Required Actor Groupings

An actor from this profile (Column 1) shall implement all of the required transactions and/or content modules in this profile *_in addition to all_* of the requirements for the grouped actor (Column 3) in <<vol1_table_sdpi_a_required_actor_groupings>>.

If this is a content profile, and actors from this profile are grouped with actors from a workflow or transport profile, the Reference column references any specifications for mapping data from the content module into data elements from the workflow or transport transactions.

<<vol1_clause_sdpi_a_ses_considerations>> describes some optional groupings that may be of interest for safety, effectiveness and security considerations and <<vol1_clause_sdpi_a_cross_profile_considerations>> describes some optional groupings in other related profiles.

[#vol1_table_sdpi_a_required_actor_groupings]
.SDPi-A - Required Actor Groupings
[%autowidth]
[cols="1,1,1,1"]
|===
.^|SDPi-A Actor
.^|Grouping Condition
.^|Actor(s) to be Grouped With
.^|TF Reference

| <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>>
| --
| <<vol1_spec_sdpi_p_actor_somds_consumer>>
| <<vol1_clause_sdpi_a_somds_medical_alert_consumer>>

| <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>>
| --
| <<vol1_spec_sdpi_p_actor_somds_provider>>
| <<vol1_clause_sdpi_a_somds_medical_alert_provider>>

| <<vol1_spec_sdpi_a_actor_somds_acm_gateway>>
| --
| <<vol1_spec_sdpi_p_actor_somds_v2_gateway>>
| <<vol1_clause_sdpi_a_somds_acm_gateway>>


|===


// 12.4
=== SDPi-A Overview


// 12.4.1
==== Concepts

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{supplement_note}*:  An overview of the concepts for this <<vol1_clause_sdpi_a_profile_reftext>> will be provided in a future supplement version.
Note that this specification extends the concepts established in the base <<vol1_clause_sdpi_p_profile_reftext>>.
|===

[#vol1_clause_sdpi_a_use_cases_reftext, reftext='SDPi-A Use Cases']
==== Use Cases
The SDPi-A Profile supports requirements from use cases detailed in <<vol1_appendix_c_dpi_use_cases>>.
The following subsections identify the specific use case requirements that are fulfilled with capabilities provided by this SDPi-A Profile.


[role="support-use-case", use-case-id="sicdsp", oid-arcs=.1]
===== <<label_use_case_name_sicdsp>> (<<acronym_sicdsp>>)
This use case provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_sicdsp>>.

Specific capabilities supporting the <<acronym_sicdsp>> use case include:

* *System Type*:  N/A
* *Service Type*:  N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: <<acronym_sicdsp>> <<vol1_clause_appendix_c_use_case_sicdsp_scenarios>> communication of medical alert information to a <<vol1_spec_sdpi_p_actor_somds_consumer>> <<system_type_dashboard>>

sdpi_support_use_case::somds_medical_alert_consumer[support=optional]


[role="support-use-case", use-case-id="sicdmp", oid-arcs=.2]
===== <<label_use_case_name_sicdmp>> (<<acronym_sicdmp>>)
This use case provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_sicdmp>>.

Specific capabilities supporting the <<acronym_sicdmp>> use case include:

* *System Type*:  N/A
* *System Type*:  N/A
* *Technical Pre-Conditions*: N/A
* *Scenarios*: <<acronym_sicdmp>> <<vol1_clause_appendix_c_use_case_sicdmp_scenarios>> communication of medical alert information to a <<vol1_spec_sdpi_p_actor_somds_consumer>> <<system_type_dashboard>>

sdpi_support_use_case::somds_medical_alert_consumer[support=optional]

[role="support-use-case", use-case-id="acns", oid-arcs=.3]
===== <<label_use_case_name_acns>> (<<acronym_acns>>)
This use case provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_acns>>.

Specific capabilities supporting the <<acronym_acns>> use case include:

* *System Type*:  N/A
* *Service Type*:  N/A
* *Technical Pre-Conditions*:  N/A
* *Scenarios*:  <<acronym_acns>> <<vol1_clause_appendix_c_use_case_acns_scenarios>> communication of medical alert information to a <<vol1_spec_sdpi_p_actor_somds_consumer>> Alert <<system_type_device_gateway>>

sdpi_support_use_case::somds_acm_gateway[support=optional]

[role="support-use-case", use-case-id="aars", oid-arcs=.3]
===== <<label_use_case_name_aars>> (<<acronym_aars>>)
This use case provides capabilities for requirements from <<vol1_clause_appendix_c_use_case_aars>>.

Specific capabilities supporting the <<acronym_aars>> use case include:

* *System Type*:  N/A
* *Service Type*:  N/A
* *Technical Pre-Conditions*:  N/A
* *Scenarios*:  <<acronym_aars>> <<vol1_clause_appendix_c_use_case_aars_scenarios>> communication of medical alert information to a <<vol1_spec_sdpi_p_actor_somds_consumer>> Alert <<system_type_device_gateway>>

sdpi_support_use_case::somds_acm_gateway[support=optional]

[#vol1_clause_sdpi_a_ses_considerations]
=== SDPi-A Safety, Effectiveness and Security - Requirements and Considerations

==== SES General Considerations

Of all the SDPi Profiles, the Alerting profile is the most challenging regarding ensuring implementations are safe, effective & secure (<acronym_ses>>).
This is due in part to the unique and dynamic care environments into which these systems are deployed, requiring significant risk management efforts throughout the entire technology lifecycle.
To that end, requirements from the <<ref_iso_81001_1_2021>>, <<ref_iec_80001_1_2021>>, and related standards should be fully applied to this technical framework element.
Additionally, requirements from the <<ref_ieee_11073_10702_202x>> should be fully implemented in any implementation of the SDPi Profiles.  For example, a <<vol1_spec_sdpi_a_actor_somds_medical_alert_provider>> may indicate a maximum delay time, which if not met by a <<vol1_spec_sdpi_a_actor_somds_medical_alert_consumer>> could result in stopping an active "silent mode" state.

The above standards include processes for determining what potential alert annunciation latency or delay periods are clinically acceptable, as well as the specification of specific risk control measures that facilitate the establishment of a robust and resilient interoperable infrastructure for communicating alert conditions.
Many specific implementation details such as the use of wireless technology, has to include a full assessment of the environment of use (e.g., to understand the potential impact of "noise" and coexistence challenges).

Additional device-specific standards may specify latency or delay thresholds.
For example, the <<ref_iec_60601_2_27_2011>> standard specifies a delay for "brady" alerts (i.e., 10 seconds); however, the realization of this requirement must be understood in the care environment and the systems and network configuration that is utilized for communication of that alert condition.  In other words, even when there is a particular standard that defines a specific time constraint, risk management based on that implementation environment must be fully performed and maintained during operation in order to ensure the clinical needs are met.

For additional general guidance, see Section <<vol1_clause_appendix_a_ses_considerations_and_requirements>>.

==== Safety Requirements & Considerations
No additional safety requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ Section above.

==== Effectiveness Requirements & Considerations
No additional effectiveness requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ Section above.

==== Security Requirements & Considerations
No additional security requirements and considerations are identified for this technical framework element beyond those provided by the  SDPi-P Profile (see <<vol1_clause_appendix_a_ses_considerations_section_template>>), and those specified in the _<<acronym_ses>> General Considerations_ Section above.

[#vol1_clause_sdpi_a_cross_profile_considerations]
=== SDPi-A Cross Profile Considerations
No additional cross profile considerations have been identified.

////
#TODO:  See the template instructions + PCD 2019 and other TF's to see if any content should go in this section for SDPi-A.#
////

