==== Safety, Effectiveness, Security Considerations and Requirements

===== SES General Considerations
Requirements from the <<ref_iso_81001_1_2021>>, <<ref_iec_80001_1_2021>>, and related standards should be fully applied to this technical framework element.

For additional guidance, see <<vol1_clause_appendix_a_ses_considerations_and_requirements>>.

===== Safety Requirements & Considerations
No additional safety requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

===== Effectiveness Requirements & Considerations
No additional effectiveness requirements or considerations are identified for this technical framework element beyond those specified in the _<<acronym_ses>> General Considerations_ section above.

===== Security Requirements & Considerations
This transaction is intended to execute over *_SECURED_* transmission channels.

Protocol-specific security requirements for this transaction are detailed in the related TF-2 messaging technology appendix.
For example, <<vol2_appendix_a_mdpws_messages>> for <<acronym_mdpws>>-based communication.

Appropriate security risk management is performed in order to ensure that no unacceptable harm results during *_SECURED_* message exchange.

