// ISO/IEC 60601-1-8 Overview & Definitions for DIS / DAS / CDAS Use Cases


//[sdpi_offset=2]
[#vol1_appendix_c_60601_1_8_concepts_for_dis_das_cdas]
===== ISO/IEC 60601-1-8 Concepts for DIS, DAS and CDAS

The following is a quick guide to the functionality of DIS, CDIS, DAS and CDAS systems and how we have used and interpreted them for the purpose of this IHE Profile Supplement.
Please refer to the next section on Definitions from <<ref_iec_60601_1_8_2020>> for normative definitions for these terms.

NOTE: Note that the {ihe_supplement_sdpi_revision_short} version of the SDPi Profile only supports the Distributed Information System (DIS) model detailed below.
The other models are anticipated for subsequent versions.


====== DIS – Distributed Information System

*DIS* is a system for reporting alarm signals with no technical confirmation (of receipt).

• Cannot rely on it for alarm signaling as a risk control

• Optional support operator alarm management response locally

• Example -- patient remote display, hallway display, one-way pager

====== CDIS – Distributed Information System with Confirmation

*CDIS* is a system for reporting alarm signals with no technical confirmation but with operator confirmation (accept/reject).

NOTE: CDIS is not recognized in 60601-1-8, however it is implemented in practice and therefore included


• Cannot rely on it for alarm signaling as a risk control

• Optional support operator alarm management response locally and remotely

• Example –- two-way pager (open loop)

====== DAS – Distributed Alarm System

*DAS* is a system for reporting alarm signals with technical confirmation (of receipt).

• Can rely on it for alarm signaling as a risk control

• Optionally supports local alarm management (alarm acknowledgement)

• A communications failure or failure in any remote component of the DAS must initiate a technical alarm.

• Example -- Central Station

====== CDAS - Distributed Alarm System with Confirmation

*CDAS* is a system for reporting alarm signals with technical and operator confirmation (accept/reject) (of receipt).

• Can rely on it for alarm signaling as a risk control

• Supports operator confirmation (accept/reject); It may redirect…

• Optionally support local/remote alarm management (acknowledgement)

• A communications failure or failure in any remote component of the DAS must initiate a technical alarm.

• Example -- System that sends alarm to caregiver mobile device with accept / reject.  Integrator may redirect

NOTE: An xDIS can be either a DIS or CDIS.  Similarly an xDAS can be either a DAS or CDAS.

[%autowidth]
[cols="^2,^1,^1,^1,^1,^2"]
|===
|Description |Type|Technical Delivery Confirmation^1^|Operator Delivery Confirmation^2^|Optional Alarm Management|Examples

.4+.^|Reports alerts from a single patient (sp)
.^| DISsp
.^| No
.^| No
.^| Local
.^| Single-Pt. information Dashboard

.^| CDISsp
.^| No
.^| Yes^3^
.^| Remote^3^
.^| Single-Pt. Remote View w/accept/reject

.^| DASsp
.^| Yes
.^| No
.^| Local
.^| Single-Pt. Cockpit w/audible alarms

.^| CDASsp
.^| Yes
.^| Yes
.^| Remote
.^| Single-Pt. Cockpit w/accept/reject

.4+.^|Reports alerts from multiple patients (mp)
.^| DISmp
.^| No
.^| No
.^| Local
.^| Multiple-Pt. information Dashboard or View Station

.^| CDISmp
.^| No
.^| Yes^3^
.^| Remote^3^
.^| Multiple-Pt. info. View Station w/accept/reject

.^| DASmp
.^| Yes
.^| No
.^| Local
.^| Multiple-Pt. Central Station w/audible alarms

.^| CDASmp
.^| Yes
.^| Yes
.^| Remote
.^| Multiple-Pt. Central Station w/accept/reject

.4+.^|Reports and directs alerts to responsible caregiver (cg)
.^| DIScg
.^| No
.^| No
.^| Local
.^| Alerts to caregiver pager, Mobile viewer

.^| CDIScg
.^| No
.^| Yes^3^
.^| Remote^3^
.^| Alerts to caregiver pager, w/accept/reject

.^| DAScg
.^| Yes
.^| No
.^| Local
.^| Alerts to caregiver w/audible/haptic signals

.^| CDAScg
.^| Yes
.^| Yes
.^| Remote
.^| Alerts to caregiver w/accept/reject

6+<| ^1^ In each communication step the receiving device provides a technical response to the sending device that it received and is taking responsibility for the alert

^2^ Operator can, at their choice, use the receiving device (communicator) UI to accept or reject responsibility for the alert

^3^ Not recommended since there is no confirmation that the Source has received the commands
|===

===== ISO/IEC 60601-1-8 Definitions for DIS, DAS and CDAS

The following content is extracted directly from the <<ref_iec_60601_1_8_2020>> standard for reference purposes.
Please consult that standard for comprehensive discussion and complete normative requirements, as well as the "rationale" section, which includes many of the concepts identified in this section.

////
#TODO: REVIEW THE CONTENT OF THIS SECTION FOR ANY COPYRIGHT REQUIREMENTS - PERHAPS ENGAGE HAE CHOE/AAMI... ALSO NEED TO ADD DEFINITIONS FOR TERMS SUCH AS ME SYSTEM, ME EQUIPMENT, ETC.#
////

====== DIS - DISTRIBUTED INFORMATION SYSTEM ABOUT ALARM CONDITIONS
system that involves more than one item of equipment in a ME SYSTEM intended to provide information about ALARM CONDITIONS but does not guarantee delivery of that information

NOTE: NOTE 1: A DISTRIBUTED INFORMATION SYSTEM ABOUT ALARM CONDITIONS is not intended to notify OPERATORS of the existence of an ALARM CONDITION as a RISK CONTROL measure.
A DISTRIBUTED INFORMATION SYSTEM ABOUT ALARM CONDITIONS is intended to provide information about an ALARM CONDITION while the OPERATOR is aware of the existence of the ALARM CONDITION by an ALARM SYSTEM.

NOTE: NOTE 2: A DISTRIBUTED INFORMATION SYSTEM ABOUT ALARM CONDITIONS is not intended for confirmed delivery of ALARM CONDITIONS

Examples include:
[none]
. Sometimes referred to as secondary alerting devices: Hallway display of active alarms; Hallway light over room door; Caregiver worn device;

====== DAS - DISTRIBUTED ALARM SYSTEM
ALARM SYSTEM that involves more than one item of equipment in a ME SYSTEM intended for delivery of ALARM CONDITIONS with technical confirmation

NOTE: NOTE 1: The parts of a DISTRIBUTED ALARM SYSTEM can be widely separated in distance.

NOTE: NOTE 2: A DISTRIBUTED ALARM SYSTEM is intended to notify OPERATORS of the existence of an ALARM CONDITION.

NOTE: NOTE 3: For the purposes of this document, technical confirmation means that each element of a DISTRIBUTED ALARM SYSTEM confirms or guarantees the successful delivery of the ALARM CONDITION to the next element or appropriate TECHNICAL ALARM CONDITIONS are created as described in clause 6.11.2.2.1 of <<ref_iec_60601_1_8_2020>>.

.IEC 60601-1-8:2020, Figure 2 -- Functions of a DISTRIBUTED ALARM SYSTEM utilizing a MEDICAL IT NETWORK
image::../images/vol1-diagram-60601-1-8-2020-figure-2.svg[]

Examples include:

- EXAMPLE 1 – A central station
- EXAMPLE 2 – An electronic record-keeping device
- EXAMPLE 3 – Remote viewing from home or office
- EXAMPLE 4 – Bed-to-bed viewing of ALARM CONDITIONS (e.g., one nurse for two beds).
- EXAMPLE 5 – Transmission of ALARM CONDITIONS to pagers, cell phones, hand-held computers, etc.

====== CDAS - DISTRIBUTED ALARM SYSTEM WITH OPERATOR CONFIRMATION
DISTRIBUTED ALARM SYSTEM that includes the capability to receive an OPERATOR response

Examples include:

- Traditional Central Station;
- Bed to Bed alarm feature supporting alarm acknowledge;
- Caregiver worn device supporting alarm acknowledge

[sdpi_level=+1]
====== IEC 60601-1-8:2020, Subclause 6.11.2.4 CDAS

In a CDAS, the COMMUNICATOR that receives an ALARM CONDITION shall have means to create the OPERATOR responses (RESPONSIBILITY ACCEPTED or RESPONSIBILITY REJECTED) and transfer them to the INTEGRATOR.

[loweralpha]
. In a CDAS, the COMMUNICATOR that receives an ALARM CONDITION and initiates an OPERATOR response (RESPONSIBILITY ACCEPTED or RESPONSIBILITY REJECTED) shall indicate the OPERATOR response state (RESPONSIBILITY ACCEPTED or RESPONSIBILITY REJECTED).

The means of control used to initiate an OPERATOR response or indication of state may be marked with:

[loweralpha]
. symbol ISO 7000-6334A (2015-06) (see Symbol 13 of Table C.1) for RESPONSIBILITY ACCEPTED; or

. symbol ISO 7000-6335A (2015-06) (see Symbol 16 of Table C.1) for RESPONSIBILITY REJECTED.

Means shall be provided for the OPERATOR to terminate RESPONSIBILITY ACCEPTED or RESPONSIBILITY REJECTED while the related ALARM CONDITION is active.
Initiating RESPONSIBILITY REJECTED may be used to terminate RESPONSIBILITY ACCEPTED. Initiating RESPONSIBILITY ACCEPTED may be used to terminate RESPONSIBILITY REJECTED.

In a CDAS, RESPONSIBILITY ACCEPTED may initiate an ALARM SIGNAL inactivation state.

NOTE RESPONSIBILITY ACCEPTED is a different function than an ALARM SIGNAL inactivation state.

In a CDAS, the INTEGRATOR shall have means to accept OPERATOR responses from the COMMUNICATOR.

In a CDAS, the SOURCE may receive OPERATOR responses from the INTEGRATOR.

////
#TODO: MAKE THE FOLLOWING SECTION ONE LEVEL DEEPER#
////

[sdpi_level=+1]
====== IEC 60601-1-8:2020, Subclause 6.11.2.4 – CDAS

The terms RESPONSIBILITY ACCEPTED, RESPONSIBILITY REJECTED, and RESPONSIBILITY UNDEFINED are new to this document.
They are most often applicable to a DISTRIBUTED ALARM SYSTEM for use in an intensive care setting or a hospital ward setting, in which each OPERATOR has a COMMUNICATOR (example: pocket pager or phone) that provides an ALARM CONDITION to a specific OPERATOR.
If the DISTRIBUTED ALARM SYSTEM presents an ALARM CONDITION to a specific OPERATOR, then there can be three possibilities:

• the specific OPERATOR accepts responsibility for the ALARM CONDITION, and the state RESPONSIBILITY ACCEPTED becomes true;

• the specific OPERATOR is busy and therefore rejects responsibility, the state RESPONSIBILITY REJECTED becomes true, and the DISTRIBUTED ALARM SYSTEM redirects the ALARM CONDITION to a different COMMUNICATOR, hence OPERATOR;

• the OPERATOR does not respond to the ALARM SIGNAL within the timeframe established by the RESPONSIBLE ORGANIZATION in the INTEGRATOR, the state RESPONSIBILITY UNDEFINED becomes true, and the INTEGRATOR redirects the ALARM CONDITION to a different COMMUNICATOR, hence OPERATOR in this instance also.

A similar configuration might be provided for other DISTRIBUTED ALARM SYSTEMS, for instance, from a bedside monitor to a different bedside monitor, or from a beside monitor to a central station.

Care is needed in the design of a CDAS when there is a non-homogenous set of SOURCES.
The logic (REDIRECTION and ESCALATION) behind the processing of RESPONSIBILITY UNDEFINED can become very complex and needs to take into account how each SOURCE responds to the resulting states.
These complex systems can inadvertently cause ALARM FLOOD or ‘lost’ ALARM CONDITIONS (i.e., no assigned COMMUNICATOR).

Such a configuration would not be expected in ME EQUIPMENT without a DISTRIBUTED ALARM SYSTEM.
For example, an anaesthesia workstation, for which an OPERATOR is normally present during all PATIENT care, would not be expected to provide these functions.
