[#vol3_clause_report-sequence]
====== Report sequence

BICEPS does not provide a method for consumers to detect missing or out of order notification messages delivered during publish-subscribe sessions established through Transaction [DEV-27] (<<vol2_clause_dev_27>>). Notification messages may be lost, for example, in complex implementations with proxy and/or relay services between the <<vol1_spec_sdpi_p_actor_somds_provider>> and <<vol1_spec_sdpi_p_actor_somds_consumer>>. Notification messages may arrive out-of-order, for example, in complex systems using load-balancing servers to receive reports. 

This extension provides a mechanism for a <<vol1_spec_sdpi_p_actor_somds_provider>> to include message numbers to order the sequence of notification messages delivered during a publish-subscribe session. This mechanism supports both full subscribers ( <<vol1_spec_sdpi_p_actor_somds_consumer>>s that subscribe to every report offered by a  <<vol1_spec_sdpi_p_actor_somds_provider>>), and partial subscribers (<<vol1_spec_sdpi_p_actor_somds_consumer>>s that subscribe to a subset of reports offered by a  <<vol1_spec_sdpi_p_actor_somds_provider>>). Well designed <<vol1_spec_sdpi_p_actor_somds_consumer>>s may choose, where feasible, a subset of reports to reduce processing requirements and network bandwidth consumption.

[sdpi_level=+1]
====== Model

The report sequence XML schema is available in <<vol3_appendix_a_xml_schemas_report_sequence>>. <<vol3_example_extension_report_sequence>> shows an exemplary XML instance of a <<vol2_clause_appendix_mdpws_dev_29, {var_label_dev_29_message_metricreport}>> including the report sequence extension in the message header.

.<<vol2_clause_appendix_mdpws_dev_29, {var_label_dev_29_message_metricreport}>> with report sequence extension.
[#vol3_example_extension_report_sequence]
====
[source,xml]
----
include::../../listings/vol3-clause-biceps-content-example-report-sequence.xml[]
----
====


[sdpi_level=+1]
====== Requirements

.R0800
[sdpi_requirement#r0800,sdpi_req_level=shall]
****
The <<vol1_spec_sdpi_p_actor_somds_provider>> shall set the `sdpi:ReportSequence/@MessageNumber` to 1 for the first notification message sent in a new publish-subscribe session.

.Notes
[%collapsible]
====
NOTE: A new publish-subscribe session begins when the <<vol1_spec_sdpi_p_actor_somds_provider>> receives a Subscribe message.

NOTE: A <<vol1_spec_sdpi_p_actor_somds_provider>> may send the first report before sending the SubscribeResponse message.

NOTE: The `sdpi:ReportSequence/@MessageNumber` is scoped to the publish-subscribe session. Different subscriptions may share the same `sdpi:ReportSequence/@MessageNumber`.
====
****

.R0801
[sdpi_requirement#r0801,sdpi_req_level=shall]
****
The <<vol1_spec_sdpi_p_actor_somds_provider>> shall increment the `sdpi:ReportSequence/@MessageNumber` by exactly 1 only when it receives confirmation of successful delivery of the notification message.

.Notes
[%collapsible]
====
NOTE: A <<vol1_spec_sdpi_p_actor_somds_provider>> only increments the `sdpi:ReportSequence/@MessageNumber` for successfully delivered notification messages.

NOTE: Successful delivery for <<vol1_spec_sdpi_p_actor_somds_participant>>s using <<ref_w3c_soap_over_http_v1_2, SOAP over HTTP transport>> is indicated by an HTTP status code between 200 and 299.

NOTE: A response may be generated by a server layer before the message reaches a <<vol1_spec_sdpi_p_actor_somds_consumer>>. HTTP response 503 (service unavailable) is an example of a status code that may be generated by a server layer. The <<vol1_spec_sdpi_p_actor_somds_provider>> does not change the `sdpi:ReportSequence/@MessageNumber` when it receives a fault status response. 
====
****

.R0802
[sdpi_requirement#r0802,sdpi_req_level=shall]
****
Two reports sent with the same `sdpi:ReportSequence/@MessageNumber` shall be functionally identical unless the <<vol1_spec_sdpi_p_actor_somds_provider>> receives a fault response to a notification message from the recipient.

.Notes
[%collapsible]
====
NOTE: A <<vol1_spec_sdpi_p_actor_somds_provider>> may change the content of a report to resolve a fault when it receives a fault response. 

NOTE: A timeout (no response or partial response) should not be considered a fault response from the recipient because the recipient's response may not have been delivered. A <<vol1_spec_sdpi_p_actor_somds_provider>> doesn't change the message content if if receives no response. 

NOTE: The transport channel may be closed, flushed or otherwise reset when no response or a partial response is received without affecting the `sdpi:ReportSequence/@MessageNumber`.
====
****
