[#vol3_clause_inter_mds_relationship]
====== Inter MDS Relationship

BICEPS does not provide means to define relationships between <<acronym_mds>>s in the same <<acronym_mdib>> since it does not support the nested <<acronym_mds>> concept.
However, in some multi-MDS scenarios it is important to provide information about the relationship between the devices.

Examples are transport patient monitoring devices which are plugged into stationary patient monitoring devices when the patients are in beds on the care unit, infusion pumps which are plugged into a rack system, and so on.

In these scenarios, the hosting device usually provides services to the plugged-in devices such as power supply, context synchronization, network access, and so on.

[sdpi_level=+1]
====== Model

The Inter MDS Relationship XML Schema is available in <<vol3_appendix_a_xml_schemas_inter_mds_relationship>>. <<vol3_example_extension_inter_mds_relationship>> shows an exemplary XML instance of a <<vol2_clause_dev_30_message_getmdibresponse, {var_label_dev_30_message_getmdibresponse}>> including the Inter MDS Relationship extension in the state part of the MDIB.

.<<acronym_mds>>s with Inter MDS Relationship extension
[#vol3_example_extension_inter_mds_relationship]
====
[source,xml]
----
include::../../listings/vol3-clause-biceps-content-example-inter-mds-relationship.xml[]
----
====

[sdpi_level=+1]
====== Requirements

.R0613
[sdpi_requirement#r0613,sdpi_req_level=should,sdpi_req_type=tech_feature]
****

[NORMATIVE]
====
For each <<acronym_mds>> in the <<acronym_mdib>> of a <<vol1_spec_sdpi_p_actor_somds_provider>>, if the <<acronym_mds>> has a parent relationship to one or more other child <<acronym_mds>>s in the same <<acronym_mdib>>, the <<vol1_spec_sdpi_p_actor_somds_provider>> should add a `sdpi:Relations` element to `pm:MdState/ext:Extension` with at least one `sdpi:Relation` including at least the following data:

* `sdpi:Code/@Code = "68167"` (MDC_ATTR_SOURCE_HANDLE_REF)
* `@Kind = "ECE"`
* `@Entries = _<list of handle references to child MDSs>_`
====
****

.R0614
[sdpi_requirement#r0614,sdpi_req_level=should,sdpi_req_type=tech_feature]
****
[NORMATIVE]
====
For each <<acronym_mds>> in the <<acronym_mdib>> of a <<vol1_spec_sdpi_p_actor_somds_provider>>, if the <<acronym_mds>> has a child relationship to one or more other parent <<acronym_mds>>s in the same <<acronym_mdib>>, the <<vol1_spec_sdpi_p_actor_somds_provider>> should add a `sdpi:Relations` element to `pm:MdState/ext:Extension` with at least one `sdpi:Relation` including at least the following data:

* `sdpi:Code/@Code = "68167"` (MDC_ATTR_SOURCE_HANDLE_REF)
* `@Kind = "DCE"`
* `@Entries = _<handle reference to parent MDS>_`
====
****