[#vol3_clause_timestamp_versioning]
====== Timestamp versioning

BICEPS does not provide any means to convey step-changes in a <<vol1_spec_sdpi_p_actor_somds_participant>>'s <<term_time_reference_frame>> (see <<vol1_clause_appendix_c_use_case_stad_non_slew, use case for non-slewing time adjustments>>). 

A <<vol1_spec_sdpi_p_actor_somds_provider>> includes <<term_timestamp>>s in many state updates. For example: `pm:AlertConditionState/@DeterminationTime`, `pm:AbstractMetricValue/@DeterminationTime` and `pm:AbstractContextState/@BindingStartTime`. From time-to-time, though rarely in normal operation, a 
<<vol1_spec_sdpi_p_actor_somds_participant>> may determine that the difference between its <<term_time_reference_frame>> and that of the <<acronym_ts_service>> is greater than can be accommodated by <<term_smooth_time_adjustments>> to the <<term_system_clock>>. This may occur, for example:

* when a device is used in an emergency or wireless situation, collecting data before joining a network and updating its clock,
* when the <<acronym_ts_service>> is unreachable for prolonged periods, or
* following hardware failures and/or operator errors in the <<vol1_spec_sdpi_p_actor_somds_provider>> and/or <<acronym_ts_service>>, or
* after switching to a different and/or backup <<acronym_ts_service>> when the primary <<acronym_ts_service>> becomes unavailable, or
* when network congestion leads to asymmetrical network transport delays while exchanging messages with the <<acronym_ts_service>>.

In <<ref_rfc_5905>> this is referred to as a step-adjustment or a non-slewing time adjustment. In the absence of step-adjustments, <<term_timestamp>>s generated by a <<vol1_spec_sdpi_p_actor_somds_participant>>'s <<term_system_clock>> are well-behaved:

* they never decrease,
* have a well defined relationship to timestamps within the same <<term_epoch>>, and
* have well defined relationships to peer <<term_system_clock>>s and <<term_reference_clock>>s.

The presence of <<term_abrupt_time_adjustment>> creates <<term_epoch>>s of consistency: periods where the <<vol1_spec_sdpi_p_actor_somds_participant>>'s timestamps are well-behaved, separated by step-changes. At best, <<term_epoch>> are separated by a constant temporal offset; at worst <<vol1_spec_sdpi_p_actor_somds_participant>>s may have insufficient information to determine the relationship between <<term_epoch>> (e.g., changes at the <<acronym_ts_service>> that do not represent a change in elapsed time to unbiased observers). 

[NOTE]
====
R1520 excludes non-slewing adjustments (<<term_abrupt_time_adjustment>>s) to the <<acronym_ts_service>> by the RESPONSIBLE ORGANIZATION during normal operation. 

====

The diagram below illustrates a sequence of state updates (`m1`, `m2`, `m3`, `m4`) using <<term_timestamp>>s from three different epochs (3, 4, 5). In the illustration, an <<term_abrupt_time_adjustment>> shifted the device's <<term_time_reference_frame>> forward by four hours from 7 am to 11 am, creating (from the device's perspective) a gap in time. A second <<term_abrupt_time_adjustment>> shifted the device's <<term_time_reference_frame>> backward three hours from 1 pm to 10 am. The device experienced three <<term_abrupt_time_adjustment>>s in the past (because the first epoch version is 0).

image::../images/vol3-diagram-biceps-ext-non-slewing_time.svg[align=center]

NOTE: The <<term_abrupt_time_adjustment>>s serve to illustrate the extension only; it would be very unusual for a device to experience the time adjustments shown. 

A <<vol1_spec_sdpi_p_actor_somds_provider>> may start a new MDIB versioning sequence when it encounters an <<term_abrupt_time_adjustment>>. However, this may disrupt one or more System Function Contributions (<<acronym_sfc>>) by the <<vol1_spec_sdpi_p_actor_somds_provider>> or its <<acronym_somds>> peers. 

NOTE: A <<vol1_spec_sdpi_p_actor_somds_provider>> is not required to create a new MDIB versioning sequence when it encounters an <<term_abrupt_time_adjustment>> (see <<r1522>>).

This specification adds an extension to the BICEPS Participant Model enabling richer communication of changes to the <<vol1_spec_sdpi_p_actor_somds_participant>>'s local time-reference frame using a combination of:

* epoch versioning,
* optional epoch time-step offsets,
* optional versioning of `pm:CalibrationInfo/@Time`, `pm:AlertSystemState/@LastSelfCheck`, `pm:AlertConditionState/@DeterminationTime`, `pm:AbstractMetricValue/@StartTime`, `pm:AbstractMetricValue/@StopTime`, `pm:AbstractMetricValue/@DeterminationTime`, `pm:AbstractContextState/@BindingStartTime` and `pm:AbstractContextState/@BindingEndTime`. 

Other Biceps extensions may provide similar mechanisms to version appropriate timestamps. Refer to the extension documentation and schema for details. 

.R0615
[sdpi_requirement#r0615,sdpi_req_level=should]
****
Biceps extensions, with timestamps who's interpretation by a <<vol1_spec_sdpi_p_actor_somds_participant>> would be affected by unexpected abrupt time adjustments, should support timestamp versioning using this extension. 

.Notes
[NOTE]
[%collapsible]
====
* Extension authors can add types that inherit from `sdpi:TimestampEpochVersionType` to support versioning their timestamps. 
====

****

[sdpi_level=+1]
====== Model

The clock epoch schema is available in <<vol3_appendix_a_xml_schemas_timestamp_version>>. There are three parts to the extension:

. `sdpi:EpochSupport`, an extension for `pm:ClockDescriptor` so that <<vol1_spec_sdpi_p_actor_somds_consumer>>s are aware that a <<vol1_spec_sdpi_p_actor_somds_provider>> implements this extension and may prepare to receive versioned timestamps. 
. `sdpi:Epochs`, an extension for `pm:ClockState`, which contains a list of the <<term_epoch>>s referenced in the <<acronym_mdib>>.
. extensions to (optionally) attach epoch versions to `pm:AbstractState` timestamps found in `pm:CalibrationInfo`, `pm:AlertSystemState`, `pm:AlertConditionState`, `pm:AbstractMetricValue`, `pm:AbstractContextState`. 

In addition, this extension defines specific interpretation for `pm:ClockState/@ActivationState` and `pm:ClockState/@LastSet`. The `pm:ClockState/@ActivationState` is set to `StndBy` when any timestamp in a <<acronym_mdib>> version was not obtained from the current <<term_epoch>> regardless of whether that timestamp is versioned or not. This lets consumers know they may not be able to trust some or all of the timestamps in a <<acronym_mdib>> even if they don't understand this extension. To identify which timestamps are unreliable, `pm:ClockState/@LastSet` is set to the earliest reliable timestamp. That is, the earliest timestamp in a <<acronym_mdib>> version that is guaranteed to be in the current <<term_epoch>> considering the entire history of <<term_abrupt_time_adjustment>>s. It may be used to determine if a timestamp is reliable, even if it is not versioned. 

<<vol3_example_extension_clock_discontinuities>> shows an exemplary XML instance of a <<vol2_clause_dev_30_message_getmdibresponse, {var_label_dev_30_message_getmdibresponse}>> from a device that has experienced two recent <<term_abrupt_time_adjustment>>s following three adjustments some time in the past. It corresponds to the sequence of events in the diagram above. Of particular note:

* the provider supports this version of the timestamp versioning extension because the `pm:Clock` descriptor includes `sdpi:EpochSupport/[@Version='1']`. 
* in `pm:State[@xsi:type='pm:ClockState']`:
** `@ActivationState` is `StndBy` because the mdib contains timestamps that were not obtained from the current epoch (that is, `@DeterminationTime` for `m1` and `m2`),
** `@LastSet` shows any timestamp less than "1733317200000" (1 p.m.) may not be from the current epoch,
** `@DateAndTime` shows this mdib snapshot was created at "1733324400000" (3 p.m.),
** `sdpi:Epochs[@Version='5']` indicates the current epoch is 5,
** `sdpi:Epochs/Epoch` shows timestamps from epochs 4 and 3 may be used in the mdib; earlier versions are not included because they are not referenced in the mdib. The `@Timestamp` on, for example, epoch 4 records the time (in the epoch 4 <<term_time_reference_frame>> when the abrupt time adjustment was made; the equivalent time in epoch 5, the next <<term_time_reference_frame>>, can be determined by adding the `@Offset` to the `@Timestamp`).
* `pm:State[@DescriptorHandle='m1']` includes three timestamps (`DeterminationTime`, `StartTime` and `StopTime`); all were created in epoch 3.
* `pm:State[@DescriptorHandle='m2']` includes a single timestamp (`DeterminationTime`); it doesn't contain a specific epoch version however, the `DeterminationTime` is less than `pm:State[xsi:type='pm:ClockState']/@LastSet` so the timestamp _may_ be from an earlier epoch (and, as the diagram shows, `m2` was determined in epoch 4. However, the provider has decided not to provide that information, perhaps because this metric is regularly updated and a new value will be reported soon). 
* `pm:State[@DescriptorHandle='m3']` also includes a single timestamp (`DeterminationTime`); it doesn't contain a specific epoch version however, the `DeterminationTime` is less than `pm:State[xsi:type='pm:ClockState']/@LastSet` so the timestamp _may_ be from an earlier epoch (in this case, as the diagram shows, `m3` was determined in the current epoch. However, the provider has decided not to provide that information, perhaps because this metric is regularly updated and a new value will be reported soon). 
* `pm:State[@DescriptorHandle='m4']` also includes a single timestamp (`DeterminationTime`); again without an epoch version. However, the `DeterminationTime` is greater than `pm:State[xsi:type='pm:ClockState']/@LastSet` so the timestamp is from the current epoch.  

`sdpi:Epoch/@Offset` gives the change in time from the `sdpi:Epoch/@Timestamp` in the previous <<term_epoch>> to an equivalent point in time in the new epoch as shown in the diagram below.

image::../images/vol3-diagram-biceps-ext-non-slewing_adj.svg[align=center]

.Example MDIB state following two recent <<term_abrupt_time_adjustment>>s
[#vol3_example_extension_clock_discontinuities]
====
[source,xml]
----
include::../../listings/vol3-clause-biceps-content-example-timestamp-version.xml[]
----
====

[sdpi_level=+1]
====== Requirements

.R0600
[sdpi_requirement#r0600,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_provider>> shall include the `sdpi:EpochSupport` extension and set `sdpi:EpochSupport/@Version=1` in every <<term_system_clock>> `pm:ClockDescriptor`, used as part of its System Function Contribution (<<acronym_sfc>>), that uses epoch versioning for <<term_abrupt_time_adjustment>>s. 

.Notes
[NOTE]
[%collapsible]
====
* The presence of `sdpi:EpochSupport` indicates support for this extension and related requirements. 
* A <<vol1_spec_sdpi_p_actor_somds_provider>> may set `ext:MustUnderstand="true"` to prevent consumers that do not understand this extension from processing the <<acronym_mdib>>. 

====

****

.R0601
[sdpi_requirement#r0601,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_consumer>> shall ignore all epoch version information on any system clocks that do not include the `sdpi:EpochSupport` extension in any MDIB version or if the `sdpi:EpochSupport/@Version` changes within a single sequence id.

.Notes
[NOTE]
[%collapsible]
====
* The `spdi:EpochSupport` extension is intended to be immutable. 
* A <<vol1_spec_sdpi_p_actor_somds_consumer>> may rely on future versions of the extension being backwards compatible. 

====

****

.R0605
[sdpi_requirement#r0605,sdpi_req_level=shall]
****
The <<vol1_spec_sdpi_p_actor_somds_provider>> shall increment `sdpi:Epochs/@Version` by exactly one, beginning from 0, for every non-slewing time adjustment to any system clock used as part of its System Function Contribution (<<acronym_sfc>>). 

****

.R0606
[sdpi_requirement#r0606,sdpi_req_level=should]
****
A <<vol1_spec_sdpi_p_actor_somds_provider>> should set the version of all versioned timestamps to 0 when it assigns a new MDIB sequence identifier (`pm:MdibVersionGroup/@SequenceId`). 

.Notes
[NOTE]
[%collapsible]
====
* Epoch versions are generally scoped to the `pm:MdibVersionGroup/@SequenceId`. Some providers may carry versioned timestamps across new sequences, particularly if the new sequence is created for reasons other than an abrupt time adjustment. 

====
****

.R0610
[sdpi_requirement#r0610,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_provider>> that versions timestamps in any `pm:AbstractMetricValue`, `pm:AbstractContextState`, `pm:AlertSystemState`, `pm:CalibrationInfo` and/or `pm:AlertConditionState` shall include, in every clock state update, the complete history of epoch offsets from the earliest version referenced in the MDIB to the current epoch.  

.Notes
[NOTE]
[%collapsible]
====
* Epoch offsets provide a mechanism for consumers to (approximately) reconstruct time between epochs. Reconstruction can only be approximate because there is no mechanism to determine the source and timing of any external discrepancies that led to the abrupt change in a <<term_time_reference_frame>>. 
* This allows a <<vol1_spec_sdpi_p_actor_somds_provider>> to choose which timestamps it versions. For example context binding timestamps (which may remain out of date significantly longer than other metrics) could be versioned but regularly updated metrics may not require timestamp versions. 

====
****

.R0611
[sdpi_requirement#r0611,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_provider>> shall not change the epoch version assigned to a timestamp without creating a new timestamp. 

.Notes
[NOTE]
[%collapsible]
====
* Epoch versions and timestamps are immutable and may not change independently. 

====
****


