[#vol3_clause_timestamp_versioning]
====== Timestamp versioning

BICEPS does not provide any means to convey step-changes in a <<vol1_spec_sdpi_p_actor_somds_participant>>'s local time-reference frame (see use case <<acronym_stad>>, scenario {var_use_case_id}.6). 

A <<vol1_spec_sdpi_p_actor_somds_provider>> includes timestamps in many state updates including `pm:AlertConditionState/@DeterminationTime`, `pm:AbstractMetricValue/@DeterminationTime` and `pm:AbstractContextState/@BindingStartTime`. From time-to-time, a 
<<vol1_spec_sdpi_p_actor_somds_participant>> may determine that the difference between its time-reference frame and that of the TS Service is greater than can be accomodated by smooth adjustments to its clock source. This may occur, for example:

* when the TS Service is unreachable for a prolonged period, or
* following hardware failures and/or operator errors in the <<vol1_spec_sdpi_p_actor_somds_provider>> and/or TS Service, or
* after switching to a different and/or backup TS Service when the primary TS Service becomes unavailable,
* when network congestion leads to asymmetrical network transport delays while exchanging messages with the TS Service.

In <<ref_rfc_5905>> this is referred to as a step-adjustment or a non-slewing time adjustment. In the absence of step-adjustments, timestamps generated within a <<vol1_spec_sdpi_p_actor_somds_participant>>'s time-reference frame are well-behaved:

* never decrease,
* have a well defined relationship to timestamps generated by a primary time source, and
* a well defined relationship to each other. 

The presence of non-slewing time adjustments creates epochs, periods where the <<vol1_spec_sdpi_p_actor_somds_participant>>'s timestamps are well-behaved, separated by step-changes. At best, <<vol1_spec_sdpi_p_actor_somds_participant>>'s can guess at the relationship between each time-reference frame between epochs; at worst they may have insufficient information (e.g., non-slewing adjustment is caused by change at the TS Service). 

The diagram below illustrates a sequence of state updates incorporating time-stamps from two different epochs. In the illustration, a non-slewing adjustment has shifted the devices time-frame reference forward, creating a gap in time. Timestamps obtained in epoch 0, the time-frame reference immediately before the time-step was detected, may not be accurate. 

image::vol3-diagram-biceps-ext-non-slewing_time.svg[align=center]

[NOTE]
====
* R1520 excludes non-slewing adjustments to the TS Service by the RESPONSIBLE ORGANIZATION during normal operation. 

====

A <<vol1_spec_sdpi_p_actor_somds_provider>> may start a new MDIB versioning sequence when it encounters a non-slewing time adjustments. However, this may disrupt SYSTEM FUNCTION CONTRIBUTION. 

This specification adds an extension to the BICEPS Participant Model enabling richer communication of changes to the <<vol1_spec_sdpi_p_actor_somds_participant>>'s local time-reference frame using:

* epoch versioning,
* epoch time-step deltas,
* optional versioning of `CalibrationInfo/@Time`, `AlertSystemState/@LastSelfCheck`, `AlertConditionState/@DeterminationTime`, `AbstractMetricValue/@StartTime`, `AbstractMetricValue/@StopTime`, `AbstractMetricValue/@DeterminationTime`, `AbstractContextState/@BindingStartTime` and `AbstractContextState/@BindingEndTime`. 

[sdpi_level=+1]
====== Model

The clock epoch schema is available _somewhere_. <<vol3_example_extension_clock_discontinuities>> shows an exemplary XML instance of a <<vol2_clause_dev_30_message_getmdibresponse, {var_label_dev_30_message_getmdibresponse}>> from a device that has experienced two recent non-slewing time adjustments following three adjustments some time in the past. Of particular note:

* the clock state includes epoch time-step deltas for epoch 3 and 4; earlier versions are not referenced and therefore not required,
* the state for metric `m1` references epoch version 3; all timestamps in this state are versioned,
* the timestamp for metric `m2` is not versioned; its timestamp is less than `ClockState/@LastSet` and its value should be treated with greater suspicion than later timestamps, 
* although the current time (`ClockState/@DateAndTime`) is also less than `ClockState/@LastSet`, the current time is always reported using the current time-frame reference; its value need not be treated with any more suspicion than normal,
* each epoch time-step delta includes a version, timestamp and offset; the timestamp is in the time-frame reference of the versioned epoch. 

.Example MDIB state following two recent non-slewing time adjustments
[#vol3_example_extension_clock_discontinuities]
====
[source,xml]
----
include::../../listings/vol3-clause-biceps-content-example-timestamp-version.xml[]
----
====

[sdpi_level=+1]
====== Requirements

.R0600
[sdpi_requirement#r0600,sdpi_req_level=shall]
****
The <<vol1_spec_sdpi_p_actor_somds_provider>> shall increment `sdpi:Epochs/@Version` by exactly one for every non-slewing time adjustment. 

.Notes
[NOTE]
[%collapsible]
====
Non-slewing time-adjustments may be a serious error that impacts data that has already been:
 
 * displayed on a chart to the user,
 * exported to other systems.

====
****

.R0601
[sdpi_requirement#r0601,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_provider>> that versions timestamps in any `AbstractMetricValue`, `AbstractContextState`, `AlertSystemState`, `CalibrationInfo` and/or `AlertConditionState` shall include, in every clock state update, the complete history of epoch time-step deltas from the earliest version referenced in the MDIB to the current time reference-frame version.  

.Notes
[NOTE]
[%collapsible]
====
* Epoch time-step deltas provide a mechanism for consumers to (approximately) reconstruct time between epochs. Reconstruction can only be approximate because there is no mechanism to determine the source and timing of any external discrepancies that led to the abrupt change in time. 
* This allows a provider to select which timestamps it wants to version. For example context binding timestamps (which may remain out of date significantly longer than other metrics) could be versioned but regularly updated metrics might not need timestamp versions. 
====
****

