[#vol3_clause_timestamp_versioning]
====== Timestamp versioning

BICEPS does not provide any means to convey step-changes in a <<vol1_spec_sdpi_p_actor_somds_participant>>'s <<term_time_reference_frame>> (see <<vol1_clause_appendix_c_use_case_stad_non_slew, use case for non-slewing time adjustments>>). 

A <<vol1_spec_sdpi_p_actor_somds_provider>> includes <<term_timestamp>>s in many state updates including `pm:AlertConditionState/@DeterminationTime`, `pm:AbstractMetricValue/@DeterminationTime` and `pm:AbstractContextState/@BindingStartTime`. From time-to-time, though rarely in normal operation, a 
<<vol1_spec_sdpi_p_actor_somds_participant>> may determine that the difference between its <<term_time_reference_frame>> and that of the <<acronym_ts_service>> is greater than can be accommodated by <<term_smooth_time_adjustments>> to the <<term_system_clock>>. This may occur, for example:

* when the <<acronym_ts_service>> is unreachable for prolonged periods, or
* following hardware failures and/or operator errors in the <<vol1_spec_sdpi_p_actor_somds_provider>> and/or <<acronym_ts_service>>, or
* after switching to a different and/or backup <<acronym_ts_service>> when the primary <<acronym_ts_service>> becomes unavailable, or
* when network congestion leads to asymmetrical network transport delays while exchanging messages with the <<acronym_ts_service>>.

In <<ref_rfc_5905>> this is referred to as a step-adjustment or a non-slewing time adjustment. In the absence of step-adjustments, <<term_timestamp>>s generated by a <<vol1_spec_sdpi_p_actor_somds_participant>>'s <<term_system_clock>> are well-behaved:

* they never decrease,
* have a well defined relationship to timestamps within the same <<term_epoch>>, and
* have well defined relationships to peer <<term_system_clock>>s and <<term_reference_clock>>s.

The presence of <<term_abrupt_time_adjustment>> creates <<term_epoch>>s of consistency: periods where the <<vol1_spec_sdpi_p_actor_somds_participant>>'s timestamps are well-behaved, separated by step-changes. At best, <<term_epoch>> are separated by a constant temporal offset; at worst <<vol1_spec_sdpi_p_actor_somds_participant>>s may have insufficient information to determine the relationship between <<term_epoch>> (e.g., changes at the <<acronym_ts_service>> that do not represent a change in elapsed time to unbiased observers). 

[NOTE]
====
R1520 excludes non-slewing adjustments (<<term_abrupt_time_adjustment>>s) to the <<acronym_ts_service>> by the RESPONSIBLE ORGANIZATION during normal operation. 

====

The diagram below illustrates a sequence of state updates incorporating <<term_timestamp>>s from two different epochs. In the illustration, an <<term_abrupt_time_adjustment>> has shifted the device's <<term_time_reference_frame>> forward, creating (from the device's perspective) a gap in time. Timestamps obtained in epoch 0, before the required <<term_abrupt_time_adjustment>> was detected, may not be accurate (from the perspective of an unbiased observer). 

image::vol3-diagram-biceps-ext-non-slewing_time.svg[align=center]


A <<vol1_spec_sdpi_p_actor_somds_provider>> may start a new MDIB versioning sequence when it requires an <<term_abrupt_time_adjustment>>. However, this may disrupt one or more System Function Contributions (<<acronym_sfc>>) by the <<vol1_spec_sdpi_p_actor_somds_provider>> or its <<acronym_somds>> peers. 

This specification adds an extension to the BICEPS Participant Model enabling richer communication of changes to the <<vol1_spec_sdpi_p_actor_somds_participant>>'s local time-reference frame using:

* epoch versioning,
* optional epoch time-step offsets,
* optional versioning of `pm:CalibrationInfo/@Time`, `pm:AlertSystemState/@LastSelfCheck`, `pm:AlertConditionState/@DeterminationTime`, `pm:AbstractMetricValue/@StartTime`, `pm:AbstractMetricValue/@StopTime`, `pm:AbstractMetricValue/@DeterminationTime`, `pm:AbstractContextState/@BindingStartTime` and `pm:AbstractContextState/@BindingEndTime`. 

[sdpi_level=+1]
====== Model

The clock epoch schema is available in <<vol3_appendix_a_xml_schemas_timestamp_version>>. <<vol3_example_extension_clock_discontinuities>> shows an exemplary XML instance of a <<vol2_clause_dev_30_message_getmdibresponse, {var_label_dev_30_message_getmdibresponse}>> from a device that has experienced two recent <<term_abrupt_time_adjustment>>s following three adjustments some time in the past. Of particular note:

* the clock state includes epoch time-step offsets for epochs 3 and 4; earlier versions are not referenced and therefore not required,
* the state for metric `m1` references epoch version 3; all timestamps in this state are versioned,
* the timestamp for metric `m2` is not versioned; its timestamp is less than `pm:ClockState/@LastSet` and its value should be treated with greater suspicion than later timestamps, 
* although the current time (`pm:ClockState/@DateAndTime`) is also less than `pm:ClockState/@LastSet`, the current time is always reported using with <<term_timestamp>> from the current <<term_epoch>>; its value need not be treated with any more suspicion than normal,
* each `sdpi:Epoch` includes a `@Version`, `@Timestamp` and `@Offset`; the <<term_timestamp>> is from the versioned <<term_epoch>>, adding the `@Timestamp` and `@Offset` provides a timestamp for an equivalent point in time for the next epoch version (see illustration below),
* the default value of any timestamp not specifically versioned is the current <<term_epoch>> version. 

`sdpi:Epoch/@Offset` gives the change in time from the `sdpi:Epoch/@Timestamp` in the previous <<term_epoch>> to an equivalent point in time in the new epoch: 

image::vol3-diagram-biceps-ext-non-slewing_adj.svg[align=center]

.Example MDIB state following two recent <<term_abrupt_time_adjustment>>s
[#vol3_example_extension_clock_discontinuities]
====
[source,xml]
----
include::../../listings/vol3-clause-biceps-content-example-timestamp-version.xml[]
----
====

[sdpi_level=+1]
====== Requirements

.R0600
[sdpi_requirement#r0600,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_provider>> shall include the `sdpi:EpochSupport` extension and set `sdpi:EpochSupport/@Version=1` in every <<term_system_clock>> `pm:ClockDescriptor`, used as part of its System Function Contribution (<<acronym_sfc>>), that uses epoch versioning for <<term_abrupt_time_adjustment>>s. 

.Notes
[NOTE]
[%collapsible]
====
* The presence of `sdpi:EpochSupport` indicates support for this extension and related requirements. 
* A <<vol1_spec_sdpi_p_actor_somds_provider>> may set `ext:MustUnderstand="true"` to prevent consumers that do not understand this extension from processing the <<acronym_mdib>>. 

====

****

.R0601
[sdpi_requirement#r0601,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_consumer>> shall ignore all epoch version information on any system clocks that do not include the `sdpi:EpochSupport` extension in any MDIB version or if the `sdpi:EpochSupport/@Version` changes within a single sequence id.

.Notes
[NOTE]
[%collapsible]
====
* The `spdi:EpochSupport` extension is intended to immutable. 
* A <<vol1_spec_sdpi_p_actor_somds_consumer>> may rely on future versions of the extension being backwards compatible. 

====

****

.R0605
[sdpi_requirement#r0605,sdpi_req_level=shall]
****
The <<vol1_spec_sdpi_p_actor_somds_provider>> shall increment `sdpi:Epochs/@Version` by exactly one, beginning from 0, for every non-slewing time adjustment to any system clock used as part of its System Function Contribution (<<acronym_sfc>>). 

****

.R0606
[sdpi_requirement#r0606,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_provider>> shall set the version of all versioned timestamps to 0 when it assigns a new MDIB sequence identifier (`pm:MdibVersionGroup/@SequenceId`). 

.Notes
[NOTE]
[%collapsible]
====
* Epoch versions are scoped to the `pm:MdibVersionGroup/@SequenceId`.

====
****

.R0610
[sdpi_requirement#r0610,sdpi_req_level=shall]
****
A <<vol1_spec_sdpi_p_actor_somds_provider>> that versions timestamps in any `pm:AbstractMetricValue`, `pm:AbstractContextState`, `pm:AlertSystemState`, `pm:CalibrationInfo` and/or `pm:AlertConditionState` shall include, in every clock state update, the complete history of epoch offsets from the earliest version referenced in the MDIB to the current epoch.  

.Notes
[NOTE]
[%collapsible]
====
* Epoch offsets provide a mechanism for consumers to (approximately) reconstruct time between epochs. Reconstruction can only be approximate because there is no mechanism to determine the source and timing of any external discrepancies that led to the abrupt change in a <<term_time_reference_frame>>. 
* This allows a <<vol1_spec_sdpi_p_actor_somds_provider>> to choose which timestamps it versions. For example context binding timestamps (which may remain out of date significantly longer than other metrics) could be versioned but regularly updated metrics may not require timestamp versions. 

====
****


