// Standard Conformance Statement:  IEEE 11073-10700:2022

==== ISO/IEEE 11073-10700 Base requirements for participants ICS Tables

load-standard::IEEE-P11073-10700-2022.json[id=10700,cite="ref_ieee_11073_10700_2022"]

*Standard Version:*  ISO/IEEE 11073-10700:2022

ISO/IEEE 11073-10700 defines the base requirements for <<term_manufacturer>> of RefActor:somds_participant[] to support safe, effective and secure operation of 
RefActor:somds_participant[] in an <<term_service_oriented_medical_device_system>>

The _Status_ column indicates:

* *m*: mandatory, indicated by requirement keyword *shall*,
* *r*: recommended, indicated by requirement keyword *should*,
* *p*: permissible, indicated by requirement keyword *may*,


===== SOMDS Participants

.ICSs applicable to all SOMDS Participants
sdpi_ics_table::[sdpi_req_group="SDC Participant",standard-id=10700]

===== SOMDS Provider

.ICSs applicable to all SOMDS providers
sdpi_ics_table::[sdpi_req_group="SDC Service Provider",standard-id=10700]

===== SOMDS Consumer

.ICSs applicable to all SOMDS consumers
sdpi_ics_table::[sdpi_req_group="SDC Service Consumer",standard-id=10700]

