[appendix#vol3_appendix_c_oids,sdpi_offset=C]
== OID identifiers

Object identifiers, or OIDs, are globally unique numeric identifiers used to name something in a formal, unambiguous way. 
They are typically formatted as dotted number strings (`1.3.6.1.4.1.19376.1.6`, for example). Each number (or _arc_) is a node in a
hierarchical, tree-structured, namespace. The top of the tree, and first arc in the sequence, is managed by standards
bodies who delegate responsibility for distinct branches in the hierarchy. 

IHE DEV is responsible for managing arcs from the _IHE DEV parent_ OID `1.3.6.1.4.1.19376.1.6`.
See https://wiki.ihe.net/index.php/PCD_OID_Management[PCD OID Management] for canonical definitions 
of object identifiers for the profile, its actors and transactions, etc. It defines an arc for
for this service-oriented device point-of-care interoperability supplement: `1.3.6.1.4.1.19376.1.6.*10*`. 
This supplement is responsible for the hierarchy underneath the `1.3.6.1.4.1.19376.1.6.10` oid. 

This supplement defines the following hierarchy:

// NEW Version: ////
* `1.3.6.1.4.1.19376.1.6.2.10`: parent oid for service-oriented device point-of-care interoperability (SDPi)
** `.0`: parent OID for SDPi *conformity versioning*
*** `.2`: major version 2, for this version of the SDPi specification. 
**** `.2`: minor version 2, for this version of the SDPi specification.
***** `.1`: revision 1, for this version of the SDPi specification.

** `.1`: parent OID for *namespaces* defined in this specification (see <<vol0_table_xml_namespaces>>)
*** `.1`: extensions to the BICEPS participant and message models (see <<vol3_table_sdpi_biceps_extension_namespace>>)
**** `.1`: major version 1 for extensions to the BICEPS participant and message models
*** `.2`: discovery proxy objects (see <<vol2_table_appendix_mdpws_discovery_proxy_oids>>)
**** `.1`: discovery proxy subscription filter dialect 
**** `.2`: target WSDL namespace identifier for the discovery proxy actor.

** `.2`: parent OID for *SDPi profiles*
*** `.11`: OID for plug-and-trust profile (*SDPi-P*)
**** `.9`: parent OID for *use cases* defined in SDPi-P profile
***** `.1`: Synchronized Time Across Devices (STAD)
***** `.2`: Standalone ICU Dashboard Single Patient (SICDsp)
***** &vellip;
*** `.12`: OID for reporting profile (*SDPi-R*)
**** `.9`: parent OID for *use cases* defined in SDPi-R profile
***** `.2`: Standalone ICU Dashboard Single Patient (SICDsp)
***** `.3`: Standalone ICU Dashboard Multiple Patient (SICDmp)
***** &vellip;
*** `.13`: OID for alerting profile (*SDPi-A*)
**** `.9`: parent OID for *use cases* defined in SDPi-A profile
***** `.2`: Standalone ICU Dashboard Single Patient (SICDsp)
***** `.3`: Standalone ICU Dashboard Multiple Patient (SICDmp)
***** `.4`: Alerts to Clinician Notification Systems (ACNS)
***** &vellip;
*** `.14`: OID for external control profile (*SDPi-xC*)
**** `.9`: parent OID for *use cases* defined in SDPi-A profile

** `.3`: parent OID for all *actors* defined in SDPi
*** `.34`: SOMDS Medical Alert Consumer
*** `.35`: SOMDS Medical Alert Provider
*** &vellip;
*** `.40`: SOMDS participant
*** `.41`: SOMDS provider
*** &vellip;


** `.4`: parent OID for all *transactions* defined in SDPi
*** `.23`: Announce network presence
*** `.24`: Discover network topology
*** &vellip;

** `.8`: parent OID for all *content modules* defined in SDPi
*** `.1`: IEEE 11073-10207 BICEPS content modules
*** `11`: Device: infusion pump
*** &vellip;

** `.9`: parent OID for all *use cases* defined in SDPi
*** `.1`: Synchronized time across devices
**** `.1`: Device is connected to the MD LAN network with a time source service
**** `.2`: Device is connected to the MD LAN network and a user wants to change the device’s time
**** &vellip;
*** &vellip;

** `.10`: parent OID for all *requirements* defined in SDPi and its profiles 
*** `.1`: R0001
*** `.2`: R0002
*** &vellip;

** `.11`: parent OID for all *profile actor options* defined in SDPi profiles.
*** `1`: managed discovery option
*** `2`: gateway export direction option
*** &vellip;


// Fix: 1:A.4.2.1 Assigning Unique Identifiers for requirement oids (they aren't in profiles
// and aren't versioned)

// Do we need versions for profiles? Perhaps they could go in a .0.version arc so adding a version doesn't
// require updating all actors etc?




Arcs are assigned, and used by this technical framework supplement, under the _IHE DEV parent_ OID for:

* device integration profiles (`.2`),
* actors (`.3`),
* transactions (`.4`),
* content modules (`.8`),
* use cases (`.9`),
* requirements (`.10`), and
* profile actor options ('.11').

Appending one of these arcs to the _IHE DEV parent_ creates a new OID root. Arcs beneath those OIDs name corresponding items within
this technical framework supplement, as identified in the tables below. 

Generally, the meaning of OIDs should not change once assigned. For example, `1.3.6.1.4.1.19376.1.6.3.40` will always refer to a
SOMDS participant. This OID will never be assigned another meaning even if, for some reason, a SOMDS participant is no longer 
relevant to the supplement. For this reason, some items in this technical framework supplement included versioned OIDs in addition
to the base OID. This provides a mechanism to precisely reference both a specific version of, for example, a transaction, and
the general purpose of a transaction. 

[#vol3_appendix_c_oid_management]
=== OID management

The generation and management of the top level OID within the DEV domain is coordinated by Technical Committee Co-chairs. The top level OID is `1.3.6.1.4.1.19376.1.6.2.10`. The SDPi working group is responsible for managing and assigning OIDs under the top level OID. OIDs are assigned and managed within the SDPi ASCIIDoc source, with any changes reviewed in pull-requests. The SDPi working group has defined the following child arcs to establish a logical structure within the SDPi top-level OID: 

[%header]
|===
| Specification         | Arc   | Description
| Conformity version    | `.0`  | Parent OID to identify a version of the SDPi specification a participant conforms to.
| Namespaces            | `.1`  | Parent OID for namespaces defined in the SDPi specification.
| Profiles              | `.2`  | Parent OID for all SDPi profiles.
| Actors                | `.3`  | Parent OID for all actors defined in SDPi profiles.
| Transactions          | `.4`  | Parent OID for all transactions defined in the SDPi specification.
| Content modules       | `.8`  | Parent OID for all content modules defined in the SDPi specification.
| Use cases             | `.9`  | Parent OID for general use cases defined in the SDPi specification.
| Requirements          | `.10` | Parent OID for all requirements defined in the SDPi specification, including profiles, use cases, etc.
| Profile actor options | `.11` | Parent OID for all profile actor options defined in SDPi profiles.
|===

Generally, only the conformity version and namespace OIDs may be versioned. Profiles, actors, transactions, content modules, use cases, requirements and profile actor options are not versioned. 

[#vol3_appendix_c_oid_top]
=== Top level SDPi Oid

The top level OID, assigned by the DEV domain Technical Committee Co-chairs is `1.3.6.1.4.1.19376.1.6.2.10`. 

[#vol3_appendix_c_oid_conformity]
=== Conformity version

The conformity version identifies a version of the SDPi specification that a RefActor:somds_participant[] claims to be conformant to. A conformity version OID has the following hierarchy:

* `1.3.6.1.4.1.19376.1.6.2.10.0`: parent OID for SDPi *conformity versioning*
** `.<major-version>`: major version 2, for this version of the SDPi specification. 
*** `.<minor-version>`: minor version 2, for this version of the SDPi specification.
**** `.<revision>`: revision 1, for this version of the SDPi specification.

The version shall be interpreted by two RefActor:somds_participant[]s as:

* participants with the same major and minor version are guaranteed by SDPi conformity testing to be interoperable.
* participants with a different major version may not be compatible. For example, a new major version may define new transactions, requirements or use cases that break interoperability. 
* a participant with the same major version and higher minor version than another participant is guaranteed by SDPi conformity testing to be interoperable for the set of features defined in the lowest common minor version. 
* changes that only affect the revision number do not affect interoperability of participants.

[#vol3_appendix_c_oid_profiles]
=== Device integration profiles

The profile specifications defined in this specification are assigned OIDs from the `.*2*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. Profile arcs are generally assigned sequentially using the `oid-arcs` attribute on the ASCIIDoc section that defines the profile. 

sdpi_oid_table::[arc="profiles"]


[#vol3_appendix_c_oid_options]
=== Profile actor options

Options for profiles / actors that are defined in this specification are assigned OIDs from the `.*11*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. Profile actor option arcs are generally assigned sequentially using the `oid-arcs` attribute on the ASCIIDoc section that defines the profile actor option. 

sdpi_oid_table::[arc="profile-actor-options"]

[#vol3_appendix_c_oid_actors]
=== Actors

The actor definitions in this supplement are assigned OIDs from the `.*3*` arc under under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. 
Actor arcs are generally assigned sequentially using the `oid-arcs` attribute on the ASCIIDoc section that defines the actor. 

sdpi_oid_table::[arc="actors"]

[#vol3_appendix_c_oid_transactions]
=== Transactions

The transactions defined in this supplement are assigned OIDs from the `.*4*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. 
Transaction arcs are automatically assigned when the document is processed by combining the transaction number with the parent OID for transactions. 

sdpi_oid_table::[arc="transactions"]

[#vol3_appendix_c_oid_content_modules]
=== Content modules

Content modules defined in this supplement are assigned OIDs from the `.*8*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. 
Content module arcs are generally assigned sequentially using the `oid-arcs` attribute on the ASCIIDoc section that defines the content module. 

sdpi_oid_table::[arc="content-modules"]

[#vol3_appendix_c_oid_use_cases]
=== Device Point-of-care interoperability use cases

<<vol1_appendix_c_dpi_use_cases, Device Point-of-care interoperability use cases>> defined in this supplement are assigned OIDs from the `.*9*` arc under <<vol3_appendix_c_oid_top,Top level SDPi OID>>. 

* Each use-case feature is sequentially, in the order it is added to the specification, assigned an arc under the `.9` parent OID using the `oid-arcs` attribute on the ASCIIDoc section that defines the feature. This OID identifies the use-case feature and is the parent for its scenarios. 
* Each scenario in a use-case feature is sequentially, in the order it is added to the specification, assigned an arc under the corresponding feature using the `oid-arcs` attribute on the ASCIIDoc section that defines the scenario.


sdpi_oid_table::[arc="use-cases"]

[#vol3_appendix_c_oid_requirements]
=== Requirements

All requirements defined in this specification are assigned OIDs from the `.*10*` arc under <<vol3_appendix_c_oid_top,Top level SDPi OID>>.  See <<vol1_clause_sdpi_requirement_assigning_unique_identifiers>> for more information on selecting requirement numbers. Requirement OIDs are automatically assigned when the document is processed by combining the requirement number with the parent OID for requirements.

sdpi_oid_table::[arc="requirements"]


