[#vol3, sdpi_volume_caption=3]
= Volume 3 -- Content Modules

[#clause-content-modules]

// == Content Modules

// 8
[#vol3_clause_content_modules,sdpi_offset=8]
== DEV Semantic Content Modules

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi Supplement Version Note*: The organization of this Volume 3 supplement factors in two major changes:

. IHE Supplement template (2020), with content mapped from the <<ref_ihe_pcd_tf_3_2019>> specification;

. Addition of <<acronym_biceps>> content to a volume that is organized according to the "classic" <<ref_ieee_11073_10201_2004>> domain information model (DIM).

For this version of the supplement, content from the 2019 version that was in sections 3 and 7 has now been collected into a single section 8.

In order to clearly identify the supplement content that is related to <<acronym_biceps>>, specific sections with <<acronym_biceps>> in the title have been added.
Although this results in a fairly clean supplement document, the flow of the outline is at times non sequitur.
To address that problem -- again arising from the original volume organization never contemplating additional semantic content standards alignment beyond the Classic DIM -- subsections that are aligned with the Classic DIM have been organized in a subsection with that scope.
That new content which is based on <<acronym_biceps>> is also contained within a similarly labeled set of subsections -- both at the same outline level.

For the existing TF-3 content in the <<ref_ihe_pcd_tf_3_2019>>, especially section 3, though this supplement includes editor guidance for which sections are mapped where in the updated outline, the actual content is a mix of general device informatics topics and details that are based on the "classic" <<ref_ieee_11073_10201_2004>> DIM.

*_Updating the existing IHE DEV Technical Framework content will be either deferred to a later version of this SDPi supplement or will be accomplished through a specific Change Proposal (CP) to the published IHE DEV TF-3._*

Additionally, for this version of SDPi 1.0, it isn't clear how best to address a smilar division of the device specialization sections (e.g., infusion pump or ventilator).
Version note boxes (like this one) have therefore been added to the specializations section and a single BICEPS subsection has been added.
Subsequent versions of the specification may address this more comprehensively.

*REVIEWER QUESTION*:  Please consider not only the <<acronym_biceps>>-related updates but also the changes to the general organization and provide guidance as to whether this TF-3 is better organized for clarity and future extensions, or if a different approach should be taken.

|===

// 8.1
[sdpi_offset=1]
=== Overview of device semantic content

[%noheader]
[cols="1"]
|===
| Move IHE PCD 2019 TF-3 section 3 (text immediately after the section header) to this SDPi 1.0 TF-3 section 8.1
|===

////
#TODO:  Update the IHE PCD 2019 TF-3 section 3 content to be model/format independent#
////

// 8.2
=== General device content considerations

[%noheader]
[cols="1"]
|===
| Move IHE PCD 2019 TF-3 sections 3.1 to this SDPi 1.0 TF-3 section 8.2
|===

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi Supplement Version Note*: The content in the IHE PCD 2019 TF-3 3.1 section will need to be edited to be agnostic to the underlying protocol, with protocol specifics being relegated to subsections in <<vol3_clause_protocol_specific_content_module_considerations>> below.
|===


// 8.3
[#vol3_clause_protocol_specific_content_module_considerations]
===  Protocol-Specific Content Module Considerations

// 8.3.1
[#vol3_clause_ieee_11073_10201_classic_dim_content_modules]
==== IEEE 11073-10201 Classic DIM Content Modules

[%noheader]
[cols="1"]
|===
| Move IHE PCD 2019 TF-3 sections 3.2 to 3.7 to this SDPi 1.0 TF-3 section 8.3.1.2 TO 8.3.1..7

A new 8.3.1.1 section should be added to the Classic DIM content section that addresses basic reporting.
This content would be extracted from the existing (2019) section 3.1, where that content is specific to the Classi DIM (see related note above).
|===

// 8.3.2
[#vol3_clause_sdc_biceps_semantic_content]
==== IEEE 11073-10207 BICEPS Content Modules

include::tf3-ch-8.3.2-biceps-content.adoc[]

include::mdib-report-retrofit/tf3-ch-8.3.2.9-mdib-report-retrofit.adoc[]


// 8.3.3
==== RESERVED

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi Supplement Version Note*: This is a place holder section for content modules related to the Personal Health Device (PHD) semantics defined in the IEEE 11073-10206 and 11073-20601 standards.  Though there are no PHD requirements in this supplement, there are PHD profiles that may be integrated into the IHE DEV Technical Framework, and as a result may add content to this section.
|===

// 8.4 8.5 8.6 RESERVED
=== RESERVED

[%noheader]
[cols="1"]
|===
| Move IHE PCD 2019 TF-3 section 4 Reserved to this SDPi 1.0 TF-3 section 8.4
|===

=== RESERVED

[%noheader]
[cols="1"]
|===
| Move IHE PCD 2019 TF-3 section 5 Reserved to this SDPi 1.0 TF-3 section 8.5
|===

=== RESERVED

[%noheader]
[cols="1"]
|===
| Move IHE PCD 2019 TF-3 section 6 Reserved to this SDPi 1.0 TF-3 section 8.6
|===

// 8.7
[#vol3_clause_device_specialization_content_modules,sdpi_offset=7]
=== Device specialization content modules

include::tf3-ch-8.7.1-infusion-pump.adoc[]

include::tf3-ch-8.7.2-ventilator.adoc[]

include::tf3-ch-8.7.3-physiologic-monitor.adoc[]

include::tf3-ch-8.7.4-surgical.adoc[]

include::tf3-ch-a-xml-schemas.adoc[]