[appendix#vol3_appendix_c_oids,sdpi_offset=C]
== OID identifiers

Object identifiers, or OIDs, are globally unique numeric identifiers used to name something in a formal, unambiguous way. 
They are typically formatted as dotted number strings (`1.3.6.1.4.1.19376.1.6`, for example). Each number (or _arc_) is a node in a
hierarchical, tree-structured, namespace. The top of the tree, and first arc in the sequence, is managed by standards
bodies who delegate responsibility for distinct branches in the hierarchy. 

IHE DEV is responsible for managing arcs from the _IHE DEV parent_ OID `1.3.6.1.4.1.19376.1.6`.
See https://wiki.ihe.net/index.php/PCD_OID_Management[PCD OID Management]. 
They have designated `{SDPi-parent-oid}` as the parent OID for a hierarchy of object identifiers for this
service-oriented device point-of-care interoperability (SDPi) specification. 

This supplement is responsible for the hierarchy underneath the `{SDPi-parent-oid}` SDPi top level oid. 

// Fix: 1:A.4.2.1 Assigning Unique Identifiers for requirement oids (they aren't in profiles
// and aren't versioned)


Generally, the meaning of OIDs should not change once assigned. For example, `{SDPi-parent-oid}.3.40` will always refer to a
RefActor:somds_participant[]. This OID will never be assigned another meaning even if, for some reason, a SOMDS participant is no longer 
relevant to the specification. 

[#vol3_appendix_c_oid_management]
=== OID management

The SDPi working group is responsible for managing and assigning OIDs under the <<vol3_appendix_c_oid_top,top level SDPi OID>>.

OIDs are assigned and managed within the SDPi ASCIIDoc source, with any changes reviewed in pull-requests. The SDPi working group has defined the following child arcs to establish a logical structure under the <<vol3_appendix_c_oid_top,top level SDPi OID>>: 


[cols="2,1,4",options="autowidth, header"]
|===
| Specification         | Arc   | Description
| <<vol3_appendix_c_oid_conformity,Conformity version>>   | `.0`  | Parent OID to identify a version of the SDPi specification a participant conforms to.
| <<vol3_appendix_c_oid_namespaces,Namespaces and URIs>>  | `.1`  | Parent OID for namespaces and URIs defined in the SDPi specification.
| <<vol3_appendix_c_oid_profiles,Profiles>>               | `.2`  | Parent OID for all SDPi profiles.
| <<vol3_appendix_c_oid_actors,Actors>>                   | `.3`  | Parent OID for all actors defined in SDPi profiles.
| <<vol3_appendix_c_oid_transactions,Transactions>>       | `.4`  | Parent OID for all transactions defined in the SDPi specification.
| <<vol3_appendix_c_oid_content_modules,Content modules>> | `.8`  | Parent OID for all content modules defined in the SDPi specification.
| <<vol3_appendix_c_oid_use_cases,Use cases>>             | `.9`  | Parent OID for general use cases defined in the SDPi specification.
| <<vol3_appendix_c_oid_requirements,Requirements>>       | `.10` | Parent OID for all requirements defined in the SDPi specification, including profiles, use cases, etc.
| <<vol3_appendix_c_oid_options,Profile actor options>>   | `.11` | Parent OID for all profile actor options defined in SDPi profiles.
|===

Generally, only the conformity version and namespace OIDs are versioned. Profiles, actors, transactions, content modules, use cases, requirements and profile actor options are not versioned. 

[#vol3_appendix_c_oid_top]
=== Top level SDPi Oid

The top level OID for the SDPi specification, assigned by the DEV domain Technical Committee Co-chairs, is `{SDPi-parent-oid}`. 

[#vol3_appendix_c_oid_conformity]
=== Conformity version

The conformity version identifies a version of the SDPi specification that a RefActor:somds_participant[] may claim conformity to. A conformity version OID has the following hierarchy:

* `1.3.6.1.4.1.19376.1.6.2.10.0`: parent OID for SDPi *conformity versioning*
** `.<major-version>`: major version, {sdpi_version_major} for this version of the SDPi specification. 
*** `.<minor-version>`: minor version, {sdpi_version_minor} for this version of the SDPi specification.
**** `.<revision>`: revision, {sdpi_version_revision} for this version of the SDPi specification.

The version shall be interpreted by two RefActor:somds_participant[]s as:

* participants with the same major and minor version are guaranteed by SDPi conformity testing to be interoperable.
* participants with a different major version may not be compatible. For example, a new major version may define new transactions, requirements or use cases that break interoperability. 
* a participant with the same major version and higher minor version than another participant is guaranteed by SDPi conformity testing to be interoperable for the set of features defined in the lowest common minor version. 
* changes that only affect the revision number do not affect interoperability of participants.

[#vol3_appendix_c_oid_namespaces]
=== Namespaces and URIs

<<vol0_xml_namespaces,Namespaces>> and URIs defined in this specification are assigned OIDs from the `.*1*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. OIDs within the namespace parent OID `{sdpi-parent-oid}.1` are used for URIs (such as custom filter dialects), XSD schema and WSDL namespaces including:

* <<vol3_appendix_b_biceps_extension_namespace,Extensions to the BICEPS participant and message model>>.
* <<vol1_clause_sdpi_p_option_managed_discovery,Managed discovery profile actor option>>.

Generally, new namespaces and URIs for profile actor options are grouped into a hierarchy sharing a parent OID. For example, 

* `{sdpi-parent-oid}.1.2` is the parent oid for the <<vol1_clause_sdpi_p_option_managed_discovery,managed discovery option>>,
** `.1`: is the URI for the subscription filter dialect
** `.2`: is the target namespace URI for the proxy service web-service description language (WSDL).

OIDs used for namespaces may be versioned. For example:

* `{sdpi-parent-oid}.1.1` is the OID identifying SDPi extensions to the BICEPS participant and message model schema
** `.1`: is version 1 of the extension schema.




// Existing ones:
// 1.3.6.1.4.1.19376.1.6.2.10.1.1: extensions to the participant and message model, §Appendix 3:B 
//   * .1 Major version 1 for participant and message model extensions
// 1.3.6.1.4.1.19376.1.6.2.10.1.2: discovery proxy, §2:A.3.1 Utilized OIDs
//   * .1: subscription filter dialect
//   * .2: target namespace for discovery proxy service WSDL.


[#vol3_appendix_c_oid_profiles]
=== Device integration profiles

The profile specifications defined in this specification are assigned OIDs from the `.*2*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. Profile arcs are generally assigned sequentially using the `oid-arcs` attribute on the ASCIIDoc section that defines the profile. 

sdpi_oid_table::[arc="profiles"]


[#vol3_appendix_c_oid_options]
=== Profile actor options

Options for profiles / actors that are defined in this specification are assigned OIDs from the `.*11*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. Profile actor option arcs are generally assigned sequentially using the `oid-arcs` attribute on the ASCIIDoc section that defines the profile actor option. 

sdpi_oid_table::[arc="profile-actor-options"]

[#vol3_appendix_c_oid_actors]
=== Actors

The actor definitions in this supplement are assigned OIDs from the `.*3*` arc under under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. 
Actor arcs are generally assigned sequentially using the `oid-arcs` attribute on the ASCIIDoc section that defines the actor. 

sdpi_oid_table::[arc="actors"]

[#vol3_appendix_c_oid_transactions]
=== Transactions

The transactions defined in this supplement are assigned OIDs from the `.*4*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. 
Transaction arcs are automatically assigned when the document is processed by combining the transaction number with the parent OID for transactions. 

sdpi_oid_table::[arc="transactions"]

[#vol3_appendix_c_oid_content_modules]
=== Content modules

Content modules defined in this supplement are assigned OIDs from the `.*8*` arc under the <<vol3_appendix_c_oid_top,Top level SDPi OID>>. 
Content module arcs are generally assigned sequentially using the `oid-arcs` attribute on the ASCIIDoc section that defines the content module. 

sdpi_oid_table::[arc="content-modules"]

[#vol3_appendix_c_oid_use_cases]
=== Device Point-of-care interoperability use cases

<<vol1_appendix_c_dpi_use_cases, Device Point-of-care interoperability use cases>> defined in this supplement are assigned OIDs from the `.*9*` arc under <<vol3_appendix_c_oid_top,Top level SDPi OID>>. 

* Each use-case feature is sequentially, in the order it is added to the specification, assigned an arc under the `.9` parent OID using the `oid-arcs` attribute on the ASCIIDoc section that defines the feature. This OID identifies the use-case feature and is the parent for its scenarios. 
* Each scenario in a use-case feature is sequentially, in the order it is added to the specification, assigned an arc under the corresponding feature using the `oid-arcs` attribute on the ASCIIDoc section that defines the scenario.


sdpi_oid_table::[arc="use-cases"]

[#vol3_appendix_c_oid_requirements]
=== Requirements

All requirements defined in this specification are assigned OIDs from the `.*10*` arc under <<vol3_appendix_c_oid_top,Top level SDPi OID>>.  See <<vol1_clause_sdpi_requirement_assigning_unique_identifiers>> for more information on selecting requirement numbers. Requirement OIDs are automatically assigned when the document is processed by combining the requirement number with the parent OID for requirements.

sdpi_oid_table::[arc="requirements"]


