[#vol3, sdpi_volume_caption=3]
= Volume 3 -- Content Modules

[#clause-content-modules]

// == Content Modules

// 8
[#vol3_clause_content_modules,sdpi_offset=8]
== DEV Semantic Content Modules

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{standard_note}*: Volume 3 of this Gemini SDPi standard provides for semantic content specifications that may be used across the profile specifications and transactions, especially for the <<vol1_spec_sdpi_p_actor_biceps_content_creator>> and <<vol1_spec_sdpi_p_actor_biceps_content_consumer>> transaction-non-specific actors.
This volume includes requirements and guidelines regarding nomenclature use, extensions to data models, "value lists" associated with specific device modalities / "specializations", etc.

What is unique for this Gemini SDPi standard, is that some of the normative content is currently only in the IHE DEV TF-3 document.
This begs the question of whether that content should only be referenced from this "standalone" specification, summarized in this specification and then referenced, or copied and adapted for this specification?
Note:  Requirements interoperability metadata is currently included ONLY in this Gemini standard, and as a result, if implementation testing and conformity assessment will include semantic content that leverages this metadata, and if some of those requirements are curently only in the IHE DEV TF specification, then they will need to be included in this standard with the appropriate labeling so as to ensure that they are part of the exported requirements data.

#REVIEWER QUESTIONS#:

. Only SDPi-specific semantic content has been included in this current "standalone" draft of the SDPi standard; however, to understand the broader device informatics context, additional content (possibly summarized from the IHE Devices Technical framework, Volume 3) may be necessary for understanding this SDPi content.
*_Please comment on what additional informational content (non-normative) should be added to this volume for clarity._*
. *_Should normative semantic content currently in the IHE DEV TF-3 document, be (a) Referenced by this specification only?  (b) Be replicated but adapted for this unique standard?  (c) ..._?*

|===

// 8.1
[sdpi_offset=1]
=== Overview of device semantic content

[%noheader]
[cols="1"]
|===
a| *{standard_note}*:  See IHE DEV 2024 TF-3 Section 3 (text immediately after the section header).
Ultimately, that content will be moved to this SDPi {gemini_standard_sdpi_revision_short} TF-3 Section 8.1
|===


// 8.2
=== General device content considerations

[%noheader]
[cols="1"]
|===
a| *{standard_note}*:  See IHE DEV 2024 TF-3 sections 3.1.
Ultimately, that content might be moved to this SDPi {gemini_standard_sdpi_revision_short} TF-3 Section 8.2
|===

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *{standard_note}*: The content in the IHE DEV 2024 TF-3 3.1 Section will need to be edited to be agnostic to the underlying protocol, with protocol specifics being relegated to subsections in <<vol3_clause_protocol_specific_content_module_considerations>> below.
|===


// 8.3
[#vol3_clause_protocol_specific_content_module_considerations]
===  Protocol-Specific Content Module Considerations

// 8.3.1
[#vol3_clause_ieee_11073_10201_classic_dim_content_modules]
==== IEEE 11073-10201 Classic DIM Content Modules

[%noheader]
[cols="1"]
|===
a| *{standard_note}*: See IHE DEV 2024 TF-3 sections 3.2 to 3.7 for the non-BICEPS content in this SDPi {gemini_standard_sdpi_revision_short} TF-3 Section 8.3.1.2 TO 8.3.1.7

A new 8.3.1.1 Section should be added to the Classic DIM content section that addresses basic reporting.
This content would be extracted from the existing (2024) Section 3.1, where that content is specific to the Classic DIM (see related note above).
|===

// 8.3.2
[#vol3_clause_sdc_biceps_semantic_content]
[role=content-module,content-module-id=biceps,oid-arcs=".1"]
==== IEEE 11073-10207 BICEPS Content Modules

include::tf3-ch-8.3.2-biceps-content.adoc[]

include::mdib-report-retrofit/tf3-ch-8.3.2.9-mdib-report-retrofit.adoc[]

include::tf3-ch-8.3.2.13-metric-display-precision.adoc[]


// 8.7
[#vol3_clause_device_specialization_content_modules,sdpi_offset=7]
=== Device specialization content modules

include::tf3-ch-8.7.1-infusion-pump.adoc[]

include::tf3-ch-8.7.2-ventilator.adoc[]

include::tf3-ch-8.7.3-physiologic-monitor.adoc[]

include::tf3-ch-8.7.4-surgical.adoc[]

include::tf3-ch-a-xml-schemas.adoc[]

include::tf3-ch-b-biceps-extension-namespace.adoc[]

include::tf3-ch-c-oid-tables.adoc[]

// ICS tables
include::tf3-ch-z-ics.adoc[]