[#vol3_clause_metric_display_precision]
===== Numeric Metric Display Precision

A <<actor_somds_provider>> conforming to the <<ref_ieee_11073_10701_2022>>, provides numeric metric data that fulfils the following requirements:

[quote, "<<ref_ieee_11073_10701_2022>> TR0800"]
For each METRIC of an SDC METRIC PROVIDER, for each pm:Range of the METRIC, while the minimum numerical distance between two values differs from the METRIC's @resolution, the SDC METRIC PROVIDER SHOULD provide this distance using pm:Range/@StepWidth.

[quote, "<<ref_ieee_11073_10701_2022>> TR0242"]
____
For each METRIC's @value or @samples that the MEDICAL DEVICE represented by an MDS of an SDC METRIC PROVIDER displays to a USER, while the precision of this display differs from the METRIC's @resolution or the active pm:Range has a @StepWidth that differs from the METRIC's @resolution, the SDC METRIC PROVIDER SHALL provide the display precision by attaching one mpkp:DisplayPrecision EXTENSION with @ext:MustUnderstand = false to the active pm:Range element.

NOTE—The mpkp:DisplayPrecision/@StepWidth implies the number of decimal places that are used on display.
For example, a value of 0.1 or 0.4 indicates that one decimal place is displayed whereas a value of 4 or 20 indicates that no decimal place is displayed.
____

This section defines clear rules how to interpret the requirements mentioned above.

====== What is an active range?

In <<acronym_biceps>>, a *pm:NumericMetricDescriptor*, *pm:RealTimeSampleArrayMetricDescriptor*, and *DistributionSampleArrayMetricDescriptor* can provide a list of *pm:TechnicalRange* elements of type *pm:Range*.

The same holds true for the corresponding state elements *pm:NumericMetricState*, *pm:RealTimeSampleArrayMetricState*, and *DistributionSampleArrayMetricState*.
In this case, the state elements can optionally define a list of *pm:PhysiologicalRange* elements of type *pm:Range*.

For a metric *@Value* or *@Samples* that falls in one of the *pm:TechnicalRange* or *pmPhysiologicalRange* elements, this *pm:Range* element is considered as the _active range_ for this particular metric *@Value* or *@Samples*.

If the metric *@Value* or *@Samples* falls in one of the *pm:TechnicalRange* elements and in one of *pm:PhysiologicalRange* elements at the same time, the *pm:PhysiologicalRange* element of the metric state will supersede the *pm:TechnicalRange* element of the descriptor and will become the _active range_ for this particular metric *@Value* or *@Samples*.

====== When must the *mpkp:DisplayPrecision* extension be defined?

As already defined in *TR0242* of the <<ref_ieee_11073_10701_2022>> standard, the <<actor_somds_provider>> is required to provide a *mpkp:DisplayPrecision* extension when the metric's *@Resolution* or @StepWidth of the _active range_ differs from the metric's display precision.

While *TR0800* is a SHOULD requirement, *TR0242* mandates the <<actor_somds_provider>> to provide a *mpkp:DisplayPrecision* extension when the metric's *@Resolution* differs from the display precision.
This forces the <<actor_somds_provider>> to provide at least one  *pm:TechnicalRange* or *pm:PhysiologicalRange* element with the appropriate *mpkp:DisplayPrecision* extension, since the extension can only be applied on *pm:Range* elements.

In this case, the *@StepWidth* of the *pm:Range* element is the same as the metric's *@Resolution* in order to preserve the resolution which would be superseded by a different *pm:Range/@StepWidth* otherwise.

.Ventilator Minute Volume Parameter Representation
====
A ventilator measures the *Minute Volume (MV)* in *L/min* with a resolution of one decimal place, but dependent on the value, the number is either displayed with no or one decimal place.
The <<actor_somds_provider>> defines the following in the *pm:NumericMetricDescriptor* of the *MV* metric:

* *@Resolution* = "0.1"
* *pm:TechnicalRange[0]/@Upper* = "100.0"
* *pm:TechnicalRange[0]/@Lower* = "10.0"
* *pm:TechnicalRange[0]/@StepWidth* = "0.1"
* *pm:TechnicalRange[0]/ext:Extension/mpkp:DisplayPrecision/@StepWidth* = "1"
* *pm:TechnicalRange[1]/@Upper* = "9.9"
* *pm:TechnicalRange[1]/@Lower* = "0.0"
* *pm:TechnicalRange[1]/@StepWidth* = "0.1"

The first range is defined from *10.0 L/min* to  *100.0 L/min*.
The measurement precision stays the same (*@Resolution* and *@StepWidth* are identical).
However, the <<actor_somds_provider>> indicates to the <<actor_somds_consumer>> that the *MV* parameter value needs to be displayed with no decimal places (*mpkp:DisplayPrecision/@StepWidth* = "1").

The second range is defined from *9.9 L/min* to  *0.0 L/min*.
Since there is no specific display precision defined, the <<actor_somds_consumer>> knows that the *MV* parameter value needs to be displayed with one decimal places (*@StepWidth* = "0.1").

It would also be correct to omit the second range element, since the implied display precision equals the metric's *@Resolution* in this case.
====

====== Requirements

.R1015
[sdpi_requirement#r1015,sdpi_req_level=shall]
****
If the display precision differs from the metric's *@Resolution* for a specific metric's *@Value* or *@Samples* range where no *pm:TechnicalRange* or *pm:PhysiologicalRange* element is defined, the <<actor_somds_provider>> shall define a descriptor *pm:TechnicalRange* element that covers this metric's *@Value* or *@Samples* range, and where the *@StepWidth* equals the *@Resolution* and the *ext:Extension/mpkp:DisplayPrecision/@StepWidth* defines the display precision.

.Notes
[%collapsible]
====
NOTE: The <<actor_somds_provider>> could also define *pm:PhysiologicalRange* element in the metric state in lieu of *pm:TechnicalRange* element in the metric descriptor.
However, it is recommended to define the appropriate *pm:Range* element in the descriptor.
====
****

.R1016
[sdpi_requirement#r1016,sdpi_req_level=shall]
****
A <<actor_somds_consumer>> shall determine the _active range_ for the current metric's *@Value* or *@Samples* by the following priority order:

. The *pm:PhysiologicalRange* element of the metric state where the current metric's *@Value* or *@Samples* falls into.
. The *pm:TechnicalRange* element of the metric descriptor where the current metric's *@Value* or *@Samples* falls into.

****

.R1017
[sdpi_requirement#r1017,sdpi_req_level=shall]
****
A <<actor_somds_consumer>> shall determine the current display precision for a metric's *@Value* or *@Samples* by the following priority order:

1. *ext:Extension/mpkp:DisplayPrecision/@StepWidth* is defined for the _active range_
2. *pm:Range/@StepWidth* is defined for the _active range_
3. *@Resolution* if there is no _active range_ defined
****
