= Service-oriented Device Point-of-care Interoperability (SDPi) Technical Framework
:doctype: book
// CAUTION: do not change the xrefstyle attribute as otherwise numbering will be broken
:xrefstyle: short
:stylesdir: css
:!webfonts:
:!iconfont-remote:
:toc-title: Contents
:toc: left
:toclevels: 3
:multipage-level: 2
:sectnums:
:icons: font
:icon-set: fas
:imagesoutdir: images/
:imagesdir: images/
:docinfo: shared
:source-highlighter: highlight.js
:highlightjsdir: js/highlight

// Set the document attribute to automatically generate
// actor transactions table from semantic markup. Unset
// to use manual tables. 
// https://docs.asciidoctor.org/asciidoc/latest/attributes/unset-attributes/
:markup-actor-transactions-table:

:sdpi_milestone_publication: SDPi 2.3 Publication
:sdpi_milestone_review: SDPi 2.3 Review

:sdpi_version_major: 2
:sdpi_version_minor: 5
:sdpi_version_revision: 0
// STANDALONE SDPi:  QUESTION:  Do we rework these to gemini_standard
:ihe_standard_sdpi_revision: {sdpi_version_major}.{sdpi_version_minor}.{sdpi_version_revision}
:gemini_standard_sdpi_revision_short: {sdpi_version_major}.{sdpi_version_minor}
:ihe_standard_sdpi_revision_date: {localdatetime}
:ihe_standard_sdpi_revision_label: Standard for Trial Use
:ihe_standard_sdpi_publication_month: December 19, 2025
:ihe_standard_sdpi_public_comment_submission_deadline: N/A

// Oid, assigned by IHE-DEV, for the SDPi specification
// https://wiki.ihe.net/index.php/PCD_OID_Management
:sdpi-parent-oid: 1.3.6.1.4.1.19376.1.6.2.10

:standard_note: SDPi {gemini_standard_sdpi_revision_short} Standard Note

{empty} +
ifeval::["{backend}" == "html5"]
++++
<script>
    $('body').prepend('<div id="load-screen"><div style="margin-top: -64px">Menu is loading</div></div>');
    document.getElementsByClassName('sectlevel0')[0].style.visibility = "hidden";
</script>
++++

[subs=attributes]
++++
<div class="logos">
    <div>
        <img src="{imagesdir}hl7-intl-logo.svg"/>
        <img src="{imagesdir}ihe-logo.svg"/>
    </div>
    <div><strong>A Joint HL7-IHE Gemini Device Interoperability Project</strong></div>
</div>
<p style="font-size: 2.75em; text-align: center"><strong>Gemini</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Technical Framework Profile Standard</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Service-oriented Device Point-of-care</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Interoperability (SDPi)</strong></p>

<p style="text-align: center">Revision {ihe_standard_sdpi_revision} &mdash; {ihe_standard_sdpi_revision_label}</p>

<p style="text-align: center"><strong>("Standalone" SDPi Standard -  For Review)</strong></p>
++++
endif::[]
{empty} +

[%noheader]
[cols="1,4"]
[frame=none,grid=none]
|===
| *Publication Date:*
| {ihe_standard_sdpi_publication_month}

| *Build Date:*
| {ihe_standard_sdpi_revision_date}

| *Author:*
| Gemini Medical Device Interoperability Program Team (Joint HL7 & IHE Devices Working Groups)

| *Issues / Questions:*
| Submit a _New issue_ at https://github.com/IHE/DEV.SDPi/issues[Gemini DEV.SDPi GitHub Issues]

|===

{empty} +

*Published versions of this standard are available from both IHE and HL7:*

* For HL7 publications:  Search for "SDPi" on the https://www.hl7.org/implement/standards/product_matrix.cfm[HL7 Standards-based Product Grid]

* For IHE publications: https://profiles.ihe.net/DEV/[*HERE*] for STU/Trial Implementation and Final Text versions and https://profiles.ihe.net/DEV/#1.2[*HERE*] for Public Comment versions.

ifeval::["{backend}" == "html5"]
//A PDF version of the specification is available upon request.
endif::[]

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *Gemini SDPi {gemini_standard_sdpi_revision_short} "Standalone" Standard -- Release & Drafting Notes*:

=== Release Note:
This version of the SDPi {gemini_standard_sdpi_revision_short} Standard for Trial Use (HL7 STU) / Trial Implementation (IHE TI) standard is the 3rd release in 2025, continuing the objective to provide three to four releases each year that include both _incremental_ updates (e.g., editorial "fixes"), ballot comment resolutions (e.g., from HL7 ballot cycles), and additional capability enhancements.

This Gemini SDPi {gemini_standard_sdpi_revision_short} release is the first time the specification has been separated into two separate documents:

. *sdpi-standard.html* -- contains all the normative content from the previous releases; however, the front matter is reorganized in alignment with other standards templates (e.g., Scope, Introduction / Overview, References, Acronyms, etc.).
It still maintains the IHE Technical Framework organizational elements (e.g., Volume 1 Integration Profiles, Volume 2 Transactions, etc.); however, elements that are solely intended for an IHE Technical Framework Supplement (e.g., directions for how to integrate a section into the IHE Devices Technical Framework - Final Text) are removed and only contained in the new supplement document
. *sdpi-supplement.html* -- contains the main outline of the standard document; however, all the normative content is referenced in the supplement to the appropriate location in the standard.
The supplement includes all the rubric information needed for ultimately integrating it into the IHE Devices Technical Framework.

For this release, key changes include:

1. Resolution of all HL7 MAY 2026 Ballot Comments
2. New History Service option with related transaction DEV-32
3. "Standalone" SDPi -- initial creation of two documents:  Gemini Standard + IHE Supplement
4. Support semantic markup for deprecating requirements, transactions, use-cases, profiles, content modules and actors
5. Updates related to the corrected SDC BICEPS standard corrigendum
6. Clarifications and corrections

All changes incorporated in a release are managed through Github Issues and reviewed Pull Requests.
For a list of those related to this release, see
//<<sdpi_release_issue_management>>
below.
For HL7 ballot comment resolution, links are made from HL7 ballot Jira tickets to IHE DEV.SDPi Github Issues that then enable tracking of the comment resolution implementation in a specific release.

NOTE: This standard also includes both normative and informative references to other specifications (see <<clause_references>>), some of which are finalized and published and others that are either being developed or in revision.
For example, the IEEE 11073-10702 PKP standard is in mature development stage; however, some requirements from that pre-standard may be included (non-normatively) in this SDPi specification, providing a pathway to early experience and validation.
When a referenced specification is used that is in development or revision, a note will be provided in the <<clause_references>> clearly indicating its status.

It is recognized that this release is a work-in-progress that will continue to subsequent versions.
These known limitations and forward-looking content include:

. Releases along with the planned capability additions are managed in the project's https://github.com/IHE/DEV.SDPi/milestones[DEV.SDPi milestones];
. This standard includes four SDPi Profiles, though the typical IHE supplement is organized for a single profile; as a result, some adjustments have been made, especially in the supplement overview section where there is a general SDPi overview and then basic overviews for each of the Profiles; challenging areas include profile "options" where there are FOUR sections vs. one; it is a work in progress and feedback is appreciated, especially to enhance clarity;
. *Open / Closed Issues tables* -- starting with SDPi 1.1 and subsequent, the approach for the IHE open / closed issues section was transitioned to utilize https://github.com/IHE/DEV.SDPi/issues[Github Issues] that are related to specific releases; each release updates the changelog file, detailing what is Added, Changed or Removed;
. *Requirements boxes* (e.g., "R1234") are included especially in TF-2, with some also part of TF-1 and TF-3; this is an initial approach that *_will be significantly expanded in future versions of the standard_*; documentation is provided in <<vol1_clause_sdpi_requirements_modeling_integration>>, including discussion related to how it will be expanded in future versions of the standard;
. *_<<term_safe_effective_secure>> Sections_* (see <<vol1_clause_appendix_a_ses_considerations_section_template>>) are included in the specification; however, their use and content will be significantly extended in future versions;
. This standard is currently rendered as a *"long form"* document -- one single HTML file; however, in subsequent versions the intent is to consider a multi-page / file HTML rendering + addition of a tabbed menu for navigating the sections of the standard;
. *{standard_note}* boxes are provided throughout the document to help guide reviewers and implementers.
This release of the standard+supplement documents is still in process, as the "Drafting Note" below indicates!
The outline of this standard, though, will be as follows:

//  *****************************************************************

. *Overview*
[none]
.. *Scope*
.. *Purpose*
[none]
.. (content from current TF-1:2.3.1.1 and similar)
.. (Copyright and other related content from supplement)
. *Introduction & Overview*
[none]
.. *_Gemini Technical Framework Profile Standard_*
[none]
... (define what a Gemini TF Profile Standard ... is!)
... (organization & conventions - section numbering, ...)
... (What & why AsciiDoc)
.. *_SDPi Overview_*
[none]
... (refactor content from TF-1:2 and elsewhere)
... (Use Cases?  Keep TF-1C or refactor here?)
... Summary of SDPi Actors & Transactions
. *Terms, Definitions & Acronyms*
[none]
.. (content from TF-0, Forward declarations, ... )
. *References*
[none]
.. (Content from TF-1B)
. ...
. [.line-through]#*Volume 1 Integration Profiles*#
. [.line-through]#*Volume 2 Transactions*#
. [.line-through]#*Volume 3 Content Modules*#


=== "Standalone" SDPi Drafting Note:

Editorial Task List (prioritized) for this Supplement:

. [.line-through]#Title Page - Update & review#
.. [.line-through]#Change Contact from DEV@IHE.NET to IHE SDPi GitHub Issues link#
. [.line-through]#Find and update all uses of "supplement" throughout current document#
.. [.line-through]#In labels used for referencing#
.. [.line-through]#In standard note sections#
.. [.line-through]#... ?#
. Create common sdpi-version.adoc that can be shared between the two documents
..  Also refactor gemini_standard_ and ihe_supplement_ to common labels
..  Also refactor standard_clause_ to clause_
. Refactor front matter not IHE TF based, but for a standalone document:
.. [.line-through]#Remove TF-0 content (supplement only)#
.. Introduction: Gemini, Gemini TF Profile Standard, SDPi in particular;
... Include Unique Features of TF Profile Standard (incl. embedded requirements, ... )
.. Refactor any IHE TF template content to be "standalone" where appropriate
.. Update section 2 overview of SDPi to a simple overview
.. Add Normative References?  or Definitions section? - reference to Appendix B
.. Refactor forward references content from early in document to a more "permanent" location!
. Move all SUPPLEMENT INSTRUCTIONS from this document to the supplement - "Standard Note" ...
. Add Standard release punch-list that includes updating Supplement content to keep in sync
. ...

|===

include::front-matter/forward.adoc[]

include::front-matter/overview.adoc[]

include::front-matter/terms-definitions.adoc[]

include::front-matter/references.adoc[]

// = Volume 1 -- Profiles

include::volume1/tf1-main.adoc[]

// = Volume 2 -- Transactions

include::volume2/tf2-main.adoc[]

// = Volume 3 -- Content Modules

include::volume3/tf3-main.adoc[]

include::conformance/conformance.adoc[]