= Service-oriented Device Point-of-care Interoperability (SDPi) Technical Framework
:doctype: book
// CAUTION: do not change the xrefstyle attribute as otherwise numbering will be broken
:xrefstyle: short
:stylesdir: css
:!webfonts:
:!iconfont-remote:
:toc-title: Contents
:toc: left
:toclevels: 3
:multipage-level: 2
:sectnums:
:icons: font
:icon-set: fas
:imagesoutdir: images/
:imagesdir: images/
:docinfo: shared
:source-highlighter: highlight.js
:highlightjsdir: js/highlight

// Set the document attribute to automatically generate
// actor transactions table from semantic markup. Unset
// to use manual tables. 
// https://docs.asciidoctor.org/asciidoc/latest/attributes/unset-attributes/
:markup-actor-transactions-table:

:sdpi_milestone_publication: SDPi 2.3 Publication
:sdpi_milestone_review: SDPi 2.3 Review

:sdpi_version_major: 2
:sdpi_version_minor: 4
:sdpi_version_revision: 0
// STANDALONE SDPi:  QUESTION:  Do we rework these to gemini_standard
:ihe_standard_sdpi_revision: {sdpi_version_major}.{sdpi_version_minor}.{sdpi_version_revision}
:ihe_standard_sdpi_revision_short: {sdpi_version_major}.{sdpi_version_minor}
:ihe_standard_sdpi_revision_date: {localdatetime}
:ihe_standard_sdpi_revision_label: Standard for Trial Use
:ihe_standard_sdpi_publication_month: December 19, 2025
:ihe_standard_sdpi_public_comment_submission_deadline: N/A

// Oid, assigned by IHE-DEV, for the SDPi specification
// https://wiki.ihe.net/index.php/PCD_OID_Management
:sdpi-parent-oid: 1.3.6.1.4.1.19376.1.6.2.10

{empty} +
ifeval::["{backend}" == "html5"]
++++
<script>
    $('body').prepend('<div id="load-screen"><div style="margin-top: -64px">Menu is loading</div></div>');
    document.getElementsByClassName('sectlevel0')[0].style.visibility = "hidden";
</script>
++++

[subs=attributes]
++++
<div class="logos">
    <div>
        <img src="{imagesdir}hl7-intl-logo.svg"/>
        <img src="{imagesdir}ihe-logo.svg"/>
    </div>
    <div><strong>A Joint HL7-IHE Gemini Device Interoperability Project</strong></div>
</div>
<p style="font-size: 2.75em; text-align: center"><strong>Gemini</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Technical Framework Profile Standard</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Service-oriented Device Point-of-care</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Interoperability (SDPi)</strong></p>

<p style="text-align: center">Revision {ihe_standard_sdpi_revision} &mdash; {ihe_standard_sdpi_revision_label}</p>

<p style="text-align: center"><strong>("Standalone" SDPi Standard -  For Review)</strong></p>
++++
endif::[]
{empty} +

[%noheader]
[cols="1,4"]
[frame=none,grid=none]
|===
| *Publication Date:*
| {ihe_standard_sdpi_publication_month}

| *Build Date:*
| {ihe_standard_sdpi_revision_date}

| *Author:*
| Gemini Medical Device Interoperability Program Team (Joint HL7 & IHE Devices Working Groups)

| *Issues / Questions:*
| Submit a _New issue_ at https://github.com/IHE/DEV.SDPi/issues[Gemini DEV.SDPi GitHub Issues]

*Standalone SDPi:*  _Should this email contact be included?  If so, what address(es)? One for IHE and one for HL7?_
|===

{empty} +

*Published versions of this standard are available from both IHE and HL7:*

* For HL7 publications:  Search for "SDPi" on the https://www.hl7.org/implement/standards/product_matrix.cfm[HL7 Standards-based Product Grid]

* For IHE publications: https://profiles.ihe.net/DEV/[*HERE*] for STU/Trial Implementation and Final Text versions and https://profiles.ihe.net/DEV/#1.2[*HERE*] for Public Comment versions.

ifeval::["{backend}" == "html5"]
//A PDF version of the specification is available upon request.
endif::[]

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi "Standalone" Standard -- Release & Drafting Notes*:

=== Release Note:
This sdpi-standard document is in the process of being refactored into a "standalone" version of the SDPi standard.
This release of the document represents an initial separation and reorganization of the content found in previous releases into two separate documents:

. *sdpi-standard.html* -- contains all the normative content from the previous releases; however, the front matter is reorganized in alignment with other standards templates (e.g., Scope, Introduction / Overview, References, Acronyms, etc.).
It still maintains the IHE Technical Framework organizational elements (e.g., Volume 1 Integration Profiles, Volume 2 Transactions, etc.); however, elements that are solely intended for an IHE Technical Framework Supplement (e.g., directions for how to integrate a section into the IHE Devices Technical Framework - Final Text) are removed and only contained in the new supplement document
. *sdpi-supplement.html* -- contains the main outline of the standard document; however, all the normative content is referenced in the supplement to the appropriate location in the standard.
The supplement includes all the rubric information needed for ultimately integrating it into the IHE Devices Technical Framework.

This releasse of the standard+supplement documents is still in process, as the "Drafting Note" below indicates!
The outline of this standard, though, will be as follows:

[none]
. *Scope*
[none]
.. (content from current TF-1:2.3.1.1 and similar)
. *Introduction & Overview*
[none]
.. *_Gemini Technical Framework Profile Standard_*
[none]
... (define what a Gemini TF Profile Standard ... is!)
... (organization & conventions)
.. *_SDPi Overview_*
[none]
... (refactor content from TF-1:2 and elsewhere)
... (Use Cases?  Keep TF-1C or refactor here?)
. *Terms, Definitions & Acronyms*
[none]
.. (content from TF-0, Forward declarations, ... )
. *References*
[none]
.. (Content from TF-1B)
. ...
. *Volume 1 Integration Profiles*
. *Volume 2 Transactions*
. *Volume 3 Content Modules*


=== Drafting Note:

Editorial Task List (prioritized) for this Supplement:

. [.line-through]#Title Page - Update & review#
.. [.line-through]#Change Contact from DEV@IHE.NET to IHE SDPi GitHub Issues link#
. [.line-through]#Find and update all uses of "supplement" throughout current document#
.. [.line-through]#In labels used for referencing#
.. [.line-through]#In standard note sections#
.. [.line-through]#... ?#
. Refactor front matter not IHE TF based, but for a standalone document:
.. Remove TF-0 content (supplement only)
.. Introduction: Gemini, Gemini TF Profile Standard, SDPi in particular;
... Include Unique Features of TF Profile Standard (incl. embedded requirements, ... )
.. Refactor any IHE TF template stuff to be "standalone" where appropriate
.. Update section 2 overview of SDPi to a simple overview
.. Add Normative References?  or Definitions section? - reference to Appendix B
.. Refactor forward references stuff from early in document to a more "permanent" location!
. Move all SUPPLEMENT INSTRUCTIONS from this document to the supplement - "Standard Note" ...
. Add Standard release punch-list that includes updating Supplement content to keep in sync
. ...

|===


[#standard_clause_foreword,sdpi_offset=clear]
= Foreword

// Standalone TO DO ... this section

This Gemini standard is a joint development effort between Health Level Seven International (HL7) and Integrating the Healthcare Enterprise (IHE) devices working groups.
Its development and publication adheres to the consensus standards processes of both HL7, an ANSI accredited standards development organization, and IHE.
The title of this document, "Technical Framework *_Standard_*", reflects its unique status as a Gemini specification, utilizing the IHE Technical Framework organization and elements (e.g., integration profiles, actors, transactions, content modules), but processed as an HL7 specification that will be published as a "standalone" standard and will persist even when its status transitions to normative standard (HL7) or Final Text (IHE).

To facilitate integration with the companion IHE Devices Technical Framework (final text) specification, a companion to this standard will be created for each edition:  SDPi "Technical Framework Profile Standard", which will be organized according to IHE style guidelines, but it will be in major section outline only, with each section including a note indicating where the content is located in the published Gemini Technical Framework ("standalone") Standard document.
Given its alignment with the companion IHE specification, some section numbers are skipped in this document to facilitate its intended integration into the above-mentioned "standard".
Skipped section numbers are already present in the Devices Technical Framework and will not require changes due to the incorporation of the supplement once it transitions to normative standard / final text status.

Additionally, some content that may otherwise be only referenced by a "supplement" document and defined elsewhere in the existing technical framework, will be incorporated in this specification to ensure that it is internally cohesive and does not force the reader to unnecessarily consult other documents.

Publication as a Standard for *Trial* Use (HL7) or *Trial* Implementation (IHE) reflects the continuous cycle of development, balloting and publication of the specification, to address addition of new capabilities as well as identified safety, effectiveness and security issues and enhancements.
Product developers are encouraged to use the standard, recognizing the potential impact of this continuous development cycle and its status as a _"trial use"_ standard.


This supplement is published on {ihe_standard_sdpi_publication_month} for Trial Implementation and may be available for testing at subsequent IHE or HL7 testing events, such as an IHE Connectathon.
The standard may be amended based on the results of testing.
Following successful testing and implementation maturity, it will transition to a normative standard, and the companion IHE supplement will be incorporated into the Devices Technical Framework.
Comments are invited and can be submitted at https://www.ihe.net/DEV_Public_Comments/[Devices Public Comments] or by submitting a https://github.com/IHE/DEV.SDPi/issues/new/choose[GitHub Issue].

General information about IHE can be found at http://www.ihe.net/[IHE.net], and about HL7 can be found at https://www.hl7.org/index.cfm[HL7.org].

General information about the HL7 Devices Working Group can be found at https://www.hl7.org/Special/committees/healthcaredevices/index.cfm[HL7.org/healthcaredevices], and the IHE Devices domain can be found at https://www.ihe.net/ihe_domains/[IHE Domains].

Information about the organization of IHE Technical Frameworks and Supplements and the process used to create them can be found at https://www.ihe.net/resources/profiles/[Profiles] and https://www.ihe.net/about_ihe/ihe_process/[IHE Processes].

The current version of the IHE Devices Technical Framework can be found at https://profiles.ihe.net/DEV/[DEV Technical Framework].

include::sdpi-standard-intro.adoc[]

include::sdpi-standard-issues.adoc[]

// = Volume 0 -- IHE Technical Frameworks General Introduction

include::volume0/tf0-main.adoc[]

// = Volume 1 -- Profiles

include::volume1/tf1-main.adoc[]

// = Volume 2 -- Transactions

include::volume2/tf2-main.adoc[]

// = Volume 3 -- Content Modules

include::volume3/tf3-main.adoc[]

