
[sdpi_offset=clear]
== SDPi Issue Management

[sdpi_offset=clear]
=== SDPi "Topic of Interest" Issue Management

All SDPi supplement issues are tracked in the https://github.com/IHE/DEV.SDPi/issues[IHE Github sdpi-fhir repository Issues section]. Filter the issues on "SDPi Topic of Interest" to see a full list.  +

* To see the full list of OPEN issues, filter on: is:issue is:open label:"SDPi Topic of Interest"
* To see the full list of CLOSED issues, filter on: is:issue is:closed label:"SDPi Topic of Interest"

For more detailed information on how the Gemini SES+MDI program manages issues from identification to resolution to incorporation into this supplement, see the wiki article https://github.com/IHE/DEV.SDPi/wiki/Program-Coordination-Co-Working-Spaces#overview-from-discussion-to-planning-to-development[_Overview: From Discussion to Planning to Development_] and the confluence article https://confluence.hl7.org/pages/viewpage.action?pageId=82912211#TopicsofInterest-TopicResolutionWorkflow[_Topics of Interest -- Topic Resolution Workflow_].

[sdpi_offset=clear]
=== Open Issues and Topic of Interests

==== Open Issues

// open issues are inserted here

==== Topic of Interests

// toi issues are inserted here

[sdpi_offset=clear]
=== Closed Issues

// closed issues are inserted here

