= Service-oriented Device Point-of-care Interoperability (SDPi) Technical Framework
:doctype: book
// CAUTION: do not change the xrefstyle attribute as otherwise numbering will be broken
:xrefstyle: short
:stylesdir: css
:!webfonts:
:!iconfont-remote:
:toc-title: Contents
:toc: left
:toclevels: 3
:multipage-level: 2
:sectnums:
:icons: font
:imagesoutdir: images/
:imagesdir: images/
:docinfo: shared
:source-highlighter: highlight.js
:highlightjsdir: js/highlight

:sdpi_milestone_publication: SDPi 1.4 Publication
:sdpi_milestone_review: SDPi 1.4 Review

:ihe_supplement_sdpi_revision: 1.4.1
:ihe_supplement_sdpi_revision_short: 1.4
:ihe_supplement_sdpi_revision_date: {localdatetime}
:ihe_supplement_sdpi_revision_label: Standard for Trial Use / Implementation
:ihe_supplement_sdpi_publication_month: October 4, 2024
:ihe_supplement_sdpi_public_comment_submission_deadline: N/A

{empty} +
++++
<script>
    $('body').prepend('<div id="load-screen"><div style="margin-top: -64px">Menu is loading</div></div>');
    document.getElementsByClassName('sectlevel0')[0].style.visibility = "hidden";
</script>
++++

[subs=attributes]
++++
<div class="logos">
    <div>
        <img src="{imagesdir}hl7-intl-logo.svg"/>
        <img src="{imagesdir}ihe-logo.svg"/>
    </div>
    <div><strong>A Joint HL7-IHE Gemini Device Interoperability Project</strong></div>
</div>
<p style="font-size: 2.75em; text-align: center"><strong>IHE Devices</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Technical Framework Supplement</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Service-oriented Device Point-of-care</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Interoperability (SDPi)</strong></p>

<p style="text-align: center">Revision {ihe_supplement_sdpi_revision} &mdash; {ihe_supplement_sdpi_revision_label}</p>
++++

{empty} +

[%noheader]
[cols="1,4"]
[frame=none,grid=none]
|===
| *Publication Date:*
| {ihe_supplement_sdpi_publication_month}

| *Build Date:*
| {ihe_supplement_sdpi_revision_date}

| *Author:*
| HL7 Devices Working Group & IHE Devices Technical Committee

| *Email:*
| DEV@ihe.net
|===

{empty} +

*Please verify you have the most recent version of this document.*
See https://profiles.ihe.net/DEV/[*HERE*] for STU/Trial Implementation and Final Text versions and https://profiles.ihe.net/DEV/#1.3[*HERE*] for Public Comment versions.

A PDF version of the specification is available upon request.

[#supplement_clause_foreword,sdpi_offset=clear]
= Foreword

This Gemini standard is a joint development effort between Health Level Seven International (HL7) and Integrating the Healthcare Enterprise (IHE) devices working groups.
Its development and publication adheres to the consensus standards processes of both HL7, an ANSI accredited standards development organization, and IHE.
Publication as a Standard for Trial Use (HL7) or Trial Implementation (IHE) reflects the continuous cycle of development, balloting and publication of the specification, to address addition of new capabilities as well as identified safety, effectiveness and security issues and enhancements.
Product developers are encouraged to use the standard, recognizing the potential impact of this continuous development cycle.

This is a supplement to the IHE Devices Technical Framework. Each supplement undergoes a process of public comment and trial implementation before being incorporated into the volumes of the Technical Frameworks.

This supplement is published on {ihe_supplement_sdpi_publication_month} for Trial Implementation and may be available for testing at subsequent IHE Connectathons. The supplement may be amended based on the results of testing. Following successful testing it will be incorporated into the Devices Technical Framework. Comments are invited and can be submitted at https://www.ihe.net/DEV_Public_Comments/[Devices Public Comments] or by submitting a https://github.com/IHE/DEV.SDPi/issues/new/choose[GitHub Issue].

This supplement describes changes to the existing technical framework documents.

“Boxed” instructions like the sample below indicate to the Volume Editor how to integrate the relevant section(s) into the relevant Technical Framework volume.
|===
|__Amend section W.X by the following:__
|===

Where the amendment adds text, make the added text +++<u><b>bold underline</b></u>+++.
Where the amendment removes text, make the removed text +++<b><s>bold strikethrough</s></b>+++.
When entire new sections are added, introduce with editor’s instructions to “add new text” or similar, which for readability are not bolded or underlined.

General information about IHE can be found at http://www.ihe.net/[IHE.net].

Information about the IHE Devices domain can be found at https://www.ihe.net/ihe_domains/[IHE Domains].

Information about the organization of IHE Technical Frameworks and Supplements and the process used to create them can be found at https://www.ihe.net/resources/profiles/[Profiles] and https://www.ihe.net/about_ihe/ihe_process/[IHE Processes].

The current version of the IHE Devices Technical Framework can be found at https://profiles.ihe.net/DEV/[DEV Technical Framework].

include::sdpi-supplement-intro.adoc[]

include::sdpi-supplement-issues.adoc[]

// = Volume 0 -- IHE Technical Frameworks General Introduction

include::volume0/tf0-main.adoc[]

// = Volume 1 -- Profiles

include::volume1/tf1-main.adoc[]

// = Volume 2 -- Transactions

include::volume2/tf2-main.adoc[]

// = Volume 3 -- Content Modules

include::volume3/tf3-main.adoc[]
