= Service-oriented Device Point-of-care Interoperability (SDPi) Technical Framework
:doctype: book
// CAUTION: do not change the xrefstyle attribute as otherwise numbering will be broken
:xrefstyle: short
:stylesdir: css
:!webfonts:
:!iconfont-remote:
:toc-title: Contents
:toc: left
:toclevels: 3
:multipage-level: 2
:sectnums:
:icons: font
:icon-set: fas
:imagesoutdir: images/
:imagesdir: images/
:docinfo: shared
:source-highlighter: highlight.js
:highlightjsdir: js/highlight

// Set the document attribute to automatically generate
// actor transactions table from semantic markup. Unset
// to use manual tables. 
// https://docs.asciidoctor.org/asciidoc/latest/attributes/unset-attributes/
:markup-actor-transactions-table:

:sdpi_milestone_publication: SDPi 2.5 Publication
:sdpi_milestone_review: SDPi 2.5 Review

:sdpi_version_major: 2
:sdpi_version_minor: 5
:sdpi_version_revision: 0
:ihe_supplement_sdpi_revision: {sdpi_version_major}.{sdpi_version_minor}.{sdpi_version_revision}
:ihe_supplement_sdpi_revision_short: {sdpi_version_major}.{sdpi_version_minor}
:ihe_supplement_sdpi_revision_date: {localdatetime}
:ihe_supplement_sdpi_revision_label: Standard for Trial Use / Implementation
:ihe_supplement_sdpi_publication_month: May 7, 2026
:ihe_supplement_sdpi_public_comment_submission_deadline: N/A

// Oid, assigned by IHE-DEV, for the SDPi specification
// https://wiki.ihe.net/index.php/PCD_OID_Management
// STANDALONE SDPi:  Disabled the following line ... we may eventually need something in this supplement for OIDs but breaking it now makes sure that this is a SLIM document to start with!
// :sdpi-parent-oid: 1.3.6.1.4.1.19376.1.6.2.10

{empty} +
ifeval::["{backend}" == "html5"]
++++
<script>
    $('body').prepend('<div id="load-screen"><div style="margin-top: -64px">Menu is loading</div></div>');
    document.getElementsByClassName('sectlevel0')[0].style.visibility = "hidden";
</script>
++++

[subs=attributes]
++++
<div class="logos">
    <div>
        <img src="{imagesdir}hl7-intl-logo.svg"/>
        <img src="{imagesdir}ihe-logo.svg"/>
    </div>
    <div><strong>A Joint HL7-IHE Gemini Device Interoperability Project</strong></div>
</div>
<p style="font-size: 2.75em; text-align: center"><strong>IHE Devices</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Technical Framework Supplement</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Service-oriented Device Point-of-care</strong></p>

<p style="font-size: 2.75em; text-align: center"><strong>Interoperability (SDPi)</strong></p>

<p style="text-align: center">Revision {ihe_supplement_sdpi_revision} &mdash; {ihe_supplement_sdpi_revision_label}</p>
++++
endif::[]
{empty} +

[%noheader]
[cols="1,4"]
[frame=none,grid=none]
|===
| *Publication Date:*
| {ihe_supplement_sdpi_publication_month}

| *Build Date:*
| {ihe_supplement_sdpi_revision_date}

| *Author:*
| HL7 Devices Working Group & IHE Devices Technical Committee

| *Email:*
| DEV@ihe.net
|===

{empty} +

*Please verify you have the most recent version of this document.*
See https://profiles.ihe.net/DEV/[*HERE*] for STU/Trial Implementation and Final Text versions and https://profiles.ihe.net/DEV/#1.2[*HERE*] for Public Comment versions.

ifeval::["{backend}" == "html5"]
//A PDF version of the specification is available upon request.
endif::[]

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi "Standalone" Supplement -- Release & Drafting Notes*:


=== Release Note
This sdpi-supplement document is being created out of and aligned with the current sdpi-standard document.
This document is intended to provide the necessary organization and summary content that can ultimately be integrated into the IHE DEV TF "final text" normative version.
When that integration to the DEV TF occurs, this "supplement" will no longer be needed and will be deprecated.

NOTE: This supplement will directly reference the "standard" revision to which it is aligned.
It may be that when a DEV TF integration occurs, that is only partial to "finalized" aspects of the SDPi standard and other capabilities will be in active development, thus requiring the need for this supplement -- potentially, for a long time!"

The complete detailed content will remain in the sdpi-standard document as it has evolved in recent years; however, that document will be designed so that it will always remain -- standalone -- and will not be integrated into some other document.

=== Drafting Note - Remaining Tasks & Open Questions
Editorial Task List (prioritized) for this Supplement:

. [.line-through]#Move over Introduction files#
. [.line-through]#Move over TF-0 files#
. [.line-through]#Add top level outline structure for supplement document#
.. Move Clause 2 Overview content to supplement (it will stay here intact)
. [.line-through]#Change labels as appropriate / necessary to be supplement-specific so as to reduce any confusion#
. Add front matter updates per IHE TF Format but for this Supplement, explaining supplement/standalone & conceptual approach.
NOTE:  The TF-1:2 content might be identical in this document.
. Add overview content for each outline section
. Add Standard -> Supplement Release Update punch list (e.g., new actors / transactions ... in TF-0 appendices)
. Migrate all supplement INSTRUCTIONS (e.g., from TF-3) to this supplement
. ...

|===


[#supplement_clause_foreword,sdpi_offset=clear]
= Foreword

This Gemini standard is a joint development effort between Health Level Seven International (HL7) and Integrating the Healthcare Enterprise (IHE) devices working groups.
Its development and publication adheres to the consensus standards processes of both HL7, an ANSI accredited standards development organization, and IHE.
Publication as a Standard for Trial Use (HL7) or Trial Implementation (IHE) reflects the continuous cycle of development, balloting and publication of the specification, to address addition of new capabilities as well as identified safety, effectiveness and security issues and enhancements.
Product developers are encouraged to use the standard, recognizing the potential impact of this continuous development cycle.

This is a supplement to the IHE Devices Technical Framework. Each supplement undergoes a process of public comment and trial implementation before being incorporated into the volumes of the Technical Frameworks.

This supplement is published on {ihe_supplement_sdpi_publication_month} for Trial Implementation and may be available for testing at subsequent IHE Connectathons. The supplement may be amended based on the results of testing. Following successful testing it will be incorporated into the Devices Technical Framework. Comments are invited and can be submitted at https://www.ihe.net/DEV_Public_Comments/[Devices Public Comments] or by submitting a https://github.com/IHE/DEV.SDPi/issues/new/choose[GitHub Issue].

Some section numbers are skipped in this supplement because it is designed for later incorporation into the Devices Technical Framework. Skipped section numbers are present in the Devices Technical Framework, and will not require changes due to the incorporation of this supplement.

This supplement describes changes to the existing technical framework documents.

“Boxed” instructions like the sample below indicate to the Volume Editor how to integrate the relevant section(s) into the relevant Technical Framework volume.
|===
|__Amend section W.X by the following:__
|===

Where the amendment adds text, make the added text +++<u><b>bold underline</b></u>+++.
Where the amendment removes text, make the removed text +++<b><s>bold strikethrough</s></b>+++.
When entire new sections are added, introduce with editor’s instructions to “add new text” or similar, which for readability are not bolded or underlined.

General information about IHE can be found at http://www.ihe.net/[IHE.net].

Information about the IHE Devices domain can be found at https://www.ihe.net/ihe_domains/[IHE Domains].

Information about the organization of IHE Technical Frameworks and Supplements and the process used to create them can be found at https://www.ihe.net/resources/profiles/[Profiles] and https://www.ihe.net/about_ihe/ihe_process/[IHE Processes].

The current version of the IHE Devices Technical Framework can be found at https://profiles.ihe.net/DEV/[DEV Technical Framework].

include::supplement/sdpi-supplement-intro.adoc[]

// Standalone TO DO - This is a common IHE SUPPLEMENT SECTION, we should include it and mention that they are in the standard
// include::supplement/sdpi-standard-issues.adoc[]

// = Volume 0 -- IHE Technical Frameworks General Introduction

include::supplement/volume0/tf0-main.adoc[]

//
// = Volume 1 -- Profiles
//
include::supplement/sdpi-supplement-tf1.adoc[]


//
// = Volume 2 -- Transactions
//
include::supplement/sdpi-supplement-tf2.adoc[]

//
// = Volume 3 -- Content Modules
//
include::supplement/sdpi-supplement-tf3.adoc[]

