
[#supplement_clause_introduction_to_supplement,sdpi_offset=clear]
= Introduction to this Supplement

[%noheader]
[%autowidth]
[cols="1"]
|===
a| *SDPi 1.3 Supplement -- _STU / TI Version_ -- Note*:

This release of the SDPi 1.3 Standard for Trial Use (HL7 STU) / Trial Implementation (IHE TI) supplement is the first release that integrates resolutions from an HL7 ballot cycle (January 2024). This process implements links from HL7 ballot Jira tickets to IHE DEV.SDPi Github Issues that then enable tracking of the comment resolution implementation in this specification.

Note:  The 1.3.1 release provides a few minor editorial corrections that were overlooked in the first release of 1.3.0.

Release 1.3 provides only a few _incremental_ updates to release 1.2; however, it continues the objective of quarterly _minor version_ releases and continues to advance support for prototyping and testing of device-to-device plug-and-trust interoperability.
It is recognized, though, that this release is incomplete with work continuing for 1.4 and subsequent versions.
These known limitations include:


. Releases along with the planned capability additions are managed in the project's https://github.com/orgs/IHE/projects/6[DEV.SDPi "Gemini SDPi Releases" Github project]
. This supplement includes (4) SDPi Profiles, though the typical IHE supplement is organized for a single profile; as a result, some adjustments have been made, especially in the supplement overview section where there is a general SDPi overview and then basic overviews for each of the Profiles; challenging areas include profile "options" where there are FOUR sections vs. one; it is a work in progress and feedback is appreciated, especially to enhance clarity
. *Open / Closed Issues tables* -- starting with SDPi 1.1 and subsequent, the approach for the IHE open / closed issues section has been transitioned to utilize https://github.com/IHE/DEV.SDPi/issues[Github Issues] that are related to this release; each release will update the changelog file, detailing what is Added, Changed or Removed
. *Requirements boxes* (e.g., "R1234") have been added especially in TF-2, with some also part of TF-1 and TF-3; this is an initial approach that *_will be significantly expanded in future versions of the supplement_*; an initial approach is provided in <<vol1_clause_sdpi_requirements_modeling_integration>>, with discussion related to how it will be expanded in future versions of the supplement;
. *_<<term_safe_effective_secure>> Sections_* (see <<vol1_clause_appendix_a_ses_considerations_section_template>>) are included in the specification; however, their use and content will be significantly extended in future versions;
. This supplement is currently rendered as a *"long form"* document -- one single HTML file; however, in subsequent versions the intent is to consider a multi-page / file HTML rendering + addition of a tabbed menu for navigating the sections of the supplement;
. *"SDPi 1.3 Supplement Note"* boxes are provided throughout the document to help guide reviewers and implementers.

|===

// Forward declarations of common labels & acronyms & variables
include::document-declarations.adoc[]


[#supplement_clause_sdpi_supplement_overview]
== SDPi Supplement Overview

[#supplement_clause_sdpi_supplement_organization]
=== SDPi Supplement Organization

This IHE Devices Technical Framework supplement introduces a new _family of interoperability profiles_, Service-oriented Device Point-of-care Interoperability (SDPi), that comprise (4) separate profiles:

* SDPi-Plug-and-trust (*SDPi-P*) Profile
* SDPi-Reporting (*SDPi-R*) Profile
* SDPi-Alerting (*SDPi-A*) Profile
* SDPi-external Control (*SDPi-xC*) Profile

To that end, the supplement includes updates to all (3) IHE DEV TF volumes, including:

*TF-1  Profiles*

* General overview of the SDPi architectural approach & integrated set of profiles
* Profile-specific sections
* Related appendices, for example the integration of this family of SDPi Profiles with other sources of requirements - use cases or reference standards

*TF-2  Transactions*

* Extensive new set of transactions based on ISO/IEEE 11073 Service-oriented Device Connectivity (SDC) medical device interoperability standards.
* Related appendices, for example the specialized use of web services messaging for device communication and gateways to other protocols or profiles

*TF-3  Content Modules*

* New content covering the application of ISO/IEEE 11073 SDC semantic standards to device content modules, with a primary focus on specifications related to the ISO/IEEE 11073-10207 BICEPS standard.

{empty} +

[#supplement_clause_joint_ihe_hl7_gemini_ses_mdi_project_development]
=== Joint IHE-HL7 Gemini SES+MDI Project Development
This supplement is the result of a joint https://confluence.hl7.org/x/Xzf9Aw[IHE-HL7 Gemini Device Interoperability program] which began early 2020.
Extensive notes and discussion materials are provided on the project's HL7 Confluence site, including a https://confluence.hl7.org/pages/viewpage.action?pageId=113674346#LibrarywithEVERYTHINGyoueverwantedtoknow...-GeneralUpdate&BriefingPresentations[Library with extensive presentations and other materials].
This Library also includes *_briefings (slides and recordings) to provide background for those reviewing the specification_*.

The joint IHE-HL7 devices team leveraged tools from both organizations, as well as participated jointly throughout the project's multi-year efforts.

The methods currently employed are provided in the wiki article:  https://github.com/IHE/DEV.SDPi/wiki/Program-Coordination-Co-Working-Spaces#program-coordination--co-working-spaces[Program Coordination & Co-Working Spaces].

[#supplement_clause_supplement_support_for_ri_mc_rr_using_asciidoc]
=== Supplement Support for RI+MC+RR using AsciiDoc
In addition to the supplement's technical specification content, a development approach has been advanced that represents added value to adopters and implementers over the traditional document oriented approach.
These are referred to as:

[none]
. *_Requirements Interoperability + Model Centric + Regulatory Ready_*

Or *RI+MC+RR* for short.

These three objectives may be summarized as follows:

[none]
* *Requirements Interoperability (RI)*
[none]
** Ability to integrate & automate requirements and capabilities from component specifications & standards to enable traceability & coverage at <<term_conformity_assessment>> (<<acronym_ca>>) of the component product interface
* *Model Centric (MC)*
[none]
** Transition from a document-centric to a _computable model-based "single source of truth"_ specification from which the Technical Framework becomes a view of the model
* *Regulatory Ready (RR)*
[none]
** Enable CA test reports that are genuinely _"regulatory submission ready"_ (e.g., inclusion in a U.S. FDA 510(k) submission package)

The SDPi 1.3 version of the supplement continues to make small but significant steps toward support of these objectives, especially Requirements Interoperability, as well as the use of AsciiDoc metadata to annotate the document sources for post-processing.
Clearly, moving toward <<term_model_centric>> specifications and full integration of <<term_model_based_systems_engineering>> (<<acronym_mbse>>) will take considerable effort and time; however, this supplement represents a humble start in that direction.
Subsequent supplement versions will build upon these objectives and support a new level of rigor for connectathon and product conformity assessment testing and ultimately test reports that directly impact the challenges around medical product regulatory submissions.

Additional discussion is provided in <<vol1_appendix_a_requirements_management_for_p_n_t_interperability>>, and on the https://confluence.hl7.org/pages/viewpage.action?pageId=82906664#ConformityAssessment&Tooling-RI+MC+RRforMedTechSpecificationsInitiative[Gemini project's confluence pages].
See also related discussions on the Gemini Project's https://confluence.hl7.org/x/XhPUB[Pathway to an Ecosystem of Plug-and-Trust Products].


