@startuml

!include plantuml/common_style.inc.puml
autonumber

!global $str_somds_medical_data_consumer = "SOMDS Medical Data Consumer"
!global $str_somds_medical_data_provider = "SOMDS Medical Data Provider"

participant "$str_somds_medical_data_consumer" as consumer
participant "$str_somds_medical_data_provider" as provider

==Retrieve Medical Data [DEV-37]==

consumer -> provider: GetMdib()
consumer <<-- provider: GetMdibResponse(MdDescription, MdState [incl. ContextStates])
@enduml