@startuml

!include plantuml/common_style.inc.puml
autonumber

!global $str_somds_consumer = "SOMDS Consumer"
!global $str_somds_provider = "SOMDS Provider"

participant "$str_somds_consumer" as consumer
participant "$str_somds_provider" as provider

==Retrieve Localization Information[DEV-33]==

consumer -> provider: GetSupportedLanguages()
consumer <-- provider: GetSupportedLanguagesResponse(SupportedLanguages)
|||
loop SupportedLanguage in SupportedLanguages
    opt if SupportedLanguage is required
        consumer -> provider: GetLocalizedText(SupportedLanguage, [Filter])
        consumer <-- provider: GetLocalizedTextResponse(LocalizedTexts)
        consumer -> consumer: cache LocalizedTexts
    end
end


@enduml