@startuml

!include common_style.inc.puml
autonumber

!global $str_somds_consumer = "SOMDS Consumer"
!global $str_somds_provider = "SOMDS Provider"

participant "$str_somds_consumer" as consumer
participant "$str_somds_provider" as provider

==Discover BICEPS Content [DEV-30]==

consumer -> provider: GetMdib()
consumer <<-- provider: GetMdibResponse(MdDescription, MdState [incl. ContextStates])
@enduml