@startuml

skinparam monochrome true
autonumber

!global $str_somds_consumer = "SOMDS Consumer"
!global $str_somds_provider = "SOMDS Provider"

participant "$str_somds_consumer" as consumer
participant "$str_somds_provider" as provider

==Announce Network Presence [DEV-23]==
|||
group unsecured
    provider ->> consumer: Hello(Provider UID, Discovery Scope)
end
|||

@enduml