@startuml

skinparam monochrome true
autonumber

!global $str_somds_consumer = "SOMDS Consumer"
!global $str_somds_provider = "SOMDS Provider"

participant "$str_somds_consumer" as consumer
participant "$str_somds_provider" as provider

==SDPi Announce Network Departure [DEV-34]==
|||
group unsecured
    provider ->> consumer: Bye(Provider UID)
end
|||

@enduml