@startuml

!include plantuml/common_style.inc.puml
autonumber

!global $str_somds_consumer = "SOMDS Consumer"
!global $str_somds_provider = "SOMDS Provider"

participant "$str_somds_consumer" as consumer
participant "$str_somds_provider" as provider

==Publish BICEPS Update Reports [DEV-29]==
opt
consumer <<- provider: Notification(EpisodicAlertReport)
end
opt
consumer <<- provider: Notification(EpisodicMetricReport)
end
opt
consumer <<- provider: Notification(EpisodicComponentReport)
end
opt
consumer <<- provider: Notification(DescriptionModificationReport)
end
opt
consumer <<- provider: Notification(EpisodicOperationalStateReport)
end
opt
consumer <<- provider: Notification(WaveformStream)
end
@enduml