@startuml

!include plantuml/common_style.inc.puml
autonumber

!global $str_somds_medical_alert_consumer = "SOMDS Medical Alert Consumer"
!global $str_somds_medical_alert_provider = "SOMDS Medical Alert Provider"

participant "$str_somds_medical_alert_consumer" as consumer
participant "$str_somds_medical_alert_provider" as provider

==Medical Alert Status [DEV-40]==

consumer -> provider: GetMdib()
consumer <<-- provider: GetMdibResponse(MdDescription, MdState [incl. ContextStates])
@enduml