@startuml

skinparam monochrome true
autonumber

!global $str_somds_consumer = "SOMDS Consumer"
!global $str_somds_provider = "SOMDS Provider"

participant "$str_somds_consumer" as consumer
participant "$str_somds_provider" as provider

== SDPi [DEV-28] Notify Change in System Context and Capabilities  ==


consumer <<- provider: Notification(EpisodicContextReport)
@enduml