@startuml
skinparam monochrome true
autonumber

!global $str_sdpi_p_somds_cons = "SOMDS Consumer"
!global $str_sdpi_p_somds_prov = "SOMDS Provider"

participant "$str_sdpi_p_somds_cons" as sdpi_somds_consumer
participant "$str_sdpi_p_somds_prov" as sdpi_somds_provider

==SDPi Discover BICEPS Services [DEV-25]==

sdpi_somds_consumer -> sdpi_somds_provider: GetMetadata()
sdpi_somds_consumer <<-- sdpi_somds_provider: GetMetadataResponse(BICEPS Services, Device Metadata, Model Metadata)

/' opt conditional if BICEPS interfaces are processed dynamically
    loop on EndpointReference in HostedServices
        sdpi_somds_consumer -> sdpi_somds_provider: MetadataGet()
        sdpi_somds_consumer <-- sdpi_somds_provider: MetadataGetResponse([WsdlDescription], [WsdlUrl])
        opt conditional if WSDL description was not enclosed in MetadataGetResponse
            sdpi_somds_consumer -> sdpi_somds_provider: HTTP_GET(WsdlUrl)
            sdpi_somds_consumer <-- sdpi_somds_provider: HTTP_GET_RESPONSE(WsdlDescription)
        end
    end
end'/

@enduml