@startuml

skinparam monochrome true
autonumber

!global $str_somds_consumer = "SOMDS Consumer"
!global $str_somds_provider = "SOMDS Provider"

participant "$str_somds_consumer" as consumer
participant "$str_somds_provider" as provider

==SDPi Establish Medical Data Exchange [DEV-35]==

consumer -> provider: Subscribe(Filter, Expiration Time)
consumer <<-- provider: SubscribeResponse(Subscription Manager, Expiration Time)

@enduml