@startuml

!include ../plantuml/common_style.inc.puml
autonumber

!global $str_somds_medical_alert_consumer = "SOMDS Medical Alert Consumer"
!global $str_somds_medical_alert_provider = "SOMDS Medical Alert Provider"

participant "$str_somds_medical_alert_consumer" as consumer
participant "$str_somds_medical_alert_provider" as provider

==Establish Distributed Alarm System [DEV-48]==
opt
    consumer -> provider: SetFriendlyConsumerName
    consumer <<-- provider: SetFriendlyConsumerNameResponse
end
consumer -> provider: MonitoredByDAS
consumer <<-- provider: MonitoredByDASResponse (MDIB version)

par
    loop upon alert condition change and before MaxTechnicalConfirmationDelay expires
        consumer -> provider: ConfirmAlertsTechnicalDelivery (Alert Occurrence ID Tuple(s))
        consumer <<-- provider: ConfirmAlertsTechnicalDeliveryResponse (MDIB version)
    end
else
    loop before InvocationEffectiveTimeout expires
        consumer -> provider: MonitoredByDAS
        consumer <<-- provider: MonitoredByDASResponse (MDIB version)
    end
else
    loop at least once every SelfCheckPeriod
        provider -> consumer: Notification (PeriodicAlertReport incl. updated 'SelfCheck' information)
    end
end

@enduml