[#vol0_clause_ihe_technical_frameworks_general_introduction, sdpi_volume_caption=0]
= IHE Technical Frameworks General Introduction

[#vol0_clause_general,sdpi_offset=clear]
== IHE Technical Frameworks General Introduction
The https://profiles.ihe.net/GeneralIntro[IHE Technical Frameworks General Introduction] is shared by all of the IHE domain technical frameworks. Each technical framework volume contains links to this document where appropriate.

include::tf0-ch-9-copyrights.adoc[]

// 10 Trademark

[sdpi_offset=10]
== Trademark
IHE^®^ and the IHE logo are trademarks of the Healthcare Information Management Systems Society in the United States and trademarks of IHE Europe in the European Community. Please refer to the IHE Technical Frameworks General Introduction, https://profiles.ihe.net/GeneralIntro/ch-10.html[Section 10 - Trademark] for information on their use.

[sdpi_offset=1]
[sdpi_offset=clear]
== IHE Technical Frameworks General Introduction Appendices
The https://profiles.ihe.net/GeneralIntro/index.html[IHE Technical Framework General Introduction Appendices] are components shared by all of the IHE domain technical frameworks. Each technical framework volume contains links to these documents where appropriate.

include::tf0-ch-a-actors.adoc[]

include::tf0-ch-b-transactions.adoc[]

include::tf0-ch-d-glossary.adoc[]

