[#vol0_clause_ihe_technical_frameworks_general_introduction]
= IHE Technical Frameworks General Introduction

[sdpi_offset=clear]
== General

The https://profiles.ihe.net/GeneralIntro[IHE Technical Frameworks General Introduction] is shared by all of the IHE domain technical frameworks. Each technical framework volume contains links to this document where appropriate.

include::tf0-ch-9-copyrights.adoc[]

// 10 Trademark

[sdpi_offset=10]
== Trademark
IHE^®^ and the IHE logo are trademarks of the Healthcare Information Management Systems Society in the United States and trademarks of IHE Europe in the European Community. Please refer to the IHE Technical Frameworks General Introduction, https://profiles.ihe.net/GeneralIntro/ch-10.html[Section 10 - Trademark] for information on their use.

[sdpi_offset=clear]
== IHE Technical Frameworks General Introduction Appendices
The https://profiles.ihe.net/GeneralIntro/index.html#3[IHE Technical Framework General Introduction Appendices] are components shared by all of the IHE domain technical frameworks. Each technical framework volume contains links to these documents where appropriate.

include::tf0-ch-a-actors.adoc[]

include::tf0-ch-b-transactions.adoc[]

include::tf0-ch-d-glossary.adoc[]

=== XML Namespaces

The XML namespace URI that is used by this specification is: `urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.1.1`.

<<vol0_table_xml_namespaces>> lists XML namespaces and prefixes that are used in this specification.
The choice of any namespace prefix is arbitrary and not semantically significant.

.Prefixes and XML namespaces used in this specification.
[#vol0_table_xml_namespaces,cols="1,5,2",width=100%,]
|===
|Prefix |XML Namespace |Specification

|dpws
|http://docs.oasis-open.org/ws-dd/ns/dpws/2009/01
|<<ref_oasis_dpws_2009>>

|sdpi
|urn:oid:1.3.6.1.4.1.19376.1.6.2.10.1.1.1
|This specification

|wsa
|http://www.w3.org/2005/08/addressing
|<<ref_oasis_ws_addressing_2006>>

|wsd
|http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01
|<<ref_oasis_ws_discovery_2009>>

|wse
|http://schemas.xmlsoap.org/ws/2004/08/eventing
|<<ref_w3c_ws_eventing_2006>>

|wsm
|http://schemas.xmlsoap.org/ws/2004/09/mex
|<<ref_w3c_ws_metadata_exchange_2008>>

|===