

[#vol2_clause_appendix_mdpws_dev_30]
==== MDPWS: Retrieve BICEPS Content [DEV-30]

This section specifies the MDPWS data transmission for messages defined in <<vol2_clause_dev_30>>.

// ---------- Get Mdib ---------


===== {var_label_dev_30_message_getmdib} Message

The <<vol2_clause_dev_30_message_getmdib, {var_label_dev_30_message_getmdib}>> message is encoded by using {var_uri_dpws_messaging}[DPWS Messaging].

====== Referenced Standards

* <<ref_oasis_dpws_2009>> {var_uri_dpws_messaging}[Section 2 Messaging]
* <<ref_ieee_11073_10207_2017>> msg:GetMdib

====== Message Outline

.GetMdib message
[source#vol2_clause_appendix_a_mdpws_dev_30_getmdib,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-30-getmdib.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_30_message_getmdib>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

The <<vol2_clause_dev_30_message_getmdib, {var_label_dev_30_message_getmdib}>> message does not contain any further semantics.

:var_expected_actions_ref: <<vol2_clause_dev_30_message_getmdib>>
include::../dev-a-default-expected-actions.adoc[]

// ---------- Get Mdib Response ---------

===== {var_label_dev_30_message_getmdibresponse} Message

The <<vol2_clause_dev_30_message_getmdibresponse, {var_label_dev_30_message_getmdibresponse}>> message is encoded by using {var_uri_dpws_messaging}[DPWS Messaging].

====== Referenced Standards

* <<ref_oasis_dpws_2009>> {var_uri_dpws_messaging}[Section 2 Messaging]
* <<ref_ieee_11073_10207_2017>> msg:GetMdibResponse

====== Message Outline

.GetMdibResponse message
[source#vol2_clause_appendix_a_mdpws_dev_30_getmdibresponse,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-30-getmdibresponse.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_30_message_getmdibresponse>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/msg:GetMdibResponse/msg:Mdib/pm:MdDescription`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s descriptive part of the MDIB.

`s12:Envelope/s12:Body/msg:GetMdibResponse/msg:Mdib/pm:MdState`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s state part of the MDIB.

:var_expected_actions_ref: <<vol2_clause_dev_30_message_getmdibresponse>>
include::../dev-a-default-expected-actions.adoc[]

====== Additional Consideration

[sdpi_level=+1]
====== Context States

.R7002
[sdpi_requirement#r7002,sdpi_req_level=shall,sdpi_req_type=tech_feature]
****
[NORMATIVE]
====
A <<vol1_spec_sdpi_p_actor_somds_provider>> shall enclose all context states in pm:GetMdibResponse messages.
====

[NOTE]
====
This requirement restricts optionality in including context states in GetMdibResponse messages as specified in <<ref_ieee_11073_10207_2017>>, C.57 GetMdibResponse:

[quote]
____
Since contexts might include privacy-related information, a SERVICE PROVIDER MAY decide to leave
the MDS contexts empty.
____

Since transmission of GetMdibResponse messages is required to be secured, there is no need for omitting context states to meet confidentiality; R0121 in <<ref_ieee_11073_10207_2017>> is still met.
====

****


