:var_uri_ws_discovery_probe: http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231831
:var_uri_ws_discovery_probe_match: http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231835
:var_uri_ws_discovery_resolve: http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231840
:var_uri_ws_discovery_resolve_match: http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231844
:var_uri_dpws_discovery: http://docs.oasis-open.org/ws-dd/dpws/1.1/os/wsdd-dpws-1.1-spec-os.html#_Toc228672091
:var_uri_matching_rule: http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01/rfc3986

[#vol2_clause_appendix_mdpws_dev_47]
==== MDPWS: Provide Endpoint Metadata [DEV-47]

This section specifies the MDPWS data transmission for messages defined in <<vol2_clause_dev_47>>.

// ---------- Hello ---------

===== {var_label_dev_47_message_hello} Message

The <<vol2_clause_dev_47_message_hello, {var_label_dev_47_message_hello}>> message is encoded by using {var_uri_dpws_messaging}[DPWS Messaging].

====== Referenced Standards

* <<ref_oasis_dpws_2009>> {var_uri_dpws_messaging}[Section 2 Messaging]
* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_hello}[Section 4.1 Hello]

====== Message Outline

.{var_label_dev_47_message_hello} message
[source#vol2_clause_appendix_a_mdpws_dev_47_hello,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-47-hello.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_47_message_hello>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:Hello/wsa:EndpointReference/wsa:Address`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<payload_dev_47_provider_uid_hello>> as URI.
`s12:Envelope/s12:Body/wsd:Hello/wsd:Scopes`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<payload_dev_47_discovery_scope>> as a list of URIs.

:var_expected_actions_ref: <<vol2_clause_dev_47_message_hello>>
include::../dev-a-default-expected-actions.adoc[]


// ---------- Bye ---------

[#vol2_clause_appendix_a_mdpws_dev_47_message_bye]
===== {var_label_dev_47_message_bye} Message

The <<vol2_clause_dev_47_message_bye, {var_label_dev_47_message_bye}>> message is encoded by using {var_uri_dpws_messaging}[DPWS Messaging].

====== Referenced Standards

* <<ref_oasis_dpws_2009>> {var_uri_dpws_messaging}[Section 2 Messaging]
* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_bye}[Section 4.2 Bye]

====== Message Outline

.{var_label_dev_47_message_bye} message
[source#vol2_clause_appendix_a_mdpws_dev_47_bye,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-47-bye.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_47_message_bye>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:Bye/wsa:EndpointReference/wsa:Address`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<payload_dev_47_provider_uid_bye>> as URI.

:var_expected_actions_ref: <<vol2_clause_dev_47_message_bye>>
include::../dev-a-default-expected-actions.adoc[]


// ---------- PROBE ---------


===== {var_label_dev_47_message_probe} Message

The <<vol2_clause_dev_47_message_probe, {var_label_dev_47_message_probe}>> message is encoded by using {var_uri_ws_discovery_probe}[WS-Discovery Probe].

====== Referenced Standards

* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_probe}[Section 5.2 Probe]
* <<ref_oasis_dpws_2009>> {var_uri_dpws_discovery}[Section 3 Discovery]
* <<ref_ieee_11073_20702_2016>> mdpws:MedicalDevice
* <<ref_ieee_11073_20701_2018>> sdc.mds.pkp:1.2.840.10004.20701.1.1

====== Message Outline

.WS-Discovery Probe message
[source#vol2_clause_appendix_a_mdpws_dev_47_probe,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-47-probe.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_47_message_probe>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:Probe/wsa:Types`:: List that contains at least `mdpws:MedicalDevice` to express seeking <<vol1_spec_sdpi_p_actor_somds_provider>>s that conform to MDPWS.
`s12:Envelope/s12:Body/wsd:Probe/wsd:Scopes/@MatchBy`:: The algorithm used to compare the `s12:Envelope/s12:Body/wsd:Probe/wsd:Scopes` against the <<vol1_spec_sdpi_p_actor_somds_provider>>'s scopes.
`s12:Envelope/s12:Body/wsd:Probe/wsd:Scopes`:: The <<payload_dev_47_probe_discovery_scope>> as a list of URIs to probe for.
[#vol2_clause_appendix_mdpws_dev_47_recurring_probe]


:var_expected_actions_ref: <<vol2_clause_dev_47_message_probe_match>>
include::../dev-a-default-expected-actions.adoc[]

====== Additional Consideration

All additional considerations specified in <<vol2_clause_appendix_mdpws_dev_24_additional_consideration>> do also apply to <<vol2_clause_appendix_mdpws_dev_47>>.


// ---------- PROBE MATCH ---------


===== {var_label_dev_47_message_probe_match} Message

The <<vol2_clause_dev_47_message_probe_match, {var_label_dev_47_message_probe_match}>> message is encoded by using {var_uri_ws_discovery_probe_match}[WS-Discovery Probe Match].

====== Referenced Standards

* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_probe_match}[Section 5.3 Probe Match]
* <<ref_oasis_dpws_2009>> {var_uri_dpws_discovery}[Section 3 Discovery]
* <<ref_ieee_11073_20702_2016>> mdpws:MedicalDevice
* <<ref_ieee_11073_20701_2018>> sdc.mds.pkp:1.2.840.10004.20701.1.1

====== Message Outline

.WS-Discovery Probe Match message
[source#vol2_clause_appendix_a_mdpws_dev_47_probe_match,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-47-probe-match.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_47_message_probe_match>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:ProbeMatches`:: All matches found by the <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>>.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsa:EndpointReference/wsa:Address`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<term_somds_provider_uid>> encoded as URI.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsd:Types`:: List of types that contains at least `dpws:Device` and mdpws:MedicalDevice`, which expresses the <<vol1_spec_sdpi_p_actor_somds_provider>> to conform to DPWS and MDPWS.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsd:Scopes`:: The <<term_discovery_scope>> of the <<vol1_spec_sdpi_p_actor_somds_provider>>, encoded as a list of URIs.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsd:XAddrs`:: A list of HTTPS addresses under which the <<vol1_spec_sdpi_p_actor_somds_provider>> receives secured messages.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsd:MetadataVersion`:: A metadata version of the <<vol1_spec_sdpi_p_actor_somds_provider>>.

:var_expected_actions_ref: <<vol2_clause_dev_47_message_probe_match>>
include::../dev-a-default-expected-actions.adoc[]


// ---------- RESOLVE ---------


===== {var_label_dev_47_message_resolve} Message

The <<vol2_clause_dev_47_message_resolve, {var_label_dev_47_message_resolve}>> message is encoded by using {var_uri_ws_discovery_resolve}[WS-Discovery Resolve].

====== Referenced Standards

* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_resolve}[Section 6.2 Resolve]
* <<ref_oasis_dpws_2009>> {var_uri_dpws_discovery}[Section 3 Discovery]

====== Message Outline

.WS-Discovery Resolve message
[source#vol2_clause_appendix_a_mdpws_dev_47_resolve,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-47-resolve.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_47_message_resolve>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:Resolve/wsa:EndpointReference/wsa:Address`:: The <<payload_dev_47_provider_uid>> to resolve, encoded as URI.

:var_expected_actions_ref: <<vol2_clause_dev_47_message_resolve>>
include::../dev-a-default-expected-actions.adoc[]


// ---------- RESOLVE MATCH ---------


===== {var_label_dev_47_message_resolve_match} Message

The <<vol2_clause_dev_47_message_probe_match, {var_label_dev_47_message_resolve_match}>> message is encoded by using {var_uri_ws_discovery_resolve_match}[WS-Discovery Resolve Match].

====== Referenced Standards

* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_resolve_match}[Section 6.3 Resolve Match]
* <<ref_oasis_dpws_2009>> {var_uri_dpws_discovery}[Section 3 Discovery]
* <<ref_ieee_11073_20702_2016>> mdpws:MedicalDevice
* <<ref_ieee_11073_20701_2018>> sdc.mds.pkp:1.2.840.10004.20701.1.1

====== Message Outline

.WS-Discovery Resolve Match message
[source#vol2_clause_appendix_a_mdpws_dev_47_resolve_match,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-47-resolve-match.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_47_message_resolve_match>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsa:EndpointReference/wsa:Address`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<term_somds_provider_uid>> encoded as URI.
`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsd:Types`:: List of types that contains at least `dpws:Device` and mdpws:MedicalDevice`, which expresses the <<vol1_spec_sdpi_p_actor_somds_provider>> to conform to DPWS and MDPWS.
`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsd:Scopes`:: The <<term_discovery_scope>> of the <<vol1_spec_sdpi_p_actor_somds_provider>>, encoded as a list of URIs.
`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsd:XAddrs`:: A list of HTTPS addresses under which the <<vol1_spec_sdpi_p_actor_somds_provider>> receives secured messages.
`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsd:MetadataVersion`:: A metadata version of the <<vol1_spec_sdpi_p_actor_somds_provider>>.

:var_expected_actions_ref: <<vol2_clause_dev_47_message_resolve_match>>
include::../dev-a-default-expected-actions.adoc[]