:var_transaction_id: DEV-47

:var_label_dev_47_message_hello: Hello
:var_label_dev_47_message_bye: Bye
:var_label_dev_47_message_probe: Probe
:var_label_dev_47_message_probe_match: ProbeMatch
:var_label_dev_47_message_resolve: Resolve
:var_label_dev_47_message_resolve_match: ResolveMatch


//reset|+1|off
[#vol2_clause_dev_47,sdpi_offset=47]
=== Provide Endpoint Metadata [{var_transaction_id}]

==== Scope

include::tf2-dev-47-summary.adoc[]

==== Actor Roles

.Actor Roles [{var_transaction_id}]
[cols="1,2"]
|===
|Actor |Roles

|<<vol1_spec_sdpi_p_actor_somds_discovery_proxy>>
|Forwards <<vol2_clause_dev_46_message_hello, {var_label_dev_46_message_hello}>> and <<vol2_clause_dev_46_message_hello, {var_label_dev_46_message_bye}>> messages received from <<vol1_spec_sdpi_p_actor_somds_provider>>s.
Responds to incoming <<vol2_clause_dev_47_message_probe, {var_label_dev_47_message_probe}>> and <<vol2_clause_dev_47_message_resolve, {var_label_dev_47_message_resolve}>> messages
|<<vol1_spec_sdpi_p_actor_somds_consumer>>
|Optionally subscribes to a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> in order to receive <<vol2_clause_dev_47_message_hello, {var_label_dev_47_message_hello}>> and <<vol2_clause_dev_47_message_hello, {var_label_dev_47_message_bye}>> messages.
Uses <<vol2_clause_dev_47_message_probe, {var_label_dev_47_message_probe}>> and <<vol2_clause_dev_47_message_resolve, {var_label_dev_47_message_resolve}>> messages to seek endpoint metadata.
|===

==== Referenced Standards

* <<ref_ieee_11073_10207_2017>> Section 9. Discovery Model

==== Messages

.Message Interaction Diagram [{var_transaction_id}]
[plantuml#vol2_figure_dev_47_sequence, target=puml-dev-47-sequence, format=svg, width=100%]
....
include::../../plantuml/vol2-figure-dev-47-sequence.puml[]
....

// ---------- HELLO ---------

[#vol2_clause_dev_47_message_hello]
===== {var_label_dev_47_message_hello} Message

<<acronym_biceps>> specifies an implicit discovery protocol for allowing <<vol1_spec_sdpi_p_actor_somds_consumer>>s to receive a notification when a <<vol1_spec_sdpi_p_actor_somds_provider>> is ready to exchange messages with other <<vol1_spec_sdpi_p_actor_somds_consumer>>s.
If a <<vol1_spec_sdpi_p_actor_somds_consumer>> uses a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>>, network presence is announced to <<vol1_spec_sdpi_p_actor_somds_consumer>>s by using the _{var_label_dev_47_message_hello}_ message of this transaction.

[#vol2_clause_dev_47_message_hello_trigger_events]
====== Trigger Events

If a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> is known to the <<vol1_spec_sdpi_p_actor_somds_consumer>> and the <<vol1_spec_sdpi_p_actor_somds_consumer>> is interested in {var_label_dev_47_message_hello} messages, this message is sent

1. whenever a <<vol1_spec_sdpi_p_actor_somds_provider>> known to the <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> joins an <<acronym_md_lan>>,
2. when a <<vol1_spec_sdpi_p_actor_somds_provider>> known to the <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> returns to normal _on-line_ operation after having indicated temporary suspension of message exchanges, or
3. when a <<vol1_spec_sdpi_p_actor_somds_provider>> known to the <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> changes its <<payload_dev_23_discovery_scope>>.

[#vol2_clause_dev_47_message_hello_semantics]
====== Message Semantics

[[payload_dev_47_provider_uid_hello]]Provider UID:: The <<term_somds_provider_uid>>.
[[payload_dev_47_discovery_scope]]Discovery Scope:: The <<term_discovery_scope>> of the <<vol1_spec_sdpi_p_actor_somds_provider>>.

[#vol2_clause_dev_47_message_hello_expected_actions]
====== Expected Actions

When a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> sends this message, there is no expected or required response.

// ---------- BYE ---------

[#vol2_clause_dev_47_message_bye]
===== {var_label_dev_47_message_bye} Message

If a <<vol1_spec_sdpi_p_actor_somds_consumer>> uses a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>>, network absence is announced to <<vol1_spec_sdpi_p_actor_somds_consumer>>s by using the _{var_label_dev_47_message_bye}_ message of this transaction.

[#vol2_clause_dev_47_message_bye_trigger_events]
====== Trigger Events

If a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> is known to the <<vol1_spec_sdpi_p_actor_somds_consumer>> and the <<vol1_spec_sdpi_p_actor_somds_consumer>> is interested in {var_label_dev_47_message_bye} messages, this message is sent whenever a <<vol1_spec_sdpi_p_actor_somds_provider>> leaves the <<acronym_md_lan>> it previously joined via the {var_label_dev_46_message_hello} message.

[#vol2_clause_dev_47_message_bye_semantics]
====== Message Semantics

[[payload_dev_47_provider_uid_bye]]Provider UID:: The <<term_somds_provider_uid>>.

[#vol2_clause_dev_47_message_bye_expected_actions]
====== Expected Actions

When a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> sends this message, there is no expected or required response.

// ---------- PROBE ---------

[#vol2_clause_dev_47_message_probe]
===== {var_label_dev_47_message_probe} Message

<<acronym_biceps>> specifies an explicit discovery protocol for allowing <<vol1_spec_sdpi_p_actor_somds_consumer>>s to discover all <<vol1_spec_sdpi_p_actor_somds_provider>>s that are ready to exchange messages with <<vol1_spec_sdpi_p_actor_somds_consumer>>s.
The corresponding message to seek <<vol1_spec_sdpi_p_actor_somds_provider>>s based on filter criteria is called _{var_label_dev_47_message_probe}_.

If a <<vol1_spec_sdpi_p_actor_somds_consumer>> uses a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>>, the <<vol1_spec_sdpi_p_actor_somds_consumer>> can send a {var_label_dev_47_message_probe} message to the <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> to seek endpoint information based on filter criteria.

[#vol2_clause_dev_47_message_probe_trigger_events]
====== Trigger Events

The {var_label_dev_47_message_probe} message is sent whenever a <<vol1_spec_sdpi_p_actor_somds_consumer>> joins an <<acronym_md_lan>> and is ready to exchange messages with <<vol1_spec_sdpi_p_actor_somds_provider>>s.

[#vol2_clause_dev_47_message_probe_semantics]
====== Message Semantics

[[payload_dev_47_probe_discovery_scope]]Discovery Scope:: A <<term_discovery_scope>> to filter against.

[#vol2_clause_dev_47_message_probe_expected_actions]
====== Expected Actions

When a <<vol1_spec_sdpi_p_actor_somds_consumer>> sends this message, the <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> answers with all endpoint records that match the requested <<payload_dev_47_probe_discovery_scope>> by sending a <<vol2_clause_dev_47_message_probe_match, {var_label_dev_47_message_probe_match}>> message.

// ---------- PROBE MATCH ---------

[#vol2_clause_dev_47_message_probe_match]
===== {var_label_dev_47_message_probe_match} Message

The {var_label_dev_47_message_probe_match} message is sent as part of the BICEPS _explicit discovery_ protocol in response to an incoming <<vol2_clause_dev_47_message_probe, {var_label_dev_47_message_probe}>> message.

The {var_label_dev_47_message_probe_match} message is sent by a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> when an incoming <<vol2_clause_dev_47_message_probe, {var_label_dev_47_message_probe}>> message contains a <<payload_dev_47_probe_discovery_scope>> that matches zero or more <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<term_discovery_scope>>s.

[#vol2_clause_dev_47_message_probe_match_trigger_events]
====== Trigger Events

The {var_label_dev_47_message_probe_match} message is sent whenever a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> receives a <<vol2_clause_dev_47_message_probe, {var_label_dev_47_message_probe}>> message that contains a <<payload_dev_47_probe_discovery_scope>> that matches zero or more <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<term_discovery_scope>>s.

[#vol2_clause_dev_47_message_probe_match_semantics]
====== Message Semantics

[[payload_dev_47_probe_match_provider_uid]]Provider UID:: The <<term_somds_provider_uid>>.
[[payload_dev_47_probe_match_transport_address]]Transport Address:: The <<term_transport_address>> under which the <<vol1_spec_sdpi_p_actor_somds_provider>> can receive secured messages.

[#vol2_clause_dev_47_message_probe_match_expected_actions]
====== Expected Actions

The <<vol1_spec_sdpi_p_actor_somds_consumer>> that receives a {var_label_dev_47_message_probe_match} message can use the <<payload_dev_47_probe_match_transport_address>> to exchange secured messages with the <<vol1_spec_sdpi_p_actor_somds_provider>> for which it received the <<vol2_clause_dev_47_message_probe_match, {var_label_dev_47_message_probe_match}>> message.


// ---------- RESOLVE ---------


[#vol2_clause_dev_47_message_resolve]
===== {var_label_dev_47_message_resolve} Message

<<acronym_biceps>> specifies an explicit discovery protocol for allowing <<vol1_spec_sdpi_p_actor_somds_consumer>>s to discover all <<vol1_spec_sdpi_p_actor_somds_provider>>s that are ready to exchange messages with <<vol1_spec_sdpi_p_actor_somds_consumer>>s.
The corresponding message to seek <<vol1_spec_sdpi_p_actor_somds_provider>>s based on a unique identifier is called _{var_label_dev_47_message_resolve}_.

If a specific <<term_somds_provider_uid>> is known to a <<vol1_spec_sdpi_p_actor_somds_consumer>>, the <<vol1_spec_sdpi_p_actor_somds_consumer>> can send a {var_label_dev_47_message_resolve} message to a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>>.

[#vol2_clause_dev_47_message_resolve_trigger_events]
====== Trigger Events

The {var_label_dev_47_message_resolve} message is sent to a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>>

1. whenever a <<vol1_spec_sdpi_p_actor_somds_consumer>> joins an <<acronym_md_lan>> and is ready to exchange messages with <<vol1_spec_sdpi_p_actor_somds_provider>>s or
2. when a <<vol1_spec_sdpi_p_actor_somds_consumer>> runs in a mode where it periodically checks for availability of <<vol1_spec_sdpi_p_actor_somds_provider>>s matching a specific <<term_somds_provider_uid>>.

[#vol2_clause_dev_47_message_resolve_semantics]
====== Message Semantics

[[payload_dev_47_resolve_provider_uid]]Provider UID:: The <<term_somds_provider_uid>> to resolve.

[#vol2_clause_dev_47_message_resolve_expected_actions]
====== Expected Actions

When a <<vol1_spec_sdpi_p_actor_somds_consumer>> sends this message, the <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> answers with the endpoint record that matches the requested <<payload_dev_47_resolve_provider_uid>>

// ---------- RESOLVE MATCH ---------


[#vol2_clause_dev_47_message_resolve_match]
===== {var_label_dev_47_message_resolve_match} Message

The {var_label_dev_47_message_resolve_match} message is sent as part of the BICEPS _explicit discovery_ protocol in response to an incoming <<vol2_clause_dev_47_message_resolve, {var_label_dev_47_message_resolve}>> message.

The {var_label_dev_47_message_resolve_match} message is sent by a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> when an incoming <<vol2_clause_dev_47_message_resolve, {var_label_dev_47_message_resolve}>> message contains a <<payload_dev_47_provider_uid>> that matches zero or one <<term_somds_provider_uid>>.

[#vol2_clause_dev_47_message_resolve_match_trigger_events]
====== Trigger Events

The {var_label_dev_47_message_resolve_match} message is sent whenever a <<vol1_spec_sdpi_p_actor_somds_discovery_proxy>> receives a <<vol2_clause_dev_47_message_resolve, {var_label_dev_47_message_resolve}>> message that contains a <<payload_dev_47_provider_uid>> that is equal to a <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<term_somds_provider_uid>>.

[#vol2_clause_dev_47_message_resolve_match_semantics]
====== Message Semantics

[[payload_dev_47_provider_uid]]Provider UID:: The <<term_somds_provider_uid>>.
[[payload_dev_47_transport_address]]Transport Address:: The <<term_transport_address>> under which the <<vol1_spec_sdpi_p_actor_somds_provider>> can receive secured messages.

[#vol2_clause_dev_47_message_resolve_match_expected_actions]
====== Expected Actions

The <<vol1_spec_sdpi_p_actor_somds_consumer>> that receives a {var_label_dev_47_message_resolve_match} message can use the <<payload_dev_47_probe_match_transport_address>> to exchange secured messages with the <<vol1_spec_sdpi_p_actor_somds_provider>> for which it received the <<vol2_clause_dev_47_message_resolve_match, {var_label_dev_47_message_resolve_match}>> message.

[#vol2_clause_dev_47_publish_biceps_update_reports_ses]
include::../dev-x-default-ses-secured-mode.adoc[]

