:var_uri_ws_discovery_probe: http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231831
:var_uri_ws_discovery_probe_match: http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231835
:var_uri_ws_discovery_resolve: http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231840
:var_uri_ws_discovery_resolve_match: http://docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-spec-os.html#_Toc234231844
:var_uri_dpws_discovery: http://docs.oasis-open.org/ws-dd/dpws/1.1/os/wsdd-dpws-1.1-spec-os.html#_Toc228672091
:var_uri_matching_rule: http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01/rfc3986

[#vol2_clause_appendix_mdpws_dev_24]
==== MDPWS: Discovery Network Topology [DEV-24]

This section specifies the MDPWS data transmission for messages defined in <<vol2_clause_dev_24>>, corresponding to the WS-Discovery ad-hoc mode.

// ---------- PROBE ---------


===== {var_label_dev_24_message_probe} Message

The <<vol2_clause_dev_24_message_probe, {var_label_dev_24_message_probe}>> message is encoded by using {var_uri_ws_discovery_probe}[WS-Discovery Probe].

====== Referenced Standards

* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_probe}[Section 5.2 Probe]
* <<ref_oasis_dpws_2009>> {var_uri_dpws_discovery}[Section 3 Discovery]
* <<ref_ieee_11073_20702_2016>> mdpws:MedicalDevice
* <<ref_ieee_11073_20701_2018>> sdc.mds.pkp:1.2.840.10004.20701.1.1

====== Message Outline

.WS-Discovery Probe message
[source#vol2_clause_appendix_a_mdpws_dev_24_probe,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-24-probe.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_24_message_probe>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:Probe/wsa:Types`:: List that contains at least `mdpws:MedicalDevice` to express seeking <<vol1_spec_sdpi_p_actor_somds_provider>>s that conform to MDPWS.
`s12:Envelope/s12:Body/wsd:Probe/wsd:Scopes/@MatchBy`:: The algorithm used to compare the `s12:Envelope/s12:Body/wsd:Probe/wsd:Scopes` against the <<vol1_spec_sdpi_p_actor_somds_provider>>'s scopes.
`s12:Envelope/s12:Body/wsd:Probe/wsd:Scopes`:: The <<payload_dev_24_probe_discovery_scope>> as a list of URIs to probe for.
[#vol2_clause_appendix_mdpws_dev_24_recurring_probe]


:var_expected_actions_ref: <<vol2_clause_dev_24_message_probe_match>>
include::../dev-a-default-expected-actions.adoc[]

[#vol2_clause_appendix_mdpws_dev_24_additional_consideration]
====== Additional Consideration

[sdpi_level=+1]
====== Recurring Probe

While the number of Hello messages scales linearly with the number of <<vol1_spec_sdpi_p_actor_somds_provider>>s, in the worst case the number of Probe / ProbeMatch messages is the product of the number of <<vol1_spec_sdpi_p_actor_somds_provider>>s and the number of <<vol1_spec_sdpi_p_actor_somds_consumer>>s.
Therefore, in order to prevent the network congestion from Probe / ProbeMatch messages, the following requirements are defined:

.R3001
[sdpi_requirement#r3001,sdpi_req_level=should]
[sdpi_req_type=risk_mitigation,sdpi_ses_type=effectiveness,sdpi_ses_test=wire]
****
[NORMATIVE]
====
A <<vol1_spec_sdpi_p_actor_somds_consumer>> should not periodically send Probe messages.
====

[NOTE]
====
If Probe messages are sent periodically, a rationale needs to be provided, since <<vol1_spec_sdpi_p_actor_somds_provider>>s send Hello messages periodically.
====

****

.R3002
[sdpi_requirement#r3002,sdpi_req_level=may,sdpi_req_type=tech_feature]
****
[NORMATIVE]
====
A <<vol1_spec_sdpi_p_actor_somds_consumer>> may re-send Probe messages if demanded by a dedicated user interaction.
====

[NOTE]
====
A dedicated user interaction can be a button press on a <<vol1_spec_sdpi_p_actor_somds_consumer>>'s display or any other manual activation.
====

****

In addition, <<vol1_spec_sdpi_p_actor_somds_consumer>> may set filter criteria for Probe messages to reduce the amount of Probe Match messages.
For example, Probe messages are sent only if a <<vol1_spec_sdpi_p_actor_somds_consumer>> is assigned to a patient and lost network connection.

[sdpi_level=+1]
====== Scope Matching

.R7000
[sdpi_requirement#r7000,sdpi_req_level=shall,sdpi_req_type=tech_feature]
****
[NORMATIVE]
====
A <<vol1_spec_sdpi_p_actor_somds_provider>> shall implement the scope matching rule `{var_uri_matching_rule}` as specified by <<ref_oasis_ws_discovery_2009>> in a way that the use of _prefix_ refers to the definition of a prefix in formal theory.
====

[NOTE]
====
* This requirement erases disambiguation since there are multiple definitions of the term _prefix_.
* From this it follows that a prefix can be empty as otherwise the term _proper prefix_ would have to be used.
* The requirement does not impose restrictions on the use of other matching rules.
====
****

// ---------- PROBE MATCH ---------


===== {var_label_dev_24_message_probe_match} Message

The <<vol2_clause_dev_24_message_probe_match, {var_label_dev_24_message_probe_match}>> message is encoded by using {var_uri_ws_discovery_probe_match}[WS-Discovery Probe Match].

====== Referenced Standards

* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_probe_match}[Section 5.3 Probe Match]
* <<ref_oasis_dpws_2009>> {var_uri_dpws_discovery}[Section 3 Discovery]
* <<ref_ieee_11073_20702_2016>> mdpws:MedicalDevice
* <<ref_ieee_11073_20701_2018>> sdc.mds.pkp:1.2.840.10004.20701.1.1

====== Message Outline

.WS-Discovery Probe Match message
[source#vol2_clause_appendix_a_mdpws_dev_24_probe_match,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-24-probe-match.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_24_message_probe_match>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:ProbeMatches`:: In cases where multiple <<vol1_spec_sdpi_p_actor_somds_provider>>s are running on a single machine, `wsd:ProbeMatches` can contain multiple `wsd:ProbeMatch` results.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsa:EndpointReference/wsa:Address`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<term_somds_provider_uid>> encoded as URI.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsd:Types`:: List of types that contains at least `dpws:Device` and mdpws:MedicalDevice`, which expresses the <<vol1_spec_sdpi_p_actor_somds_provider>> to conform to DPWS and MDPWS.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsd:Scopes`:: The <<term_discovery_scope>> of the <<vol1_spec_sdpi_p_actor_somds_provider>>, encoded as a list of URIs.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsd:XAddrs`:: A list of HTTPS addresses under which the <<vol1_spec_sdpi_p_actor_somds_provider>> receives secured messages.
`s12:Envelope/s12:Body/wsd:ProbeMatches/wsd:ProbeMatch/wsd:MetadataVersion`:: A metadata version of the <<vol1_spec_sdpi_p_actor_somds_provider>>. To be ignored as the transmission of the Probe Match message is unsecure.

:var_expected_actions_ref: <<vol2_clause_dev_24_message_probe_match>>
include::../dev-a-default-expected-actions.adoc[]


// ---------- RESOLVE ---------


===== {var_label_dev_24_message_resolve} Message

The <<vol2_clause_dev_24_message_resolve, {var_label_dev_24_message_resolve}>> message is encoded by using {var_uri_ws_discovery_resolve}[WS-Discovery Resolve].

====== Referenced Standards

* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_resolve}[Section 6.2 Resolve]
* <<ref_oasis_dpws_2009>> {var_uri_dpws_discovery}[Section 3 Discovery]

====== Message Outline

.WS-Discovery Resolve message
[source#vol2_clause_appendix_a_mdpws_dev_24_resolve,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-24-resolve.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_24_message_resolve>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:Resolve/wsa:EndpointReference/wsa:Address`:: The <<payload_dev_24_provider_uid>> to resolve, encoded as URI.

:var_expected_actions_ref: <<vol2_clause_dev_24_message_resolve>>
include::../dev-a-default-expected-actions.adoc[]

// ---------- RESOLVE MATCH ---------


===== {var_label_dev_24_message_resolve_match} Message

The <<vol2_clause_dev_24_message_probe_match, {var_label_dev_24_message_resolve_match}>> message is encoded by using {var_uri_ws_discovery_resolve_match}[WS-Discovery Resolve Match].

====== Referenced Standards

* <<ref_oasis_ws_discovery_2009>> {var_uri_ws_discovery_resolve_match}[Section 6.3 Resolve Match]
* <<ref_oasis_dpws_2009>> {var_uri_dpws_discovery}[Section 3 Discovery]
* <<ref_ieee_11073_20702_2016>> mdpws:MedicalDevice
* <<ref_ieee_11073_20701_2018>> sdc.mds.pkp:1.2.840.10004.20701.1.1

====== Message Outline

.WS-Discovery Resolve Match message
[source#vol2_clause_appendix_a_mdpws_dev_24_resolve_match,xml]
----
include::../../listings/vol2-clause-appendix-a-mdpws-dev-24-resolve-match.xml[]
----

:var_trigger_events_ref: <<vol2_clause_dev_24_message_resolve_match>>
include::../dev-a-default-trigger-events.adoc[]

====== Message Semantics

`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsa:EndpointReference/wsa:Address`:: The <<vol1_spec_sdpi_p_actor_somds_provider>>'s <<term_somds_provider_uid>> encoded as URI.
`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsd:Types`:: List of types that contains at least `dpws:Device` and mdpws:MedicalDevice`, which expresses the <<vol1_spec_sdpi_p_actor_somds_provider>> to conform to DPWS and MDPWS.
`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsd:Scopes`:: The <<term_discovery_scope>> of the <<vol1_spec_sdpi_p_actor_somds_provider>>, encoded as a list of URIs.
`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsd:XAddrs`:: A list of HTTPS addresses under which the <<vol1_spec_sdpi_p_actor_somds_provider>> receives secured messages.
`s12:Envelope/s12:Body/wsd:ResolveMatches/wsd:ResolveMatch/wsd:MetadataVersion`:: A metadata version of the <<vol1_spec_sdpi_p_actor_somds_provider>>. To be ignored as the transmission of the Resolve Match message is unsecure.

:var_expected_actions_ref: <<vol2_clause_dev_24_message_resolve_match>>
include::../dev-a-default-expected-actions.adoc[]