[#vol2_clause_appendix_sdpi_gateway_hl7_v2_general_mapping]
=== SDPi Gateway -- HL7 V2 General Mapping
This section specifies general <<acronym_hl7>> V2 requirements and mappings, which apply to the <<vol2_clause_appendix_sdpi_dec_gateway>> as well as to the <<vol2_clause_appendix_sdpi_acm_gateway>> sections below.

==== Time Zone Setting
Timestamps can be specified in HL7 v2 in both UTC and local time.

====
NOTE: As stated in <<ref_ihe_pcd_tf_2_2019>> all observation times reported SHOULD be UTC, as indicated by including a time zone offset of +0000.

NOTE: If the timestamps are to be specified in local time, it is important that the time zone is set correctly at the <<term_point_of_care_device>>.

NOTE: It is not always guaranteed that the timezone configured at the <<actor_somds_provider>> and/or <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> corresponds with the timezone of the <<acronym_mds>> entities, for example, when a <<actor_somds_provider>> acting as device aggregator and/or the  <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> are running in a data center located in a different timezone than the <<acronym_mds>> entities.
====


include::tf2-ch-b-gateway-private-mdc-mapping.adoc[]

==== HL7 Segment Descriptions
The following sections specify the general <<acronym_hl7>> V2 segment mappings. Please refer to the *Appendix B Common Segment Descriptions* of the <<ref_ihe_pcd_tf_2_2019>> for further information.

include::tf2-ch-b-gateway-msh-mapping.adoc[]

include::tf2-ch-b-gateway-pid-mapping.adoc[]

include::tf2-ch-b-gateway-pv1-mapping.adoc[]

==== HL7 Field Descriptions
The following sections specify the general <<acronym_hl7>> V2 field mappings. Please refer to the *Appendix B Common Segment Descriptions* of the <<ref_ihe_pcd_tf_2_2019>> for further information.

include::tf2-ch-b-gateway-obx3-mapping.adoc[]

include::tf2-ch-b-gateway-obx4-mapping.adoc[]

include::tf2-ch-b-gateway-obx18-mapping.adoc[]