[#ref_gateway_pid_mapping]
===== PID - Patient Identification Segment
The HL7 Patient Identification (PID) segment requires a mapping from the <<acronym_mdib>> patient context information element *pm:PatientContextState* to the PID segment fields.

====== Prerequisite of Valid Patient Context
.R8102
[sdpi_requirement#r8102,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
The SDC patient context information shall only be mapped to the corresponding fields in the HL7 PID segment when the requirements for a valid SDC patient context as defined in <<ref_ieee_11073_10700_2022>> are fulfilled.

.Notes
[%collapsible]
====
NOTE: For a valid *pm:PatientContextState*, the *pm:AbstractContextState/@ContextAssociation* attribute is set to *"Assoc"* and the *pm:AbstractContextState/pm:Validator* is set to a valid validator. A corresponding inferred patient ensemble context is not required for the <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>>.

NOTE: If the SDC patient context information is not intended to be used for the mapping, please refer to the <<ref_ihe_pcd_tf_2_2019>> on how to populate the fields of the PID segment in this case.
====
****

====== PID-3 Patient Identifier List
.R8103
[sdpi_requirement#r8103,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If <<r8102>> is met, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> shall map the patient identifiers to the PID-3 field.

.Notes
[%collapsible]
====
NOTE: The PID-3 is a list of patient identifiers (e.g., medical record number, socal security number, visit number, account number, etc.)

NOTE: <<ref_tbl_pid3_mapping>> defines the mapping of the <<acronym_mdib>> patient identification to the data fields of the HL7 data type *CX* used in the PID-3 field.

NOTE: If the <<acronym_mdib>> patient identification element *pm:PatientContextState/pm:Identification* contains more than one patient identifier, each SDC patient identifier is mapped according to the <<ref_tbl_pid3_mapping>> table and added to the PID-3 patient identifier list.
====
****

[#ref_tbl_pid3_mapping]
.PID-3 Patient Identifier List Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-3/CX-1
|ID Number
|pm:PatientContextState+++<wbr/>+++/pm:Identification+++<wbr/>+++/@Extension
|The @Extension attribute contains the unique patient identifer.

*Note that the field may contain a null value indicating that the identifier is missing.*

|PID-3/CX-4
|Assigning Authority
|pm:PatientContextState+++<wbr/>+++/pm:Identification
| HL7 data type *HD*

|PID-3/CX-4.1
|Namespace ID
|/@Root
|The @Root contains the unique identification of the HDO.

*Note that if the HDO identifier is not defined the CX-4 field is left empty.*

|PID-3/CX-5
|Identifier Type Code
|pm:PatientContextState+++<wbr/>+++/pm:Identification+++<wbr/>+++/pm:Type+++<wbr/>+++/@Code
|The type of the patient identifier set in the @Code attribute is set to a value from HL7 V2 table 0203. The @CodingSystem is set to `urn:oid:2.16.840.1.113883.18.108`.

|===

The following identifier type codes are proposed to be used for the patient identifier in the point of care device:

[#ref_tbl_pid5_itc_valueset]
.Patient Identifier Type Code Value Set
|===
|Value |Description

|AN
|Account Number

|MR
|Medical Record Number

|PI
|Patient Internal Identifier

|U
|Unspecified Identifier

|VN
|Visit Number

|===

====== PID-5 Patient Name
.R8104
[sdpi_requirement#r8104,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If <<r8102>> is met, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> shall set the PID-5 field to the patient name information.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid5_mapping>> defines the mapping of the SDC patient name information to the data fields of the HL7 data type *XPN* used in the PID-5 field.
====
****

[#ref_tbl_pid5_mapping]
.PID-5 Patient Name Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-5/XPN-1
|Family Name
|pm:PatientContextState+++<wbr/>+++/pm:CoreData
|HL7 data type *FN*

|PID-5/XPN-1.1
|Surname
|/pm:Familyname
|

|PID-5/XPN-2
|Given Name
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Givenname
|

|PID-5/XPN-3
|Second and Further Given Names or Initials
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Middlename
|

|PID-5/XPN-5
|Prefix (e.g., DR)
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Title
|

|PID-5/XPN-7
|Name Type Code
|pm:PatientContextState+++<wbr/>+++/pm:CoreData
|This field is set to "L" when a patient name is available, or "U" when the patient name is not set.

Please refer also to the corresponding section in the <<ref_ihe_pcd_tf_2_2019>>.

|===

====== PID-6 Mother’s Maiden Name
.R8105
[sdpi_requirement#r8105,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If <<r8102>> is met, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> shall set the PID-6 field to the mother's maiden name or birth name before marriage.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid6_mapping>> defines the mapping of the SDC patient name information to the data fields of the HL7 data type *XPN* used in the PID-6 field.
====
****

[#ref_tbl_pid6_mapping]
.PID-6 Mother’s Maiden Name Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-6/XPN-1
|Family Name
|pm:PatientContextState+++<wbr/>+++/pm:CoreData
|HL7 data type *FN*

|PID-6/XPN-1.1
|Surname
|/pm:Birthname
|

|===

====== PID-7 Date/Time of Birth
.R8106
[sdpi_requirement#r8106,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If <<r8102>> is met, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> shall set the PID-7 field to the date & time of birth.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid7_mapping>> defines the mapping of the SDC patient's date of birth information to the data fields of the HL7 data type *DTM* used in the PID-7 field.
====
****

[#ref_tbl_pid7_mapping]
.PID-7 Date/Time of Birth Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-7/DTM-1
|Date/Time
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:DateOfBirth
|Note that the HL7 date & time format differs from the xsd date/time formats and requires a mapping accordingly (see also <<ref_expl_dt_mapping>>).

|===

[#ref_expl_dt_mapping]
.Date/Time Format Mapping
====
xsd:dateTime: *2001-10-26T21:32:52* -> HL7 DTM: *20011026213252*

xsd:date: *2001-10-26* -> HL7 DTM: *20011026*
====

====== PID-8 Administrative Sex

The sex and gender of a patient (or a newborn) cannot exactly be mapped from <<ref_ieee_11073_10207_2017>> to <<ref_hl7_v2>>. The <<acronym_biceps>> model only contains an attribute for sex (*pm:PatientContextState/pm:CoreData/pm:Sex*) as defined by biological and physiological characteristics. <<ref_hl7_v2>>, on the other hand, only provides a field for the administrative sex as defined by the socially constructed roles, behaviours, activities, and attributes that a given society considers appropriate. The biological sex, however, does not necessarily match a person’s administrative gender or sex. Mapping from one to the other would therefore introduce errors. However, in the clinical context of a <<acronym_pocd>> the *sex for clinical use* is important for various algorithms, range and limit settings, and so on.

In order to avoid an erroneous mapping of potentially different sex concept interpretations, the sex as defined in <<acronym_biceps>> is required to be mapped to a separate OBX segment as defined in <<r8120>>.

Mappings to the *PID-8 Administrative Sex* field are allowed in certain cases as defined in <<r8121>> and <<r8107>>.

.R8120
[sdpi_requirement#r8120,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If <<r8102>> is met, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> shall export the patient's sex as OBX segment on the MDS level.

.Notes
[%collapsible]
====
NOTE: The mapping for the patient's sex is defined in table <<ref_tbl_dec_obx_sex_mapping>>.
====
****

.R8121
[sdpi_requirement#r8121,sdpi_req_level=may,sdpi_max_occurrence=1]
****
If <<r8102>> is met and the patient's sex in the <<acronym_mdib>> is sourced from the PID-8 field in HL7 V2 ADT messages provided by the hospital ADT system, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> may set the PID-8 field to the code for the administrative sex.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid8_mapping>> defines the mapping of the SDC patient's sex information to the data fields of the HL7 data type *IS* used in the PID-8 field.
====
****

.R8107
[sdpi_requirement#r8107,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If <<r8102>> is met and the <<actor_somds_v2_gateway>> provides the Healthcare Delivery Organization (HDO) the possibility to configure the export of the patient's sex set in the <<acronym_mdib>> in the PID-8 field, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> shall set the PID-8 field to the code for the administrative sex.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid8_mapping>> defines the mapping of the SDC patient's sex information to the data fields of the HL7 data type *IS* used in the PID-8 field.
====
****

.R8122
[sdpi_requirement#r8122,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If the <<actor_somds_v2_gateway>> provides the Healthcare Delivery Organization (HDO) the possibility to configure the export of the patient's sex in the PID-8 field, the manufacturer of the <<actor_somds_v2_gateway>> shall require in the ACCOMPANYING INFORMATION that the HDO has to consider the risk that the patient's sex set in the <<acronym_mdib>> and mapped to the PID-8 field does not lead to a misinterpretation of the sex concept on <<actor_somds_v2_gateway>> consumer side.
****

[#ref_tbl_dec_obx_sex_mapping]
.OBX Sex Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|OBX-1
|Set ID - OBX
|
|Please refer to the <<ref_ihe_pcd_tf_2_2019>> *OBX-1 Set ID - OBX* for further information.

|OBX-2
|Value Type
|
|Set to *"ST"*.

|OBX-3/CWE-1
|Identifier
|
|Set to LOINC code *"46098-0"*.

|OBX-3/CWE-2
|Text
|
| Set to LOINC fully-specified name *"Sex"*.

|OBX-3/CWE-3
|Name of Coding System
|
|Set to coding system *"https://loinc.org"*.

|OBX-4
|Observation Sub-ID
|
|Set to *"<MDS>.0.0.3"* where *<MDS>* is the number of the MDS level assigned by the gateway.
See <<ref_dec_obx4>> for further information.

|OBX-5
|Observation Value
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Sex
|Note that the HL7 Administrative Sex value set (HL7 table 0001) differs from the SDC pm:Sex value set and requires a mapping accordingly (see also <<ref_tbl_sex_mapping>>).

|OBX-11
|Observation Result Status
|
|When the patient context has been associated and a new *@BindingStartTime* has been set, the field is set to final result status *"F"*.

When there are further updates of the sex value after the association of the patient context, the field is set to *"C"*.

|OBX-14
|Date/Time of the Observation
|pm:PatientContextState+++<wbr/>+++/@BindingStartTime
|Note that the HL7 date & time format differs from the xsd date/time formats and requires a mapping accordingly (see also <<ref_expl_dt_mapping>>).

|===


[#ref_tbl_pid8_mapping]
.PID-8 Administrative Sex Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-8/IS-1
|Administrative Sex
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Sex
|Note that the HL7 Administrative Sex value set (HL7 table 0001) differs from the SDC pm:Sex value set and requires a mapping accordingly (see also <<ref_tbl_sex_mapping>>).

|===

[#ref_tbl_sex_mapping]
.Patient's Sex Value Set Mapping
|===
|SDC Value |SDC Description |HL7 Value |HL7 Description

|Unspec
|Unspecified. Sex is not designated.
|A
|Ambiguous

|M
|Male. Indicates a male patient.
|M
|Male

|F
|Female. Indicates a female patient.
|F
|Female

|Unkn
|Unknown. Indicates that the sex is unknown for different reasons.
|U
|Unknown

|===

// https://build.fhir.org/ig/HL7/uv-pocd/StructureDefinition-Patient.html

====== PID-10 Race
.R8108
[sdpi_requirement#r8108,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If <<r8102>> is met, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> shall set the PID-10 field to the patient's race.

.Notes
[%collapsible]
====
NOTE: <<ref_tbl_pid10_mapping>> defines the mapping of the SDC patient's race information to the data fields of the HL7 data type *CWE* used in the PID-10 field.
====
****

[#ref_tbl_pid10_mapping]
.PID-10 Race Mapping
|===
|HL7 Field |HL7 Component Name |SDC Attribute/Element |Comments

|PID-10/CWE-1
|Identifier
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Race
/@Code
|

|PID-10/CWE-2
|Text
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Race
/@SymbolicCodeName
|

|PID-10/CWE-3
|Name of Coding System
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Race
/@CodingSystem
|

|PID-10/CWE-4
|Alternate Identifier
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Race+++<wbr/>+++/pm:Translation
/@Code
|Note that if *pm:Race/@Code* contains a private code, the corresponding translation is to be mapped. Otherwise, only the first entry of the *pm:Translation* element list is to be mapped.

|PID-10/CWE-6
|Name of Alternate Coding System
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Race+++<wbr/>+++/pm:Translation
/@CodingSystem
|Note that if *pm:Race/@Code* contains a private code, the corresponding translation is to be mapped. Otherwise, only the first entry of the *pm:Translation* element list is to be mapped.

|PID-10/CWE-7
|Coding System Version ID
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Race
/@CodingSystemVersion
|

|PID-10/CWE-8
|Alternate Coding System Version ID
|pm:PatientContextState+++<wbr/>+++/pm:CoreData+++<wbr/>+++/pm:Race+++<wbr/>+++/pm:Translation
/@CodingSystemVersion
|Note that if *pm:Race/@Code* contains a private code, the corresponding translation is to be mapped. Otherwise, only the first entry of the *pm:Translation* element list is to be mapped.

|===

====== PID-31 Identity Unknown Indicator
.R8109
[sdpi_requirement#r8109,sdpi_req_level=shall,sdpi_max_occurrence=1]
****
If <<r8102>> is met, then a <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> shall set the PID-31 field to an indicator whether the patient's identity is known.

.Notes
[%collapsible]
====
NOTE: For a valid *pm:PatientContextState*, the *pm:AbstractContextState/@ContextAssociation* attribute is set to *"Assoc"* and the *pm:AbstractContextState/pm:Validator* is set to a valid validator. In this case, the value is set to "N".

NOTE: In all other cases, the value is set to "Y".

NOTE: A corresponding inferred patient ensemble context is not required for the <<actor_somds_dec_gateway>> / <<actor_somds_acm_gateway>> in order to determine a valid *pm:PatientContextState*.
====
****
