name: Latest Master Build
    
on:
  push:
    branches:
      - master

env:
  CI: true
  
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Not needed with a .ruby-version file
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      
    - name: Create HTML with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: run --args="--input-file ../../asciidoc/sdpi-supplement.adoc --output-folder ../../sdpi-supplement --github-token ${{ secrets.SDPI_API_ACCESS_TOKEN_SECRET }} --backend html"
        build-root-directory: .ci/asciidoc-converter

    - name: Generate PlantUML diagrams and copy images
      run: .github/copy_images.sh
      
    - name: Upload artifact
      # if: success() && github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v3
      with:
        name: sdpi-supplement
        path: sdpi-supplement
